function buildRows(rows, start, count, section, reference) {
  return Array.from({ length: count }, (_, i) => {
    const r = rows[i % rows.length];
    const variante = i >= rows.length ? "Caso variante: " : "";
    return {
      id: start + i,
      section,
      topic: r[0],
      difficulty: r[1],
      text: variante + r[2],
      options: r[3],
      answer: r[4],
      explanation: r[5] || ("Respuesta correcta: " + r[3][r[4]] + "."),
      reference
    };
  });
}

const anexoA = [
  ["Hardware", "media", "En una CPU, ¿qué elemento ejecuta operaciones aritméticas y lógicas?", ["ALU", "Unidad de control", "Bus de direcciones"], 0, "La ALU realiza operaciones aritméticas y lógicas."],
  ["Hardware", "alta", "Un equipo usa constantemente paginación en disco. ¿Qué efecto es más probable?", ["Mejora por usar SSD", "Lentitud por falta de RAM", "Desactivación de caché"], 1, "La paginación continua indica presión de memoria y reduce rendimiento."],
  ["Firmware", "media", "UEFI se diferencia de BIOS tradicional porque:", ["Soporta GPT y arranque moderno", "Es una aplicación de Office", "Solo existe en servidores Linux"], 0, "UEFI es firmware moderno con más funciones de arranque."],
  ["Almacenamiento", "alta", "En un SSD frente a un HDD destaca especialmente:", ["Menor latencia y mejor lectura aleatoria", "Necesidad obligatoria de desfragmentar", "Partes mecánicas más rápidas"], 0, "El SSD no tiene partes mecánicas y reduce latencia."],
  ["Sistemas operativos", "media", "El kernel de un sistema operativo:", ["Gestiona recursos hardware y llamadas del sistema", "Es solo el escritorio gráfico", "Es un tipo de cable de red"], 0, "El kernel es el núcleo del sistema operativo."],
  ["Linux", "alta", "En permisos Linux, 640 significa:", ["rwx para todos", "rw para propietario, r para grupo, nada para otros", "Solo ejecución para grupo"], 1, "6=lectura/escritura, 4=lectura, 0=sin permisos."],
  ["Windows", "media", "Un servicio de Windows se caracteriza por:", ["Ejecutarse en segundo plano", "Ser siempre una web", "No poder iniciarse automáticamente"], 0, "Los servicios pueden ejecutarse sin interacción directa."],
  ["Redes", "media", "Una WAN conecta:", ["Equipos dentro de una misma mesa", "Redes en áreas geográficas amplias", "Solo buses internos de CPU"], 1, "WAN implica interconexión geográfica amplia."],
  ["OSI", "alta", "Un switch Ethernet trabaja principalmente con:", ["Direcciones MAC de capa 2", "Puertos USB", "Consultas SQL"], 0, "El switch aprende MAC y opera sobre capa de enlace."],
  ["Redes", "alta", "¿Qué dispositivo separa dominios de broadcast por defecto?", ["Hub", "Router", "Repetidor"], 1, "El router separa redes y dominios de broadcast."],
  ["VLAN", "alta", "Una VLAN permite:", ["Segmentación lógica de capa 2", "Cifrado automático TLS", "Sustituir DNS"], 0, "Las VLAN separan dominios lógicos dentro de la infraestructura."],
  ["IPv4", "alta", "Para 192.168.10.25/24, la red es:", ["192.168.10.0", "192.168.10.25", "192.168.10.255"], 0, "Con /24 la red es .0 y broadcast .255."],
  ["Gateway", "alta", "Si accede a su LAN pero no a Internet, revisa primero:", ["Gateway predeterminado", "Tarjeta gráfica", "Resolución de pantalla"], 0, "El gateway permite salir a otras redes."],
  ["DHCP", "media", "DHCP sirve para:", ["Resolver nombres", "Asignar configuración IP automáticamente", "Cifrar HTTPS"], 1, "DHCP entrega IP, máscara, puerta de enlace y DNS."],
  ["DNS", "alta", "Si ping a 8.8.8.8 funciona pero no navega por nombre, sospecha de:", ["DNS", "RAID", "BIOS"], 0, "Hay conectividad IP, pero falla la resolución de nombres."],
  ["ARP", "alta", "ARP relaciona:", ["IP con MAC en red local", "Usuarios con GPO", "Backups con RPO"], 0, "ARP resuelve MAC asociada a una IP local."],
  ["ICMP", "media", "La utilidad ping usa principalmente:", ["SMTP", "ICMP", "LDAP"], 1, "Ping usa mensajes ICMP Echo."],
  ["TCP/UDP", "alta", "TCP se diferencia de UDP porque:", ["TCP controla conexión y entrega", "UDP siempre cifra", "TCP solo es local"], 0, "TCP es orientado a conexión; UDP no garantiza entrega."],
  ["Puertos", "alta", "¿Qué combinación es correcta?", ["LDAP 389 / LDAPS 636", "RDP 53 / DNS 3389", "HTTP 25 / SMTP 80"], 0, "LDAP usa 389 y LDAPS 636."],
  ["NAT", "alta", "NAT se usa para:", ["Traducir direcciones privadas a públicas", "Crear tablas SQL", "Formatear discos"], 0, "NAT permite salida a Internet desde redes privadas."],
  ["TTL", "alta", "TTL evita principalmente:", ["Bucles infinitos de paquetes", "Usuarios duplicados", "Copias completas"], 0, "TTL decrece en cada salto y al llegar a cero se descarta."],
  ["MTU", "alta", "MTU indica:", ["Tamaño máximo de unidad de transmisión", "Tiempo máximo de usuario", "Número de VLAN"], 0, "MTU limita el tamaño transmisible sin fragmentación."],
  ["Seguridad", "alta", "Riesgo se relaciona mejor con:", ["Amenaza, vulnerabilidad, probabilidad e impacto", "Solo antivirus", "Solo temperatura del CPD"], 0, "El riesgo combina amenaza, vulnerabilidad e impacto/probabilidad."],
  ["Malware", "media", "El ransomware:", ["Cifra o bloquea datos y exige rescate", "Optimiza SQL", "Crea VLAN"], 0, "El ransomware extorsiona bloqueando información."],
  ["Firewall", "alta", "Un firewall filtra:", ["Tráfico según reglas", "Solo voltaje eléctrico", "Tablas relacionales"], 0, "Filtra por origen, destino, puerto, protocolo o política."],
  ["IDS/IPS", "alta", "La diferencia general IDS/IPS es:", ["IDS alerta; IPS puede bloquear", "IDS hace backups; IPS restaura", "Son lo mismo que DNS"], 0, "IDS detecta; IPS previene o bloquea."],
  ["Criptografía", "alta", "El cifrado asimétrico usa:", ["Clave pública y privada", "Una única clave para todos", "Solo hashes sin claves"], 0, "Usa par de claves pública/privada."],
  ["Hash", "alta", "Una función hash criptográfica busca:", ["Huella no reversible resistente a colisiones", "Descifrado del mensaje", "Aumentar RAM"], 0, "El hash genera una huella, no es cifrado reversible."],
  ["VPN", "alta", "Una VPN de acceso remoto permite:", ["Conexión segura a red corporativa", "Eliminar autenticación", "Crear particiones"], 0, "La VPN crea un túnel seguro autenticado."],
  ["Active Directory", "alta", "Un controlador de dominio:", ["Autentica y presta servicios del dominio", "Solo imprime documentos", "Sustituye el SAI"], 0, "El DC autentica y ofrece servicios de directorio."],
  ["AD DNS", "alta", "DNS es crítico en AD porque:", ["Localiza controladores y servicios", "Sustituye Kerberos", "Impide OU"], 0, "AD depende de registros DNS para localizar servicios."],
  ["LDAP", "alta", "LDAP se asocia con:", ["Servicios de directorio", "Paginación de RAM", "RAID 0"], 0, "LDAP consulta y accede a directorios."],
  ["Kerberos", "alta", "Kerberos usa principalmente:", ["Tickets de autenticación", "Direcciones MAC", "Discos espejo"], 0, "Kerberos autentica mediante tickets."],
  ["GPO", "alta", "Una GPO sirve para:", ["Aplicar configuraciones centralizadas", "Crear snapshots", "Asignar IP por DHCP siempre"], 0, "Las políticas de grupo administran equipos y usuarios."],
  ["Permisos", "alta", "En acceso por red a carpeta compartida con NTFS y share, aplica:", ["Permiso efectivo más restrictivo", "Siempre el más permisivo", "Solo el icono de carpeta"], 0, "Se combinan permisos y manda la restricción efectiva."],
  ["Backups", "alta", "Un snapshot no debe confundirse con:", ["Backup independiente", "Estado temporal", "Punto de reversión local"], 0, "Un snapshot no sustituye una copia externa/restaurable."],
  ["Backups", "alta", "RPO mide:", ["Datos máximos que se acepta perder en tiempo", "Tiempo de reparación física", "Número de discos"], 0, "RPO es punto de recuperación; RTO es tiempo de recuperación."],
  ["RAID", "alta", "RAID 1 consiste en:", ["Espejo", "Striping sin redundancia", "Base de datos documental"], 0, "RAID 1 duplica datos en espejo."],
  ["Virtualización", "alta", "Un hipervisor tipo 1:", ["Corre directamente sobre hardware", "Corre solo dentro de Word", "Es siempre un contenedor"], 0, "Tipo 1 es bare-metal."],
  ["Git", "alta", "git merge se utiliza para:", ["Integrar ramas", "Borrar DNS", "Asignar permisos NTFS"], 0, "merge fusiona cambios de ramas."],
  ["SQL", "alta", "CREATE, ALTER y DROP son:", ["DDL", "DML", "TCL"], 0, "DDL define estructura."],
  ["SQL", "alta", "GRANT y REVOKE pertenecen a:", ["DCL", "DQL", "DML"], 0, "DCL controla permisos."],
  ["SQL", "media", "ROLLBACK sirve para:", ["Deshacer una transacción", "Crear una VLAN", "Cifrar un certificado"], 0, "ROLLBACK revierte cambios no confirmados."],
  ["NoSQL", "alta", "Redis se clasifica habitualmente como:", ["Clave-valor en memoria", "Relacional pura", "Sistema de archivos"], 0, "Redis es clave-valor en memoria."],
  ["NoSQL", "media", "MongoDB se asocia a bases de datos:", ["Documentales", "Solo DDL", "De correo SMTP"], 0, "MongoDB almacena documentos BSON."],
  ["Programación", "media", "La recursividad requiere:", ["Caso base", "Puerto 443", "GPO enlazada"], 0, "Sin caso base puede no terminar."],
  ["Web", "media", "El front-end se ejecuta principalmente en:", ["Cliente/navegador", "SAI", "RAID"], 0, "El front-end es la parte de cliente."],
  ["Accesibilidad", "media", "La accesibilidad busca:", ["Eliminar barreras de uso", "Bloquear lectores de pantalla", "Usar solo imágenes sin texto"], 0, "Accesibilidad facilita uso por todas las personas."],
  ["CASE", "media", "Las herramientas CASE apoyan:", ["Análisis, diseño, documentación o generación de software", "Solo cableado eléctrico", "Solo cambio de tóner"], 0, "CASE ayuda al ciclo de desarrollo."],
  ["Correo", "alta", "SMTP se usa principalmente para:", ["Enviar correo", "Recibir por carpetas", "Resolver nombres"], 0, "SMTP envía; IMAP/POP3 reciben o consultan."],
  ["Contenedores", "alta", "Un contenedor se diferencia de una VM porque:", ["Comparte kernel del host", "Siempre incluye BIOS propia", "Necesita más recursos que una VM"], 0, "Los contenedores son más ligeros y comparten kernel."],
  ["SAN/NAS", "media", "NAS ofrece normalmente almacenamiento a nivel de:", ["Archivo", "Ticket Kerberos", "Puerto TCP"], 0, "NAS suele exponer almacenamiento de archivos."],
  ["Alta disponibilidad", "alta", "Alta disponibilidad busca:", ["Reducir interrupciones del servicio", "Eliminar todas las contraseñas", "Evitar monitorización"], 0, "Busca continuidad y tolerancia a fallos."],
  ["Monitorización", "media", "Monitorizar permite:", ["Detectar incidencias y tendencias", "Sustituir backups", "Evitar DNS"], 0, "Ayuda a anticipar y diagnosticar problemas."],
  ["Incidencias", "media", "Registrar prioridad y acciones en un ticket aporta:", ["Trazabilidad", "Cifrado simétrico", "Más memoria caché"], 0, "La trazabilidad facilita seguimiento y escalado."],
  ["Cliente/servidor", "media", "En arquitectura cliente/servidor:", ["El cliente solicita y el servidor presta servicio", "No existe red", "Todo se ejecuta solo en BIOS"], 0, "Es un modelo de petición y respuesta."],
  ["API", "media", "Una API permite:", ["Interacción definida entre sistemas", "Cambiar voltaje de CPU", "Eliminar usuarios AD"], 0, "Una API define cómo comunicarse con un servicio."],
  ["XML", "media", "XML se usa para:", ["Representar datos estructurados con etiquetas", "Aplicar estilos CSS únicamente", "Crear discos RAID"], 0, "XML es un lenguaje de marcado extensible."],
  ["Pruebas", "media", "Las pruebas de regresión buscan:", ["Comprobar que cambios no rompen lo que funcionaba", "Cambiar contraseñas", "Crear OU"], 0, "Detectan efectos colaterales de cambios."],
  ["Metodologías", "media", "Una metodología ágil suele trabajar con:", ["Iteraciones y entregas incrementales", "Solo documentación sin producto", "Sin revisión nunca"], 0, "Lo ágil favorece iteración y adaptación."]
];

const anexoB = [
  ["Protección de datos", "media", "Un dato personal es:", ["Información sobre persona física identificada o identificable", "Solo datos anónimos", "Solo datos de empresas"], 0],
  ["Protección de datos", "alta", "El responsable del tratamiento:", ["Decide fines y medios", "Solo obedece instrucciones", "Es siempre el antivirus"], 0],
  ["Protección de datos", "alta", "El encargado del tratamiento:", ["Trata datos por cuenta del responsable", "Decide siempre la finalidad", "Es el titular de los datos"], 0],
  ["Protección de datos", "media", "La minimización exige:", ["Tratar solo datos necesarios", "Pedir todos los datos posibles", "Publicar listados completos"], 0],
  ["Protección de datos", "media", "El derecho de supresión permite:", ["Solicitar borrado en casos previstos", "Exigir más RAM", "Cambiar DNS"], 0],
  ["Protección de datos", "alta", "Una brecha de seguridad de datos es:", ["Incidente con pérdida, alteración o acceso no autorizado", "Cambio de tóner", "Alta de un switch"], 0],
  ["Derechos digitales", "media", "La desconexión digital protege:", ["Tiempo de descanso fuera del trabajo", "La velocidad de CPU", "El puerto SMTP"], 0],
  ["Igualdad", "media", "La igualdad de trato implica:", ["Ausencia de discriminación directa o indirecta", "Trato arbitrario", "Eliminar conciliación"], 0],
  ["Igualdad", "alta", "Discriminación indirecta es:", ["Criterio neutro que causa desventaja injustificada", "Siempre insulto explícito", "Acción positiva proporcional"], 0],
  ["Igualdad", "media", "El acoso sexual implica:", ["Conducta sexual que atenta contra la dignidad", "Error DNS", "Una actualización de software"], 0],
  ["Igualdad", "media", "Las acciones positivas buscan:", ["Corregir desigualdades reales", "Eliminar méritos siempre", "Sustituir backups"], 0],
  ["Igualdad", "media", "Un plan de igualdad contiene:", ["Medidas para igualdad real y no discriminación", "Solo puertos TCP", "Solo inventario hardware"], 0],
  ["Igualdad", "alta", "La transversalidad de igualdad supone:", ["Integrarla en políticas y actuaciones", "Aplicarla solo a redes", "Ignorarla en gestión"], 0],
  ["Violencia de género", "media", "La LO 1/2004 se orienta a:", ["Protección integral frente a violencia de género", "Regular SQL", "Definir VLAN"], 0],
  ["Violencia de género", "media", "Puede incluir:", ["Violencia física, psicológica, amenazas o coacciones", "Solo daño a edificios", "Solo incidencias IT"], 0],
  ["Violencia de género", "media", "La prevención busca:", ["Detectar y evitar violencia", "Crear usuarios AD", "Aumentar MTU"], 0],
  ["Violencia de género", "media", "Los derechos de víctimas incluyen:", ["Información, asistencia y protección", "Solo correo IMAP", "Solo acceso Wi-Fi"], 0],
  ["Igualdad", "alta", "Publicidad vejatoria hacia mujeres:", ["Es contraria a igualdad y dignidad", "Es obligatoria", "Solo importa en papel"], 0],
  ["Protección de datos", "alta", "La seudonimización:", ["Impide atribuir datos sin información adicional separada", "Equivale siempre a anonimato absoluto", "Publica el DNI"], 0],
  ["Protección de datos", "media", "La limitación de finalidad exige:", ["Usar datos para fines determinados y legítimos", "Usarlos para cualquier fin", "Venderlos siempre"], 0]
];

const supuesto = [
  ["Diagnóstico red", "alta", "IP 169.254.x.x y sin red corporativa. Causa probable:", ["Fallo DHCP", "Certificado TLS", "Disco lleno"], 0],
  ["DNS", "alta", "Funciona por IP pero no por nombre. Revisar:", ["DNS local/configurado", "Monitor", "Teclado"], 0],
  ["Permisos", "alta", "Share Lectura y NTFS Modificar. Por red tendrá:", ["Lectura", "Modificar", "Control total"], 0],
  ["GPO", "alta", "Una GPO no aplica a usuario en otra OU. Probable:", ["No está enlazada/heredada en su ámbito", "RDP caído", "Falta tóner"], 0],
  ["VLAN", "alta", "Un puesto obtiene IP de otra red. Revisar:", ["VLAN del puerto de switch", "Hora del monitor", "Licencia Office"], 0],
  ["RDP", "alta", "RDP activo localmente pero no desde fuera. Revisar:", ["TCP 3389/firewall", "UDP 53", "POP3"], 0],
  ["TLS", "alta", "Aviso de certificado no confiable en HTTPS interno. Causa:", ["Certificado caducado/nombre/CA", "RAID 0", "Poca VRAM"], 0],
  ["Backups", "alta", "Backups completan pero restauración falla. Faltó:", ["Prueba periódica de restauración", "Más iconos", "Cambiar fondo"], 0],
  ["Snapshot", "alta", "Se pierde datastore con snapshots dentro. Problema:", ["No eran copia independiente", "Eran demasiado antiguos para DNS", "Kerberos bloquea"], 0],
  ["RAID", "alta", "RAID 5 degradado por fallo de un disco. Lo correcto es:", ["Sustituir disco y reconstruir cuanto antes", "Ignorarlo", "Borrar backups"], 0],
  ["Ransomware", "alta", "Mejor defensa de recuperación:", ["Backups offline/inmutables probados", "Snapshots en mismo volumen", "Contraseñas compartidas"], 0],
  ["Correo", "alta", "Puede recibir IMAP pero no enviar. Revisar:", ["SMTP 587/465/25 y autenticación", "DHCP 67", "HDMI"], 0],
  ["AD", "alta", "Un usuario no inicia sesión y aparece cuenta bloqueada. Acción:", ["Revisar intentos, desbloquear según política", "Cambiar MTU", "Crear VLAN"], 0],
  ["DNS AD", "alta", "Equipos no encuentran controlador de dominio. Revisar:", ["DNS del dominio", "Puerto HDMI", "Extensión CSS"], 0],
  ["OSI", "alta", "Sin enlace físico, no empieces por aplicación. Capa a revisar:", ["Física/enlace", "Presentación", "Sesión"], 0],
  ["Firewall", "alta", "Aplicación nueva no conecta a servidor en puerto concreto. Revisar:", ["Reglas firewall y puerto", "Fondo pantalla", "Teclado"], 0],
  ["DHCP relay", "alta", "Clientes en otra VLAN no reciben IP de DHCP central. Revisar:", ["DHCP relay/ip helper", "Certificado web", "RAID 1"], 0],
  ["VM vs contenedor", "alta", "Necesitas aislar SO completo distinto. Mejor:", ["Máquina virtual", "Contenedor simple", "Cookie"], 0],
  ["Logs", "media", "Incidencia intermitente en servidor. Primer apoyo:", ["Revisar logs y monitorización", "Formatear sin mirar", "Cambiar ratón"], 0],
  ["Parcheo", "alta", "Antes de actualizar sistema crítico conviene:", ["Backup probado y plan de reversión", "Eliminar documentación", "Desactivar alertas"], 0]
];

const inglesTecnico = [
  ["Technical English", "media", "backup", ["copia de seguridad", "pantalla", "contraseña"], 0],
  ["Technical English", "media", "restore", ["restaurar", "enviar", "imprimir"], 0],
  ["Technical English", "alta", "default gateway", ["puerta de enlace predeterminada", "memoria caché", "clave primaria"], 0],
  ["Technical English", "alta", "packet loss", ["pérdida de paquetes", "bloqueo de cuenta", "copia completa"], 0],
  ["Technical English", "media", "latency", ["latencia", "licencia", "librería"], 0],
  ["Technical English", "alta", "credentials", ["credenciales", "cables", "consultas"], 0],
  ["Technical English", "alta", "encryption", ["cifrado", "enrutamiento", "arranque"], 0],
  ["Technical English", "media", "certificate", ["certificado", "servidor", "incidencia"], 0],
  ["Technical English", "media", "firewall", ["cortafuegos", "disco duro", "usuario"], 0],
  ["Technical English", "alta", "endpoint", ["puesto/dispositivo final", "punto de montaje exclusivo", "tabla SQL"], 0],
  ["Technical English", "alta", "root cause", ["causa raíz", "raíz cuadrada", "usuario root siempre"], 0],
  ["Technical English", "media", "troubleshooting", ["diagnóstico y resolución de problemas", "copia diferencial", "cifrado físico"], 0],
  ["Technical English", "alta", "account locked out", ["cuenta bloqueada", "cuenta eliminada", "correo enviado"], 0],
  ["Technical English", "media", "read-only access", ["acceso de solo lectura", "acceso total", "sin acceso"], 0],
  ["Technical English", "alta", "high availability", ["alta disponibilidad", "alta latencia", "alta resolución"], 0],
  ["Technical English", "media", "load balancer", ["balanceador de carga", "cargador portátil", "disco espejo"], 0],
  ["Technical English", "alta", "rollback", ["reversión", "reenvío", "renombrado"], 0],
  ["Technical English", "media", "outage", ["interrupción del servicio", "salida de vídeo", "permiso de lectura"], 0],
  ["Technical English", "alta", "deprecated", ["obsoleto/desaconsejado", "cifrado", "obligatorio"], 0],
  ["Technical English", "media", "shared folder", ["carpeta compartida", "pantalla duplicada", "puerto cerrado"], 0]
];

const inglesGeneral = [
  ["Grammar", "A2", "Complete: I ___ a technician.", ["am", "are", "is", "be"], 0],
  ["Grammar", "A2", "Complete: She ___ in the office today.", ["work", "works", "working", "worked"], 1],
  ["Past simple", "A2", "Complete: Yesterday I ___ the report.", ["send", "sended", "sent", "sending"], 2],
  ["Prepositions", "A2", "The meeting is ___ 9:00.", ["in", "on", "at", "to"], 2],
  ["Modal", "A2", "You ___ wear your ID card. It is required.", ["must", "might", "can", "would"], 0],
  ["Present perfect", "B1", "I ___ here since 2022.", ["work", "worked", "have worked", "am work"], 2],
  ["Since/for", "B1", "We have waited ___ two hours.", ["since", "for", "from", "during"], 1],
  ["Connectors", "B1", "I was tired, ___ I finished the task.", ["because", "so", "but", "although"], 2],
  ["Prepositions", "B1", "The file is attached ___ this email.", ["to", "at", "on", "by"], 0],
  ["Future", "B1", "I think it ___ rain tomorrow.", ["will", "is", "has", "does"], 0],
  ["Conditional", "B1", "If the printer fails, ___ support.", ["call", "called", "calling", "to call"], 0],
  ["Comparative", "B1", "This laptop is ___ than the old one.", ["fast", "faster", "fastest", "more fast"], 1],
  ["Quantifiers", "B1", "There isn't ___ time left.", ["many", "much", "few", "several"], 1],
  ["Passive", "B1", "The tickets ___ checked at the entrance.", ["is", "are", "do", "has"], 1],
  ["Vocabulary", "B1", "A deadline is:", ["latest time/date to finish", "a password", "a printer line", "a meeting room"], 0],
  ["Present perfect", "B2", "I ___ three incidents this morning, and two are still open.", ["logged", "have logged", "was log", "logging"], 1],
  ["Connector", "B2", "___ the system was updated, the error continued.", ["Although", "Because", "So", "Unless"], 0],
  ["Relative", "B2", "The technician ___ fixed it is on duty.", ["which", "who", "where", "whose"], 1],
  ["Modal perfect", "B2", "You ___ have told me earlier.", ["should", "mustn't", "can", "may"], 0],
  ["Passive", "B2", "The policy ___ approved last week.", ["was", "has", "did", "is"], 0],
  ["Reported speech", "B2", "He said he ___ remotely.", ["is working", "was working", "works", "has working"], 1],
  ["Preposition", "B2", "We must comply ___ the policy.", ["to", "with", "on", "for"], 1],
  ["Conditional", "B2", "If I had time, I ___ the logs.", ["review", "will review", "would review", "reviewed"], 2],
  ["Vocabulary", "B2", "Reliable means:", ["dependable", "expensive", "temporary", "confused"], 0],
  ["Connector", "B2", "The server was overloaded; ___, users could not log in.", ["however", "therefore", "unless", "despite"], 1],
  ["Article", "B2", "She works as ___ IT support technician.", ["a", "an", "the", "no article"], 1],
  ["C1 connector", "C1", "The procedure is slow; ___, it reduces risk.", ["nevertheless", "because", "unless", "whereas not"], 0],
  ["C1 grammar", "C1", "Choose correct: ___ known earlier, we would have acted.", ["Had we", "Have we", "Did we", "Were we"], 0],
  ["C1 vocabulary", "C1", "Mitigate means:", ["reduce severity", "ignore", "create", "translate"], 0],
  ["C2 grammar", "C2", "No sooner ___ restored than another alert appeared.", ["the system had", "had the system been", "was the system", "the system was"], 1]
];

const questions = [
  ...buildRows(anexoA, 1, 80, "Anexo A", "Programa AENA IIIJ05 2026 - Anexo A"),
  ...buildRows(anexoB, 81, 20, "Anexo B", "Programa AENA IIIJ05 2026 - Anexo B"),
  ...buildRows(supuesto, 101, 20, "Supuesto teórico-práctico", "Programa AENA IIIJ05 2026 - Supuesto teórico-práctico"),
  ...buildRows(inglesTecnico, 121, 20, "Inglés técnico", "Programa AENA IIIJ05 2026 - Inglés técnico"),
  ...buildRows(inglesGeneral, 141, 60, "Inglés escrito general", "Programa AENA IIIJ05 2026 - Inglés escrito general")
];

console.assert(questions.length === 200, "aena09.js debe tener 200 preguntas");