const questions = [
  {
    id: 1,
    section: "Bloque 5",
    topic: "Modelo OSI",
    difficulty: "easy",
    text: "¿Cuántas capas tiene el modelo OSI?",
    options: ["4", "5", "7"],
    answer: 2,
    explanation: "El modelo OSI tiene 7 capas.",
    reference: "Bloque IV - Sistemas y Comunicaciones - Modelo OSI"
  },
  {
    id: 2,
    section: "Bloque 5",
    topic: "Modelo OSI",
    difficulty: "easy",
    text: "¿Cuál es la capa 1 del modelo OSI?",
    options: ["Física", "Enlace de datos", "Red"],
    answer: 0,
    explanation: "La capa 1 es la capa física.",
    reference: "Modelo OSI"
  },
  {
    id: 3,
    section: "Bloque 5",
    topic: "Modelo OSI",
    difficulty: "easy",
    text: "¿Cuál es la capa 2 del modelo OSI?",
    options: ["Red", "Enlace de datos", "Transporte"],
    answer: 1,
    explanation: "La capa 2 es enlace de datos.",
    reference: "Modelo OSI"
  },
  {
    id: 4,
    section: "Bloque 5",
    topic: "Modelo OSI",
    difficulty: "easy",
    text: "¿Cuál es la capa 3 del modelo OSI?",
    options: ["Red", "Sesión", "Aplicación"],
    answer: 0,
    explanation: "La capa 3 es la capa de red.",
    reference: "Modelo OSI"
  },
  {
    id: 5,
    section: "Bloque 5",
    topic: "Modelo OSI",
    difficulty: "easy",
    text: "¿Cuál es la capa 4 del modelo OSI?",
    options: ["Transporte", "Presentación", "Física"],
    answer: 0,
    explanation: "La capa 4 es transporte.",
    reference: "Modelo OSI"
  },
  {
    id: 6,
    section: "Bloque 5",
    topic: "Modelo OSI",
    difficulty: "easy",
    text: "¿Cuál es la capa 5 del modelo OSI?",
    options: ["Sesión", "Red", "Enlace"],
    answer: 0,
    explanation: "La capa 5 es sesión.",
    reference: "Modelo OSI"
  },
  {
    id: 7,
    section: "Bloque 5",
    topic: "Modelo OSI",
    difficulty: "easy",
    text: "¿Cuál es la capa 6 del modelo OSI?",
    options: ["Aplicación", "Presentación", "Transporte"],
    answer: 1,
    explanation: "La capa 6 es presentación.",
    reference: "Modelo OSI"
  },
  {
    id: 8,
    section: "Bloque 5",
    topic: "Modelo OSI",
    difficulty: "easy",
    text: "¿Cuál es la capa 7 del modelo OSI?",
    options: ["Aplicación", "Sesión", "Red"],
    answer: 0,
    explanation: "La capa 7 es aplicación.",
    reference: "Modelo OSI"
  },
  {
    id: 9,
    section: "Bloque 5",
    topic: "PDU",
    difficulty: "easy",
    text: "¿Cuál es la PDU de la capa física?",
    options: ["Bits", "Tramas", "Paquetes"],
    answer: 0,
    explanation: "En la capa física se transmiten bits.",
    reference: "Modelo OSI - PDU"
  },
  {
    id: 10,
    section: "Bloque 5",
    topic: "PDU",
    difficulty: "easy",
    text: "¿Cuál es la PDU de la capa de enlace de datos?",
    options: ["Trama", "Paquete", "Segmento"],
    answer: 0,
    explanation: "En enlace de datos la PDU es la trama.",
    reference: "Modelo OSI - PDU"
  },
  {
    id: 11,
    section: "Bloque 5",
    topic: "PDU",
    difficulty: "easy",
    text: "¿Cuál es la PDU de la capa de red?",
    options: ["Segmento", "Paquete", "Bit"],
    answer: 1,
    explanation: "En la capa de red la PDU es el paquete.",
    reference: "Modelo OSI - PDU"
  },
  {
    id: 12,
    section: "Bloque 5",
    topic: "PDU",
    difficulty: "easy",
    text: "¿Cuál es la PDU de la capa de transporte?",
    options: ["Trama", "Segmento", "Bit"],
    answer: 1,
    explanation: "En transporte la PDU suele llamarse segmento.",
    reference: "Modelo OSI - PDU"
  },
  {
    id: 13,
    section: "Bloque 5",
    topic: "Capas OSI",
    difficulty: "medium",
    text: "¿Qué capa OSI se encarga del direccionamiento lógico IP?",
    options: ["Enlace de datos", "Red", "Transporte"],
    answer: 1,
    explanation: "El direccionamiento IP pertenece a la capa de red.",
    reference: "Modelo OSI - Capa 3"
  },
  {
    id: 14,
    section: "Bloque 5",
    topic: "Capas OSI",
    difficulty: "medium",
    text: "¿Qué capa OSI se relaciona con las direcciones MAC?",
    options: ["Física", "Enlace de datos", "Red"],
    answer: 1,
    explanation: "Las direcciones MAC operan en la capa de enlace.",
    reference: "Modelo OSI - Capa 2"
  },
  {
    id: 15,
    section: "Bloque 5",
    topic: "Capas OSI",
    difficulty: "medium",
    text: "¿Qué capa OSI se encarga del encaminamiento entre redes?",
    options: ["Red", "Transporte", "Sesión"],
    answer: 0,
    explanation: "El routing o encaminamiento pertenece a la capa de red.",
    reference: "Modelo OSI - Capa 3"
  },
  {
    id: 16,
    section: "Bloque 5",
    topic: "Dispositivos",
    difficulty: "medium",
    text: "¿En qué capa OSI trabaja principalmente un switch tradicional?",
    options: ["Capa 1", "Capa 2", "Capa 3"],
    answer: 1,
    explanation: "Un switch tradicional conmuta tramas usando direcciones MAC.",
    reference: "Modelo OSI - Dispositivos"
  },
  {
    id: 17,
    section: "Bloque 5",
    topic: "Dispositivos",
    difficulty: "medium",
    text: "¿En qué capa OSI trabaja principalmente un router?",
    options: ["Capa 2", "Capa 3", "Capa 4"],
    answer: 1,
    explanation: "El router trabaja en capa 3 porque enruta paquetes IP.",
    reference: "Modelo OSI - Dispositivos"
  },
  {
    id: 18,
    section: "Bloque 5",
    topic: "Dispositivos",
    difficulty: "medium",
    text: "¿En qué capa OSI trabaja un hub?",
    options: ["Física", "Enlace", "Red"],
    answer: 0,
    explanation: "El hub repite señales a nivel físico.",
    reference: "Modelo OSI - Dispositivos"
  },
  {
    id: 19,
    section: "Bloque 5",
    topic: "Protocolos",
    difficulty: "medium",
    text: "¿En qué capa del modelo OSI se sitúa IP?",
    options: ["Red", "Transporte", "Aplicación"],
    answer: 0,
    explanation: "IP pertenece a la capa de red.",
    reference: "Modelo OSI - TCP/IP"
  },
  {
    id: 20,
    section: "Bloque 5",
    topic: "Protocolos",
    difficulty: "medium",
    text: "¿En qué capa del modelo OSI se sitúa TCP?",
    options: ["Red", "Transporte", "Sesión"],
    answer: 1,
    explanation: "TCP es un protocolo de transporte.",
    reference: "Modelo OSI - TCP/IP"
  },
  {
    id: 21,
    section: "Bloque 5",
    topic: "Protocolos",
    difficulty: "medium",
    text: "¿En qué capa del modelo OSI se sitúa UDP?",
    options: ["Transporte", "Aplicación", "Enlace"],
    answer: 0,
    explanation: "UDP pertenece a la capa de transporte.",
    reference: "Modelo OSI - TCP/IP"
  },
  {
    id: 22,
    section: "Bloque 5",
    topic: "Protocolos",
    difficulty: "medium",
    text: "¿En qué capa OSI se sitúa HTTP?",
    options: ["Aplicación", "Transporte", "Red"],
    answer: 0,
    explanation: "HTTP es un protocolo de aplicación.",
    reference: "Modelo OSI - Aplicación"
  },
  {
    id: 23,
    section: "Bloque 5",
    topic: "Protocolos",
    difficulty: "medium",
    text: "¿En qué capa OSI se sitúa FTP?",
    options: ["Aplicación", "Presentación", "Física"],
    answer: 0,
    explanation: "FTP es un protocolo de aplicación.",
    reference: "Modelo OSI - Aplicación"
  },
  {
    id: 24,
    section: "Bloque 5",
    topic: "Protocolos",
    difficulty: "medium",
    text: "¿En qué capa OSI se sitúa SMTP?",
    options: ["Sesión", "Aplicación", "Red"],
    answer: 1,
    explanation: "SMTP es un protocolo de aplicación para correo saliente.",
    reference: "Modelo OSI - Aplicación"
  },
  {
    id: 25,
    section: "Bloque 5",
    topic: "Protocolos",
    difficulty: "medium",
    text: "¿En qué capa OSI se sitúa DNS?",
    options: ["Aplicación", "Transporte", "Enlace"],
    answer: 0,
    explanation: "DNS es un servicio de aplicación.",
    reference: "Modelo OSI - Aplicación"
  },
  {
    id: 26,
    section: "Bloque 5",
    topic: "Protocolos",
    difficulty: "medium",
    text: "¿Qué capa OSI se encarga del control extremo a extremo de la comunicación?",
    options: ["Transporte", "Red", "Enlace"],
    answer: 0,
    explanation: "La capa de transporte gestiona comunicación extremo a extremo.",
    reference: "Modelo OSI - Capa 4"
  },
  {
    id: 27,
    section: "Bloque 5",
    topic: "Protocolos",
    difficulty: "medium",
    text: "¿Qué capa OSI se asocia a los puertos TCP y UDP?",
    options: ["Red", "Transporte", "Aplicación"],
    answer: 1,
    explanation: "Los puertos pertenecen a la capa de transporte.",
    reference: "Modelo OSI - Capa 4"
  },
  {
    id: 28,
    section: "Bloque 5",
    topic: "Capas OSI",
    difficulty: "medium",
    text: "¿Qué capa OSI se encarga de la representación, codificación o cifrado de los datos?",
    options: ["Presentación", "Sesión", "Aplicación"],
    answer: 0,
    explanation: "La capa de presentación gestiona formato, codificación y cifrado.",
    reference: "Modelo OSI - Capa 6"
  },
  {
    id: 29,
    section: "Bloque 5",
    topic: "Capas OSI",
    difficulty: "medium",
    text: "¿Qué capa OSI establece, mantiene y finaliza sesiones entre aplicaciones?",
    options: ["Sesión", "Transporte", "Red"],
    answer: 0,
    explanation: "La capa de sesión gestiona sesiones de comunicación.",
    reference: "Modelo OSI - Capa 5"
  },
  {
    id: 30,
    section: "Bloque 5",
    topic: "Capas OSI",
    difficulty: "medium",
    text: "¿Qué capa OSI proporciona servicios directamente a las aplicaciones del usuario?",
    options: ["Aplicación", "Presentación", "Transporte"],
    answer: 0,
    explanation: "La capa de aplicación ofrece servicios de red a las aplicaciones.",
    reference: "Modelo OSI - Capa 7"
  },
  {
    id: 31,
    section: "Bloque 5",
    topic: "Encapsulación",
    difficulty: "medium",
    text: "Durante la encapsulación, ¿qué ocurre al bajar por las capas OSI?",
    options: ["Se eliminan cabeceras", "Se añaden cabeceras", "Se destruyen los datos"],
    answer: 1,
    explanation: "Al bajar por las capas se añaden cabeceras de control.",
    reference: "Modelo OSI - Encapsulación"
  },
  {
    id: 32,
    section: "Bloque 5",
    topic: "Encapsulación",
    difficulty: "medium",
    text: "¿Qué proceso ocurre al recibir datos y subir por las capas OSI?",
    options: ["Encapsulación", "Desencapsulación", "Fragmentación física"],
    answer: 1,
    explanation: "Al subir por las capas se desencapsulan los datos.",
    reference: "Modelo OSI - Encapsulación"
  },
  {
    id: 33,
    section: "Bloque 5",
    topic: "PDU",
    difficulty: "medium",
    text: "¿Cuál es el orden correcto de PDU desde transporte hasta física?",
    options: ["Segmento, paquete, trama, bits", "Paquete, segmento, bits, trama", "Trama, paquete, segmento, bits"],
    answer: 0,
    explanation: "Transporte: segmento; red: paquete; enlace: trama; física: bits.",
    reference: "Modelo OSI - PDU"
  },
  {
    id: 34,
    section: "Bloque 5",
    topic: "Capas OSI",
    difficulty: "medium",
    text: "¿Qué capa OSI detecta errores de transmisión dentro de una red local mediante tramas?",
    options: ["Enlace de datos", "Red", "Aplicación"],
    answer: 0,
    explanation: "La capa de enlace trabaja con tramas y control de errores local.",
    reference: "Modelo OSI - Capa 2"
  },
  {
    id: 35,
    section: "Bloque 5",
    topic: "Capas OSI",
    difficulty: "medium",
    text: "¿Qué capa OSI define medios físicos, conectores, señales eléctricas u ópticas?",
    options: ["Física", "Enlace", "Red"],
    answer: 0,
    explanation: "La capa física define la transmisión real por el medio.",
    reference: "Modelo OSI - Capa 1"
  },
  {
    id: 36,
    section: "Bloque 5",
    topic: "Comparación OSI/TCP-IP",
    difficulty: "hard",
    text: "En el modelo TCP/IP, ¿qué capas OSI suelen agruparse en la capa de aplicación?",
    options: ["Aplicación, presentación y sesión", "Red, enlace y física", "Transporte, red y enlace"],
    answer: 0,
    explanation: "TCP/IP agrupa aplicación, presentación y sesión en su capa de aplicación.",
    reference: "Modelo OSI y TCP/IP"
  },
  {
    id: 37,
    section: "Bloque 5",
    topic: "Comparación OSI/TCP-IP",
    difficulty: "hard",
    text: "¿Qué capa del modelo TCP/IP equivale aproximadamente a la capa 3 OSI?",
    options: ["Internet", "Aplicación", "Acceso a red"],
    answer: 0,
    explanation: "La capa Internet de TCP/IP se corresponde con red en OSI.",
    reference: "Modelo OSI y TCP/IP"
  },
  {
    id: 38,
    section: "Bloque 5",
    topic: "Comparación OSI/TCP-IP",
    difficulty: "hard",
    text: "¿Qué capas OSI se relacionan con la capa de acceso a red del modelo TCP/IP?",
    options: ["Física y enlace", "Sesión y presentación", "Red y transporte"],
    answer: 0,
    explanation: "TCP/IP suele agrupar física y enlace como acceso a red.",
    reference: "Modelo OSI y TCP/IP"
  },
  {
    id: 39,
    section: "Bloque 5",
    topic: "Protocolos",
    difficulty: "hard",
    text: "¿En qué capa OSI encaja ARP de forma más habitual en preguntas tipo test?",
    options: ["Enlace de datos", "Aplicación", "Sesión"],
    answer: 0,
    explanation: "ARP relaciona IP con MAC y suele ubicarse en enlace de datos.",
    reference: "Modelo OSI - ARP"
  },
  {
    id: 40,
    section: "Bloque 5",
    topic: "Protocolos",
    difficulty: "hard",
    text: "¿Qué protocolo se usa para comprobar conectividad y se asocia a la capa de red?",
    options: ["ICMP", "SMTP", "FTP"],
    answer: 0,
    explanation: "ICMP trabaja asociado a IP en la capa de red.",
    reference: "Modelo OSI - ICMP"
  },
  {
    id: 41,
    section: "Bloque 5",
    topic: "Dispositivos",
    difficulty: "hard",
    text: "Un switch de capa 3 combina funciones de switch y de:",
    options: ["Router", "Hub", "Repetidor"],
    answer: 0,
    explanation: "Un switch capa 3 puede enrutar tráfico entre redes o VLAN.",
    reference: "Modelo OSI - Dispositivos"
  },
  {
    id: 42,
    section: "Bloque 5",
    topic: "VLAN",
    difficulty: "hard",
    text: "¿En qué capa OSI se asocia principalmente el funcionamiento básico de una VLAN?",
    options: ["Enlace de datos", "Transporte", "Aplicación"],
    answer: 0,
    explanation: "Las VLAN operan principalmente en capa 2 mediante etiquetado de tramas.",
    reference: "Modelo OSI - VLAN"
  },
  {
    id: 43,
    section: "Bloque 5",
    topic: "VLAN",
    difficulty: "hard",
    text: "¿Qué estándar se asocia al etiquetado VLAN en tramas Ethernet?",
    options: ["IEEE 802.1Q", "IEEE 802.11", "IEEE 802.3af"],
    answer: 0,
    explanation: "802.1Q es el estándar de etiquetado VLAN.",
    reference: "Modelo OSI - VLAN"
  },
  {
    id: 44,
    section: "Bloque 5",
    topic: "Errores típicos",
    difficulty: "hard",
    text: "¿Qué afirmación es correcta?",
    options: ["MAC es capa 2 e IP es capa 3", "MAC es capa 3 e IP es capa 2", "MAC e IP son capa 4"],
    answer: 0,
    explanation: "MAC pertenece a enlace; IP pertenece a red.",
    reference: "Modelo OSI - MAC/IP"
  },
  {
    id: 45,
    section: "Bloque 5",
    topic: "Errores típicos",
    difficulty: "hard",
    text: "¿Qué afirmación es correcta sobre TCP y UDP?",
    options: ["Son protocolos de transporte", "Son protocolos de red", "Son protocolos físicos"],
    answer: 0,
    explanation: "TCP y UDP trabajan en la capa 4, transporte.",
    reference: "Modelo OSI - Transporte"
  },
  {
    id: 46,
    section: "Bloque 5",
    topic: "Errores típicos",
    difficulty: "hard",
    text: "¿Qué afirmación es correcta sobre HTTP y HTTPS?",
    options: ["Son protocolos de aplicación", "Son protocolos de enlace", "Son protocolos físicos"],
    answer: 0,
    explanation: "HTTP y HTTPS se ubican en la capa de aplicación.",
    reference: "Modelo OSI - Aplicación"
  },
  {
    id: 47,
    section: "Bloque 5",
    topic: "Puertos",
    difficulty: "hard",
    text: "Los puertos 80 y 443 se relacionan con protocolos de aplicación, pero el concepto de puerto pertenece a:",
    options: ["Transporte", "Red", "Física"],
    answer: 0,
    explanation: "Los puertos son identificadores de la capa de transporte.",
    reference: "Modelo OSI - Puertos"
  },
  {
    id: 48,
    section: "Bloque 5",
    topic: "Capas OSI",
    difficulty: "hard",
    text: "¿Qué capa OSI se encarga de dividir los datos en segmentos y controlar el flujo extremo a extremo?",
    options: ["Transporte", "Red", "Enlace"],
    answer: 0,
    explanation: "La segmentación y control extremo a extremo son funciones de transporte.",
    reference: "Modelo OSI - Capa 4"
  },
  {
    id: 49,
    section: "Bloque 5",
    topic: "Capas OSI",
    difficulty: "hard",
    text: "¿Qué capa OSI decide la ruta que seguirá un paquete entre redes diferentes?",
    options: ["Red", "Enlace", "Presentación"],
    answer: 0,
    explanation: "La capa de red decide rutas mediante direccionamiento lógico.",
    reference: "Modelo OSI - Capa 3"
  },
  {
    id: 50,
    section: "Bloque 5",
    topic: "Modelo OSI",
    difficulty: "hard",
    text: "¿Cuál es el orden correcto de las capas OSI de la 7 a la 1?",
    options: [
      "Aplicación, presentación, sesión, transporte, red, enlace, física",
      "Aplicación, sesión, presentación, red, transporte, enlace, física",
      "Física, enlace, red, transporte, sesión, presentación, aplicación"
    ],
    answer: 0,
    explanation: "De 7 a 1: aplicación, presentación, sesión, transporte, red, enlace y física.",
    reference: "Modelo OSI"
  }
];