const questions = [
  { id:"T04-001", section:"TEÓRICA", topic:"OSI", difficulty:3, text:"¿En qué capa del modelo OSI trabaja principalmente el protocolo IP?", options:["Red","Transporte","Enlace"], answer:0, explanation:"IP trabaja en la capa 3 del modelo OSI, llamada capa de Red.", reference:"Modelo OSI" },
  { id:"T04-002", section:"TEÓRICA", topic:"OSI", difficulty:3, text:"¿Cuál es la PDU de la capa de enlace de datos?", options:["Trama","Paquete","Segmento"], answer:0, explanation:"La PDU de la capa de Enlace de Datos es la trama.", reference:"Modelo OSI" },
  { id:"T04-003", section:"TEÓRICA", topic:"OSI", difficulty:3, text:"¿Qué capa del modelo OSI se encarga del direccionamiento MAC?", options:["Enlace","Red","Transporte"], answer:0, explanation:"La capa de Enlace usa direcciones MAC para identificar interfaces físicas.", reference:"Modelo OSI" },
  { id:"T04-004", section:"TEÓRICA", topic:"OSI", difficulty:3, text:"¿Qué capa del modelo OSI se encarga del cifrado y formato de los datos?", options:["Presentación","Sesión","Aplicación"], answer:0, explanation:"La capa de Presentación se encarga del formato, codificación, compresión y cifrado de datos.", reference:"Modelo OSI" },
  { id:"T04-005", section:"TEÓRICA", topic:"OSI", difficulty:3, text:"¿Qué capa del modelo OSI establece, mantiene y finaliza sesiones entre aplicaciones?", options:["Sesión","Transporte","Aplicación"], answer:0, explanation:"La capa de Sesión gestiona el establecimiento, mantenimiento y cierre de sesiones.", reference:"Modelo OSI" },

  { id:"T04-006", section:"TEÓRICA", topic:"TCP/IP", difficulty:3, text:"¿Qué protocolo se usa para resolver una dirección IP en una dirección MAC?", options:["ARP","DNS","ICMP"], answer:0, explanation:"ARP permite conocer la dirección MAC asociada a una IP dentro de una red local.", reference:"TCP/IP" },
  { id:"T04-007", section:"TEÓRICA", topic:"TCP/IP", difficulty:2, text:"¿Qué protocolo asigna automáticamente direcciones IP a los equipos de una red?", options:["DHCP","DNS","SMTP"], answer:0, explanation:"DHCP asigna automáticamente IP, máscara, puerta de enlace y DNS.", reference:"Servicios de red" },
  { id:"T04-008", section:"TEÓRICA", topic:"TCP/IP", difficulty:2, text:"¿Qué protocolo traduce nombres de dominio a direcciones IP?", options:["DNS","DHCP","ARP"], answer:0, explanation:"DNS resuelve nombres de dominio como ejemplo.com en direcciones IP.", reference:"Servicios de red" },
  { id:"T04-009", section:"TEÓRICA", topic:"TCP/IP", difficulty:3, text:"¿Qué protocolo se usa habitualmente para comprobar conectividad mediante ping?", options:["ICMP","TCP","UDP"], answer:0, explanation:"Ping utiliza mensajes ICMP Echo Request y Echo Reply.", reference:"TCP/IP" },
  { id:"T04-010", section:"TEÓRICA", topic:"TCP/IP", difficulty:3, text:"¿Qué protocolo ofrece conexión fiable, control de errores y control de flujo?", options:["TCP","UDP","IP"], answer:0, explanation:"TCP es orientado a conexión y garantiza entrega fiable y ordenada.", reference:"TCP/IP" },

  { id:"T04-011", section:"TEÓRICA", topic:"TCP/IP", difficulty:3, text:"¿Qué protocolo es no orientado a conexión y se usa cuando prima la velocidad?", options:["UDP","TCP","HTTP"], answer:0, explanation:"UDP no establece conexión previa ni garantiza entrega, por eso es más ligero.", reference:"TCP/IP" },
  { id:"T04-012", section:"TEÓRICA", topic:"Puertos", difficulty:2, text:"¿Qué puerto usa HTTP por defecto?", options:["80","443","21"], answer:0, explanation:"HTTP utiliza por defecto el puerto TCP 80.", reference:"Puertos TCP/IP" },
  { id:"T04-013", section:"TEÓRICA", topic:"Puertos", difficulty:2, text:"¿Qué puerto usa HTTPS por defecto?", options:["443","80","25"], answer:0, explanation:"HTTPS utiliza por defecto el puerto TCP 443.", reference:"Puertos TCP/IP" },
  { id:"T04-014", section:"TEÓRICA", topic:"Puertos", difficulty:3, text:"¿Qué puerto usa DNS normalmente?", options:["53","67","110"], answer:0, explanation:"DNS utiliza normalmente el puerto 53, tanto TCP como UDP según el caso.", reference:"Puertos TCP/IP" },
  { id:"T04-015", section:"TEÓRICA", topic:"Puertos", difficulty:3, text:"¿Qué puerto usa SMTP por defecto?", options:["25","143","110"], answer:0, explanation:"SMTP usa habitualmente el puerto 25 para envío de correo entre servidores.", reference:"Correo electrónico" },

  { id:"T04-016", section:"TEÓRICA", topic:"Puertos", difficulty:3, text:"¿Qué puerto usa POP3 por defecto?", options:["110","143","993"], answer:0, explanation:"POP3 usa por defecto el puerto 110.", reference:"Correo electrónico" },
  { id:"T04-017", section:"TEÓRICA", topic:"Puertos", difficulty:3, text:"¿Qué puerto usa IMAP por defecto?", options:["143","110","25"], answer:0, explanation:"IMAP usa por defecto el puerto 143.", reference:"Correo electrónico" },
  { id:"T04-018", section:"TEÓRICA", topic:"Dispositivos de red", difficulty:2, text:"¿Qué dispositivo trabaja principalmente en la capa física y repite señales?", options:["Hub","Switch","Router"], answer:0, explanation:"El hub trabaja en capa física y repite señales sin analizar direcciones.", reference:"Redes locales" },
  { id:"T04-019", section:"TEÓRICA", topic:"Dispositivos de red", difficulty:2, text:"¿Qué dispositivo toma decisiones usando direcciones MAC?", options:["Switch","Router","Hub"], answer:0, explanation:"El switch opera principalmente en capa 2 y conmuta usando direcciones MAC.", reference:"Redes locales" },
  { id:"T04-020", section:"TEÓRICA", topic:"Dispositivos de red", difficulty:2, text:"¿Qué dispositivo conecta redes distintas usando direcciones IP?", options:["Router","Switch","Hub"], answer:0, explanation:"El router trabaja en capa de Red y conecta redes diferentes mediante IP.", reference:"Redes locales" },

  { id:"T04-021", section:"TEÓRICA", topic:"LAN", difficulty:2, text:"¿Qué dirección identifica físicamente una interfaz Ethernet?", options:["MAC","IP","DNS"], answer:0, explanation:"La dirección MAC identifica físicamente una interfaz de red.", reference:"Redes locales" },
  { id:"T04-022", section:"TEÓRICA", topic:"LAN", difficulty:3, text:"¿Qué tecnología permite dividir lógicamente una red local?", options:["VLAN","NAT","DHCP"], answer:0, explanation:"Una VLAN divide una red física en varias redes lógicas.", reference:"Redes locales" },
  { id:"T04-023", section:"TEÓRICA", topic:"LAN", difficulty:3, text:"¿Qué problema reduce una VLAN?", options:["El tamaño del dominio de broadcast","La velocidad del procesador","La capacidad del disco"], answer:0, explanation:"Las VLAN reducen el dominio de broadcast al segmentar lógicamente la red.", reference:"Redes locales" },
  { id:"T04-024", section:"TEÓRICA", topic:"Medios de transmisión", difficulty:2, text:"¿Qué medio de transmisión usa pares de cobre trenzados?", options:["UTP","Fibra óptica","Radiofrecuencia"], answer:0, explanation:"El cable UTP usa pares de cobre trenzados.", reference:"Medios de transmisión" },
  { id:"T04-025", section:"TEÓRICA", topic:"Medios de transmisión", difficulty:2, text:"¿Qué medio usa pulsos de luz para transmitir datos?", options:["Fibra óptica","Cable coaxial","UTP"], answer:0, explanation:"La fibra óptica transmite datos mediante pulsos de luz.", reference:"Medios de transmisión" },

  { id:"T04-026", section:"TEÓRICA", topic:"Internet", difficulty:3, text:"¿Qué mecanismo permite que varios equipos privados salgan a Internet usando una IP pública?", options:["NAT","DNS","ARP"], answer:0, explanation:"NAT traduce direcciones privadas a una dirección pública compartida.", reference:"Internet y TCP/IP" },
  { id:"T04-027", section:"TEÓRICA", topic:"Internet", difficulty:2, text:"¿Qué protocolo seguro sustituye funcionalmente a HTTP sin cifrar?", options:["HTTPS","FTP","Telnet"], answer:0, explanation:"HTTPS añade cifrado mediante TLS sobre HTTP.", reference:"Internet" },
  { id:"T04-028", section:"TEÓRICA", topic:"Internet", difficulty:2, text:"¿Qué tecnología permite crear una conexión segura a una red remota?", options:["VPN","VLAN","DHCP"], answer:0, explanation:"Una VPN crea un túnel seguro hacia una red remota.", reference:"Seguridad en redes" },

  { id:"T04-029", section:"TEÓRICA", topic:"Seguridad", difficulty:3, text:"¿Qué garantiza principalmente la firma digital?", options:["Autenticidad e integridad","Mayor ancho de banda","Asignación automática de IP"], answer:0, explanation:"La firma digital permite verificar quién firma y que el contenido no se ha modificado.", reference:"Criptografía" },
  { id:"T04-030", section:"TEÓRICA", topic:"Seguridad", difficulty:3, text:"¿Qué tipo de cifrado usa una pareja de claves pública y privada?", options:["Asimétrico","Simétrico","Hash"], answer:0, explanation:"El cifrado asimétrico utiliza una clave pública y una clave privada.", reference:"Criptografía" },
  { id:"T04-031", section:"TEÓRICA", topic:"Seguridad", difficulty:3, text:"¿Qué función tiene un hash criptográfico?", options:["Generar una huella única de datos","Comprimir vídeo","Asignar direcciones IP"], answer:0, explanation:"Un hash genera una huella digital que permite comprobar integridad.", reference:"Criptografía" },
  { id:"T04-032", section:"TEÓRICA", topic:"Seguridad", difficulty:2, text:"¿Qué tipo de malware cifra archivos y pide rescate?", options:["Ransomware","Spyware","Adware"], answer:0, explanation:"El ransomware cifra archivos y exige un rescate económico.", reference:"Amenazas" },
  { id:"T04-033", section:"TEÓRICA", topic:"Seguridad", difficulty:2, text:"¿Qué ataque intenta engañar al usuario para obtener credenciales?", options:["Phishing","Spoofing ARP","Fragmentación IP"], answer:0, explanation:"El phishing engaña al usuario para robar credenciales o información sensible.", reference:"Amenazas" },

  { id:"T04-034", section:"TEÓRICA", topic:"Windows", difficulty:3, text:"¿Qué herramienta de Windows permite gestionar usuarios, grupos y equipos en un dominio?", options:["Active Directory","Administrador de tareas","Explorador de archivos"], answer:0, explanation:"Active Directory permite administrar objetos de dominio como usuarios, grupos y equipos.", reference:"Windows Server" },
  { id:"T04-035", section:"TEÓRICA", topic:"Windows", difficulty:3, text:"¿Qué son las GPO en un entorno Windows?", options:["Directivas de grupo","Tipos de discos","Protocolos de correo"], answer:0, explanation:"Las GPO son directivas de grupo aplicadas a usuarios y equipos.", reference:"Active Directory" },
  { id:"T04-036", section:"TEÓRICA", topic:"Windows", difficulty:3, text:"¿Qué servicio de Windows resuelve nombres de dominio en IP si está configurado como servidor?", options:["DNS Server","DHCP Client","Print Spooler"], answer:0, explanation:"DNS Server permite resolver nombres de dominio en direcciones IP.", reference:"Windows Server" },
  { id:"T04-037", section:"TEÓRICA", topic:"Linux", difficulty:2, text:"¿Qué comando muestra el contenido de un directorio en Linux?", options:["ls","cd","pwd"], answer:0, explanation:"El comando ls lista el contenido de un directorio.", reference:"Linux" },
  { id:"T04-038", section:"TEÓRICA", topic:"Linux", difficulty:2, text:"¿Qué comando cambia permisos de un archivo en Linux?", options:["chmod","chown","grep"], answer:0, explanation:"chmod modifica los permisos de archivos y directorios.", reference:"Linux" },
  { id:"T04-039", section:"TEÓRICA", topic:"Linux", difficulty:2, text:"¿Qué comando cambia el propietario de un archivo en Linux?", options:["chown","chmod","mkdir"], answer:0, explanation:"chown cambia el propietario y/o grupo de un archivo.", reference:"Linux" },

  { id:"T04-040", section:"TEÓRICA", topic:"Hardware", difficulty:2, text:"¿Qué tecnología permite conectar SSD de alto rendimiento directamente por PCI Express?", options:["NVMe","SATA","IDE"], answer:0, explanation:"NVMe permite aprovechar PCI Express para SSD de alto rendimiento.", reference:"Almacenamiento" },
  { id:"T04-041", section:"TEÓRICA", topic:"Hardware", difficulty:2, text:"¿Qué tipo de unidad no tiene partes mecánicas móviles?", options:["SSD","HDD","DVD"], answer:0, explanation:"Los SSD usan memoria flash y no tienen partes mecánicas móviles.", reference:"Almacenamiento" },
  { id:"T04-042", section:"TEÓRICA", topic:"Hardware", difficulty:2, text:"¿Qué componente ejecuta las instrucciones principales de un ordenador?", options:["CPU","RAM","Fuente de alimentación"], answer:0, explanation:"La CPU ejecuta instrucciones y coordina las operaciones principales del sistema.", reference:"CPU" },
  { id:"T04-043", section:"TEÓRICA", topic:"Hardware", difficulty:2, text:"¿Qué memoria pierde su contenido al apagar el equipo?", options:["RAM","ROM","SSD"], answer:0, explanation:"La RAM es memoria volátil y pierde su contenido al apagar el equipo.", reference:"Memoria" },
  { id:"T04-044", section:"TEÓRICA", topic:"Hardware", difficulty:2, text:"¿Qué elemento permite la comunicación entre componentes internos del ordenador?", options:["Bus","Monitor","Teclado"], answer:0, explanation:"Los buses permiten la comunicación entre componentes internos.", reference:"Placa base" },
  { id:"T04-045", section:"TEÓRICA", topic:"Hardware", difficulty:2, text:"¿Qué firmware moderno sustituye a la BIOS tradicional?", options:["UEFI","NTFS","MBR"], answer:0, explanation:"UEFI es el firmware moderno que sustituye a la BIOS clásica.", reference:"Arranque" },
  { id:"T04-046", section:"TEÓRICA", topic:"Hardware", difficulty:3, text:"¿Qué tabla de particiones se asocia normalmente a UEFI?", options:["GPT","FAT32","EXT4"], answer:0, explanation:"UEFI se asocia normalmente con discos particionados en GPT.", reference:"Arranque" },

  { id:"T04-047", section:"TEÓRICA", topic:"SQL", difficulty:2, text:"¿Qué instrucción SQL se usa para consultar datos?", options:["SELECT","UPDATE","DELETE"], answer:0, explanation:"SELECT se utiliza para consultar datos de una base de datos.", reference:"SQL" },
  { id:"T04-048", section:"TEÓRICA", topic:"SQL", difficulty:2, text:"¿Qué instrucción SQL se usa para modificar datos existentes?", options:["UPDATE","SELECT","CREATE"], answer:0, explanation:"UPDATE modifica registros existentes en una tabla.", reference:"SQL" },
  { id:"T04-049", section:"TEÓRICA", topic:"SQL", difficulty:2, text:"¿Qué cláusula SQL filtra registros?", options:["WHERE","ORDER BY","GROUP BY"], answer:0, explanation:"WHERE filtra los registros que cumplen una condición.", reference:"SQL" },
  { id:"T04-050", section:"TEÓRICA", topic:"SQL", difficulty:2, text:"¿Qué clave identifica de forma única un registro en una tabla?", options:["Clave primaria","Clave externa","Índice secundario"], answer:0, explanation:"La clave primaria identifica de forma única cada registro de una tabla.", reference:"Bases de datos" }
];