const questions = [
{
"id": 1,
"section": "Inglés escrito general",
"topic": "Verb to be",
"difficulty": "A2",
"text": "Choose the correct option: I ___ from Spain.",
"options": ["am", "is", "are"],
"answer": 0,
"explanation": "Con el sujeto 'I' se usa 'am'.",
"reference": "Inglés escrito general - A2 - Verbo to be"
},
{
"id": 2,
"section": "Inglés escrito general",
"topic": "Present simple",
"difficulty": "A2",
"text": "Choose the correct option: She ___ coffee every morning.",
"options": ["drinks", "drink", "drinking"],
"answer": 0,
"explanation": "En presente simple, con 'she/he/it' el verbo lleva -s: 'drinks'.",
"reference": "Inglés escrito general - A2 - Present simple"
},
{
"id": 3,
"section": "Inglés escrito general",
"topic": "Past simple of be",
"difficulty": "A2",
"text": "Choose the correct option: They ___ at home yesterday.",
"options": ["were", "was", "are"],
"answer": 0,
"explanation": "Con 'they' en pasado del verbo 'to be' se usa 'were'.",
"reference": "Inglés escrito general - A2 - Past simple"
},
{
"id": 4,
"section": "Inglés escrito general",
"topic": "There is / There are",
"difficulty": "A2",
"text": "Choose the correct option: There ___ many people at the airport.",
"options": ["are", "is", "be"],
"answer": 0,
"explanation": "Con un sustantivo plural ('many people') se usa 'There are'.",
"reference": "Inglés escrito general - A2 - There is / There are"
},
{
"id": 5,
"section": "Inglés escrito general",
"topic": "Since and for",
"difficulty": "B1",
"text": "Choose the correct option: I have lived here ___ 2020.",
"options": ["since", "for", "during"],
"answer": 0,
"explanation": "'Since' se usa con un punto concreto en el tiempo: since 2020.",
"reference": "Inglés escrito general - B1 - Present perfect"
},
{
"id": 6,
"section": "Inglés escrito general",
"topic": "Indirect questions",
"difficulty": "B1",
"text": "Choose the correct option: Can you tell me where ___?",
"options": ["the station is", "is the station", "does the station"],
"answer": 0,
"explanation": "En preguntas indirectas se mantiene el orden afirmativo: 'where the station is'.",
"reference": "Inglés escrito general - B1 - Indirect questions"
},
{
"id": 7,
"section": "Inglés escrito general",
"topic": "Prepositions",
"difficulty": "B1",
"text": "Choose the correct option: He is interested ___ learning English.",
"options": ["in", "on", "for"],
"answer": 0,
"explanation": "La expresión correcta es 'interested in'.",
"reference": "Inglés escrito general - B1 - Prepositions after adjectives"
},
{
"id": 8,
"section": "Inglés escrito general",
"topic": "Comparatives",
"difficulty": "A2",
"text": "Choose the correct option: This book is ___ than the one I read last week.",
"options": ["more interesting", "interestinger", "most interesting"],
"answer": 0,
"explanation": "Con adjetivos largos se forma el comparativo con 'more + adjective'.",
"reference": "Inglés escrito general - A2 - Comparatives"
},
{
"id": 9,
"section": "Inglés escrito general",
"topic": "Superlatives",
"difficulty": "A2",
"text": "Choose the correct option: It was the ___ day of the year.",
"options": ["hottest", "hotter", "most hot"],
"answer": 0,
"explanation": "El superlativo de 'hot' es 'the hottest'.",
"reference": "Inglés escrito general - A2 - Superlatives"
},
{
"id": 10,
"section": "Inglés escrito general",
"topic": "Countable and uncountable nouns",
"difficulty": "A2",
"text": "Choose the correct option: How ___ water do you drink every day?",
"options": ["much", "many", "few"],
"answer": 0,
"explanation": "'Water' es incontable, por eso se usa 'much'.",
"reference": "Inglés escrito general - A2 - Much / many"
},
{
"id": 11,
"section": "Inglés escrito general",
"topic": "Future forms",
"difficulty": "B1",
"text": "Choose the correct option: Look at those clouds! It ___ rain.",
"options": ["is going to", "will", "rains"],
"answer": 0,
"explanation": "'Be going to' se usa para predicciones basadas en evidencias visibles.",
"reference": "Inglés escrito general - B1 - Future with going to"
},
{
"id": 12,
"section": "Inglés escrito general",
"topic": "Modal verbs",
"difficulty": "A2",
"text": "Choose the correct option: You ___ smoke in this building. It is forbidden.",
"options": ["mustn't", "don't have to", "should"],
"answer": 0,
"explanation": "'Mustn't' expresa prohibición. 'Don't have to' significa que no es necesario.",
"reference": "Inglés escrito general - A2/B1 - Modal verbs"
},
{
"id": 13,
"section": "Inglés escrito general",
"topic": "Present perfect",
"difficulty": "B1",
"text": "Choose the correct option: Have you ever ___ to London?",
"options": ["been", "went", "go"],
"answer": 0,
"explanation": "Con 'Have you ever...' se usa el participio pasado: 'been'.",
"reference": "Inglés escrito general - B1 - Present perfect"
},
{
"id": 14,
"section": "Inglés escrito general",
"topic": "Past simple vs present perfect",
"difficulty": "B1",
"text": "Choose the correct option: I ___ him yesterday.",
"options": ["saw", "have seen", "see"],
"answer": 0,
"explanation": "Con una referencia temporal terminada ('yesterday') se usa past simple.",
"reference": "Inglés escrito general - B1 - Past simple vs present perfect"
},
{
"id": 15,
"section": "Inglés escrito general",
"topic": "Past continuous",
"difficulty": "B1",
"text": "Choose the correct option: I was cooking when the phone ___.",
"options": ["rang", "was ringing", "rings"],
"answer": 0,
"explanation": "La acción breve que interrumpe va en past simple: 'rang'.",
"reference": "Inglés escrito general - B1 - Past continuous and past simple"
},
{
"id": 16,
"section": "Inglés escrito general",
"topic": "Articles",
"difficulty": "A2",
"text": "Choose the correct option: She is ___ engineer.",
"options": ["an", "a", "the"],
"answer": 0,
"explanation": "Se usa 'an' antes de sonido vocálico: 'an engineer'.",
"reference": "Inglés escrito general - A2 - Articles"
},
{
"id": 17,
"section": "Inglés escrito general",
"topic": "Prepositions of time",
"difficulty": "A2",
"text": "Choose the correct option: The meeting starts ___ Monday morning.",
"options": ["on", "in", "at"],
"answer": 0,
"explanation": "Con días de la semana se usa 'on': on Monday morning.",
"reference": "Inglés escrito general - A2 - Prepositions of time"
},
{
"id": 18,
"section": "Inglés escrito general",
"topic": "Prepositions of time",
"difficulty": "A2",
"text": "Choose the correct option: The train leaves ___ 7:30.",
"options": ["at", "on", "in"],
"answer": 0,
"explanation": "Con horas concretas se usa 'at'.",
"reference": "Inglés escrito general - A2 - Prepositions of time"
},
{
"id": 19,
"section": "Inglés escrito general",
"topic": "Vocabulary",
"difficulty": "A2",
"text": "Choose the option with the closest meaning to 'quick'.",
"options": ["fast", "late", "quiet"],
"answer": 0,
"explanation": "'Quick' significa rápido; su sinónimo más cercano es 'fast'.",
"reference": "Inglés escrito general - A2 - Vocabulary"
},
{
"id": 20,
"section": "Inglés escrito general",
"topic": "Vocabulary",
"difficulty": "A2",
"text": "Choose the opposite of 'expensive'.",
"options": ["cheap", "large", "modern"],
"answer": 0,
"explanation": "El opuesto de 'expensive' es 'cheap'.",
"reference": "Inglés escrito general - A2 - Vocabulary"
},
{
"id": 21,
"section": "Inglés escrito general",
"topic": "Conditionals",
"difficulty": "B1",
"text": "Choose the correct option: If it rains tomorrow, we ___ at home.",
"options": ["will stay", "stayed", "would stay"],
"answer": 0,
"explanation": "En el primer condicional se usa 'If + present simple' y 'will + verb'.",
"reference": "Inglés escrito general - B1 - First conditional"
},
{
"id": 22,
"section": "Inglés escrito general",
"topic": "Conditionals",
"difficulty": "B2",
"text": "Choose the correct option: If I had more time, I ___ another language.",
"options": ["would learn", "will learn", "learned"],
"answer": 0,
"explanation": "En el segundo condicional se usa 'If + past simple' y 'would + verb'.",
"reference": "Inglés escrito general - B2 - Second conditional"
},
{
"id": 23,
"section": "Inglés escrito general",
"topic": "Passive voice",
"difficulty": "B1",
"text": "Choose the correct option: The report ___ by the manager yesterday.",
"options": ["was written", "wrote", "is writing"],
"answer": 0,
"explanation": "La voz pasiva en pasado se forma con 'was/were + past participle'.",
"reference": "Inglés escrito general - B1 - Passive voice"
},
{
"id": 24,
"section": "Inglés escrito general",
"topic": "Reported speech",
"difficulty": "B2",
"text": "Choose the correct option: He said that he ___ tired.",
"options": ["was", "is", "will be"],
"answer": 0,
"explanation": "En estilo indirecto, 'I am tired' pasa normalmente a 'he was tired'.",
"reference": "Inglés escrito general - B2 - Reported speech"
},
{
"id": 25,
"section": "Inglés escrito general",
"topic": "Relative clauses",
"difficulty": "B1",
"text": "Choose the correct option: The woman ___ lives next door is a doctor.",
"options": ["who", "which", "where"],
"answer": 0,
"explanation": "Para personas se usa 'who' en oraciones de relativo.",
"reference": "Inglés escrito general - B1 - Relative clauses"
},
{
"id": 26,
"section": "Inglés escrito general",
"topic": "Relative clauses",
"difficulty": "B1",
"text": "Choose the correct option: This is the hotel ___ we stayed last summer.",
"options": ["where", "who", "which"],
"answer": 0,
"explanation": "Para lugares se usa 'where'.",
"reference": "Inglés escrito general - B1 - Relative clauses"
},
{
"id": 27,
"section": "Inglés escrito general",
"topic": "Gerund and infinitive",
"difficulty": "B1",
"text": "Choose the correct option: I enjoy ___ music while I work.",
"options": ["listening to", "to listen", "listen"],
"answer": 0,
"explanation": "Después de 'enjoy' se usa gerundio: 'enjoy listening to'.",
"reference": "Inglés escrito general - B1 - Gerund"
},
{
"id": 28,
"section": "Inglés escrito general",
"topic": "Gerund and infinitive",
"difficulty": "B1",
"text": "Choose the correct option: She decided ___ a new job.",
"options": ["to look for", "looking for", "look for"],
"answer": 0,
"explanation": "Después de 'decide' se usa infinitivo con 'to'.",
"reference": "Inglés escrito general - B1 - Infinitive"
},
{
"id": 29,
"section": "Inglés escrito general",
"topic": "Phrasal verbs",
"difficulty": "B1",
"text": "Choose the correct option: Please ___ the lights before you leave.",
"options": ["turn off", "turn on", "turn up"],
"answer": 0,
"explanation": "'Turn off' significa apagar.",
"reference": "Inglés escrito general - B1 - Phrasal verbs"
},
{
"id": 30,
"section": "Inglés escrito general",
"topic": "Phrasal verbs",
"difficulty": "B2",
"text": "Choose the correct option: I need to ___ this form before the interview.",
"options": ["fill in", "give up", "look after"],
"answer": 0,
"explanation": "'Fill in a form' significa rellenar un formulario.",
"reference": "Inglés escrito general - B2 - Phrasal verbs"
},
{
"id": 31,
"section": "Inglés escrito general",
"topic": "Connectors",
"difficulty": "B1",
"text": "Choose the correct option: I was tired, ___ I continued working.",
"options": ["but", "because", "so"],
"answer": 0,
"explanation": "'But' introduce contraste: estaba cansado, pero continuó.",
"reference": "Inglés escrito general - B1 - Connectors"
},
{
"id": 32,
"section": "Inglés escrito general",
"topic": "Connectors",
"difficulty": "B1",
"text": "Choose the correct option: We stayed at home ___ the weather was terrible.",
"options": ["because", "although", "however"],
"answer": 0,
"explanation": "'Because' introduce la causa.",
"reference": "Inglés escrito general - B1 - Connectors"
},
{
"id": 33,
"section": "Inglés escrito general",
"topic": "Connectors",
"difficulty": "B2",
"text": "Choose the correct option: ___ it was raining, they went for a walk.",
"options": ["Although", "Because", "So"],
"answer": 0,
"explanation": "'Although' introduce contraste: aunque llovía, salieron.",
"reference": "Inglés escrito general - B2 - Connectors"
},
{
"id": 34,
"section": "Inglés escrito general",
"topic": "Question tags",
"difficulty": "B1",
"text": "Choose the correct option: You're coming to the meeting, ___?",
"options": ["aren't you", "are you", "don't you"],
"answer": 0,
"explanation": "Con una frase afirmativa con 'are', la question tag va negativa: 'aren't you?'.",
"reference": "Inglés escrito general - B1 - Question tags"
},
{
"id": 35,
"section": "Inglés escrito general",
"topic": "Quantifiers",
"difficulty": "B1",
"text": "Choose the correct option: There are only ___ seats left.",
"options": ["a few", "a little", "much"],
"answer": 0,
"explanation": "'Seats' es contable plural, por eso se usa 'a few'.",
"reference": "Inglés escrito general - B1 - Quantifiers"
},
{
"id": 36,
"section": "Inglés escrito general",
"topic": "Quantifiers",
"difficulty": "B1",
"text": "Choose the correct option: We have ___ time before the exam, so let's review quickly.",
"options": ["little", "few", "many"],
"answer": 0,
"explanation": "'Time' es incontable y 'little' indica poca cantidad.",
"reference": "Inglés escrito general - B1 - Quantifiers"
},
{
"id": 37,
"section": "Inglés escrito general",
"topic": "Word order",
"difficulty": "A2",
"text": "Choose the correct sentence.",
"options": ["I usually have breakfast at seven.", "I have usually breakfast at seven.", "Usually I have at seven breakfast."],
"answer": 0,
"explanation": "Los adverbios de frecuencia suelen ir antes del verbo principal: 'usually have'.",
"reference": "Inglés escrito general - A2 - Word order"
},
{
"id": 38,
"section": "Inglés escrito general",
"topic": "Adjectives and adverbs",
"difficulty": "B1",
"text": "Choose the correct option: He speaks English very ___.",
"options": ["well", "good", "better"],
"answer": 0,
"explanation": "Para describir cómo se realiza una acción se usa el adverbio: 'well'.",
"reference": "Inglés escrito general - B1 - Adverbs"
},
{
"id": 39,
"section": "Inglés escrito general",
"topic": "Common collocations",
"difficulty": "B1",
"text": "Choose the correct option: I need to ___ a decision today.",
"options": ["make", "do", "take"],
"answer": 0,
"explanation": "La colocación correcta es 'make a decision'.",
"reference": "Inglés escrito general - B1 - Collocations"
},
{
"id": 40,
"section": "Inglés escrito general",
"topic": "Common collocations",
"difficulty": "B1",
"text": "Choose the correct option: She ___ an exam last week.",
"options": ["took", "made", "did"],
"answer": 0,
"explanation": "En inglés se dice 'take an exam' para presentarse a un examen.",
"reference": "Inglés escrito general - B1 - Collocations"
},
{
"id": 41,
"section": "Inglés escrito general",
"topic": "Reading comprehension",
"difficulty": "A2",
"text": "Read the text: 'Mark works in an office from Monday to Friday. He usually starts at 9:00 and finishes at 17:00.' What time does Mark usually finish work?",
"options": ["At 17:00", "At 9:00", "On Friday"],
"answer": 0,
"explanation": "El texto dice que normalmente termina a las 17:00.",
"reference": "Inglés escrito general - A2 - Reading comprehension"
},
{
"id": 42,
"section": "Inglés escrito general",
"topic": "Reading comprehension",
"difficulty": "A2",
"text": "Read the text: 'Sarah bought a return ticket because she needed to travel back the same day.' What did Sarah buy?",
"options": ["A return ticket", "A single ticket", "A monthly ticket"],
"answer": 0,
"explanation": "El texto indica literalmente que compró un billete de ida y vuelta.",
"reference": "Inglés escrito general - A2 - Reading comprehension"
},
{
"id": 43,
"section": "Inglés escrito general",
"topic": "Reading comprehension",
"difficulty": "B1",
"text": "Read the text: 'The flight was delayed due to bad weather, but passengers were informed by email.' Why was the flight delayed?",
"options": ["Because of bad weather", "Because passengers arrived late", "Because there was no email"],
"answer": 0,
"explanation": "'Due to bad weather' significa que el retraso fue por mal tiempo.",
"reference": "Inglés escrito general - B1 - Reading comprehension"
},
{
"id": 44,
"section": "Inglés escrito general",
"topic": "Reading comprehension",
"difficulty": "B1",
"text": "Read the text: 'Employees must wear their identification cards while they are inside the building.' What are employees required to wear?",
"options": ["Identification cards", "Uniforms", "Safety glasses"],
"answer": 0,
"explanation": "El texto dice que deben llevar sus tarjetas de identificación.",
"reference": "Inglés escrito general - B1 - Reading comprehension"
},
{
"id": 45,
"section": "Inglés escrito general",
"topic": "Reading comprehension",
"difficulty": "B2",
"text": "Read the text: 'Although the new system is more expensive, it is expected to reduce maintenance costs in the long term.' What is the main advantage of the new system?",
"options": ["It may reduce maintenance costs later", "It is cheaper to buy", "It requires more repairs"],
"answer": 0,
"explanation": "La ventaja indicada es la reducción de costes de mantenimiento a largo plazo.",
"reference": "Inglés escrito general - B2 - Reading comprehension"
},
{
"id": 46,
"section": "Inglés escrito general",
"topic": "Formal language",
"difficulty": "B2",
"text": "Choose the most formal option.",
"options": ["I would like to request further information.", "Tell me more.", "I wanna know more."],
"answer": 0,
"explanation": "La opción con 'I would like to request...' es la más formal.",
"reference": "Inglés escrito general - B2 - Formal language"
},
{
"id": 47,
"section": "Inglés escrito general",
"topic": "Formal language",
"difficulty": "B2",
"text": "Choose the best option for a formal email closing.",
"options": ["Yours sincerely,", "See ya,", "Cheers mate,"],
"answer": 0,
"explanation": "'Yours sincerely' es una fórmula formal de despedida.",
"reference": "Inglés escrito general - B2 - Formal writing"
},
{
"id": 48,
"section": "Inglés escrito general",
"topic": "Error correction",
"difficulty": "B1",
"text": "Choose the correct sentence.",
"options": ["She has never been to Italy.", "She has never went to Italy.", "She never has go to Italy."],
"answer": 0,
"explanation": "Con present perfect se usa 'has + past participle': 'has been'.",
"reference": "Inglés escrito general - B1 - Error correction"
},
{
"id": 49,
"section": "Inglés escrito general",
"topic": "Error correction",
"difficulty": "B2",
"text": "Choose the correct sentence.",
"options": ["Despite the rain, the event continued.", "Despite of the rain, the event continued.", "Although the rain, the event continued."],
"answer": 0,
"explanation": "'Despite' no lleva 'of'. También podría usarse 'Although it rained', pero no 'Although the rain'.",
"reference": "Inglés escrito general - B2 - Contrast connectors"
},
{
"id": 50,
"section": "Inglés escrito general",
"topic": "Advanced grammar",
"difficulty": "C1",
"text": "Choose the correct option: No sooner had the meeting started ___ the alarm went off.",
"options": ["than", "when", "that"],
"answer": 0,
"explanation": "La estructura correcta es 'No sooner had... than...'.",
"reference": "Inglés escrito general - C1 - Inversion"
}
]