const questions = [
  { id:"HW-001", section:"TEÓRICA", topic:"Hardware", difficulty:1, text:"¿Qué componente ejecuta directamente las instrucciones de un programa?", options:["CPU","RAM","Disco duro"], answer:0, explanation:"La CPU ejecuta instrucciones.", reference:"Hardware" },
  { id:"HW-002", section:"TEÓRICA", topic:"Hardware", difficulty:1, text:"¿Qué memoria pierde su contenido al apagar el equipo?", options:["ROM","RAM","SSD"], answer:1, explanation:"La RAM es volátil.", reference:"Hardware" },
  { id:"HW-003", section:"TEÓRICA", topic:"Hardware", difficulty:2, text:"¿Qué bus se utiliza habitualmente para tarjetas gráficas modernas?", options:["PCI Express","IDE","PS/2"], answer:0, explanation:"PCIe es el bus habitual para GPU.", reference:"Hardware" },
  { id:"HW-004", section:"TEÓRICA", topic:"Hardware", difficulty:2, text:"¿Qué componente conecta CPU, memoria, buses y dispositivos internos?", options:["Placa base","Fuente de alimentación","Tarjeta de sonido"], answer:0, explanation:"La placa base interconecta componentes.", reference:"Hardware" },
  { id:"HW-005", section:"TEÓRICA", topic:"Hardware", difficulty:2, text:"¿Qué tecnología de almacenamiento no tiene partes mecánicas móviles?", options:["SSD","HDD","DVD"], answer:0, explanation:"El SSD usa memoria flash.", reference:"Hardware" },

  { id:"SO-001", section:"TEÓRICA", topic:"Sistemas Operativos", difficulty:1, text:"¿Cuál es una función principal del sistema operativo?", options:["Gestionar recursos hardware y software","Sustituir a la BIOS","Aumentar físicamente la RAM"], answer:0, explanation:"El SO gestiona recursos.", reference:"Sistemas Operativos" },
  { id:"SO-002", section:"TEÓRICA", topic:"Sistemas Operativos", difficulty:1, text:"En Windows, ¿qué herramienta permite ver procesos y uso de CPU/RAM?", options:["Administrador de tareas","Paint","Bloc de notas"], answer:0, explanation:"El Administrador de tareas muestra procesos y recursos.", reference:"Windows" },
  { id:"SO-003", section:"TEÓRICA", topic:"Sistemas Operativos", difficulty:2, text:"¿Qué sistema de archivos es habitual en Windows moderno?", options:["NTFS","EXT4","HFS+"], answer:0, explanation:"NTFS es habitual en Windows.", reference:"Windows" },
  { id:"SO-004", section:"TEÓRICA", topic:"Sistemas Operativos", difficulty:1, text:"En Linux, ¿qué comando lista el contenido de un directorio?", options:["ls","cd","pwd"], answer:0, explanation:"ls lista archivos y carpetas.", reference:"Linux" },
  { id:"SO-005", section:"TEÓRICA", topic:"Sistemas Operativos", difficulty:2, text:"¿Qué es un proceso?", options:["Un programa en ejecución","Un archivo comprimido","Un tipo de partición"], answer:0, explanation:"Un proceso es un programa ejecutándose.", reference:"SO" },

  { id:"RED-001", section:"TEÓRICA", topic:"Redes", difficulty:1, text:"¿Qué dispositivo conmuta tramas dentro de una LAN usando direcciones MAC?", options:["Switch","Router","Módem"], answer:0, explanation:"El switch trabaja principalmente en capa 2.", reference:"Redes" },
  { id:"RED-002", section:"TEÓRICA", topic:"Redes", difficulty:1, text:"¿Qué dispositivo encamina paquetes entre redes diferentes?", options:["Router","Hub","Switch no gestionable"], answer:0, explanation:"El router enruta entre redes.", reference:"Redes" },
  { id:"RED-003", section:"TEÓRICA", topic:"Redes", difficulty:2, text:"¿Qué medio es inmune a interferencias electromagnéticas?", options:["Fibra óptica","Par trenzado","Cable coaxial"], answer:0, explanation:"La fibra transmite luz.", reference:"Medios de transmisión" },
  { id:"RED-004", section:"TEÓRICA", topic:"Redes", difficulty:2, text:"¿Qué estándar se asocia con Wi-Fi?", options:["IEEE 802.11","IEEE 802.3","ISO 9660"], answer:0, explanation:"802.11 es Wi-Fi.", reference:"Redes inalámbricas" },
  { id:"RED-005", section:"TEÓRICA", topic:"Redes", difficulty:2, text:"¿Qué técnica separa redes lógicas dentro de un switch?", options:["VLAN","RAID","NAT"], answer:0, explanation:"Las VLAN segmentan redes lógicas.", reference:"Redes locales" },

  { id:"TCP-001", section:"TEÓRICA", topic:"TCP/IP", difficulty:1, text:"¿Qué protocolo asigna automáticamente direcciones IP?", options:["DHCP","DNS","FTP"], answer:0, explanation:"DHCP asigna configuración IP.", reference:"TCP/IP" },
  { id:"TCP-002", section:"TEÓRICA", topic:"TCP/IP", difficulty:1, text:"¿Qué servicio traduce nombres de dominio a direcciones IP?", options:["DNS","SMTP","ARP"], answer:0, explanation:"DNS resuelve nombres.", reference:"TCP/IP" },
  { id:"TCP-003", section:"TEÓRICA", topic:"TCP/IP", difficulty:2, text:"¿Qué protocolo usa normalmente el comando ping?", options:["ICMP","UDP","TCP"], answer:0, explanation:"Ping usa ICMP Echo Request/Reply.", reference:"TCP/IP" },
  { id:"TCP-004", section:"TEÓRICA", topic:"TCP/IP", difficulty:2, text:"¿Qué protocolo resuelve IP a MAC en IPv4?", options:["ARP","DNS","DHCP"], answer:0, explanation:"ARP relaciona IP y MAC.", reference:"TCP/IP" },
  { id:"TCP-005", section:"TEÓRICA", topic:"TCP/IP", difficulty:2, text:"¿Qué puerto usa HTTPS por defecto?", options:["443","80","25"], answer:0, explanation:"HTTPS usa TCP 443.", reference:"Internet" },

  { id:"OSI-001", section:"TEÓRICA", topic:"OSI", difficulty:1, text:"¿En qué capa OSI trabaja IP?", options:["Red","Transporte","Aplicación"], answer:0, explanation:"IP pertenece a capa de Red.", reference:"Modelo OSI" },
  { id:"OSI-002", section:"TEÓRICA", topic:"OSI", difficulty:2, text:"¿En qué capa OSI trabaja TCP?", options:["Transporte","Enlace","Sesión"], answer:0, explanation:"TCP pertenece a Transporte.", reference:"Modelo OSI" },
  { id:"OSI-003", section:"TEÓRICA", topic:"OSI", difficulty:2, text:"¿Qué unidad de datos se asocia a la capa de enlace?", options:["Trama","Segmento","Paquete"], answer:0, explanation:"La capa de enlace usa tramas.", reference:"Modelo OSI" },

  { id:"SEG-001", section:"TEÓRICA", topic:"Seguridad", difficulty:1, text:"¿Qué principio garantiza que solo accedan usuarios autorizados?", options:["Confidencialidad","Disponibilidad","Escalabilidad"], answer:0, explanation:"La confidencialidad limita el acceso.", reference:"Seguridad" },
  { id:"SEG-002", section:"TEÓRICA", topic:"Seguridad", difficulty:1, text:"¿Qué principio garantiza que los datos no sean alterados sin autorización?", options:["Integridad","Disponibilidad","Trazabilidad"], answer:0, explanation:"La integridad protege contra modificaciones indebidas.", reference:"Seguridad" },
  { id:"SEG-003", section:"TEÓRICA", topic:"Seguridad", difficulty:2, text:"¿Qué malware cifra archivos y exige rescate?", options:["Ransomware","Spyware","Adware"], answer:0, explanation:"El ransomware cifra y pide rescate.", reference:"Seguridad" },
  { id:"SEG-004", section:"TEÓRICA", topic:"Seguridad", difficulty:2, text:"¿Qué dispositivo filtra tráfico según reglas?", options:["Firewall","Hub","SAI"], answer:0, explanation:"El firewall filtra tráfico.", reference:"Seguridad" },
  { id:"SEG-005", section:"TEÓRICA", topic:"Seguridad", difficulty:3, text:"¿Qué tipo de cifrado usa la misma clave para cifrar y descifrar?", options:["Simétrico","Asimétrico","Hash"], answer:0, explanation:"El cifrado simétrico usa una misma clave.", reference:"Criptografía" },

  { id:"AD-001", section:"TEÓRICA", topic:"Active Directory", difficulty:1, text:"¿Qué servicio centraliza usuarios, equipos y políticas en un dominio Microsoft?", options:["Active Directory","Hyper-V","Docker"], answer:0, explanation:"AD centraliza la gestión del dominio.", reference:"Administración de sistemas" },
  { id:"AD-002", section:"TEÓRICA", topic:"Active Directory", difficulty:2, text:"¿Qué objeto organiza usuarios y equipos para aplicar administración?", options:["Unidad Organizativa","Registro MX","VLAN"], answer:0, explanation:"Las OU organizan objetos en AD.", reference:"AD" },
  { id:"AD-003", section:"TEÓRICA", topic:"Active Directory", difficulty:2, text:"¿Qué permite una GPO?", options:["Aplicar configuraciones a usuarios/equipos","Asignar direcciones MAC","Crear tablas SQL"], answer:0, explanation:"Las GPO aplican políticas.", reference:"AD" },

  { id:"VIR-001", section:"TEÓRICA", topic:"Virtualización", difficulty:1, text:"¿Qué es un hipervisor?", options:["Software que ejecuta máquinas virtuales","Un antivirus","Un protocolo de correo"], answer:0, explanation:"El hipervisor gestiona VMs.", reference:"Virtualización" },
  { id:"VIR-002", section:"TEÓRICA", topic:"Virtualización", difficulty:2, text:"¿Cuál es un hipervisor de Microsoft?", options:["Hyper-V","Docker","Apache"], answer:0, explanation:"Hyper-V es de Microsoft.", reference:"Virtualización" },
  { id:"VIR-003", section:"TEÓRICA", topic:"Virtualización", difficulty:3, text:"¿Qué diferencia básica tiene un contenedor frente a una VM?", options:["Comparte kernel del host","Tiene BIOS física propia","Siempre necesita más RAM"], answer:0, explanation:"Los contenedores comparten kernel.", reference:"Contenedores" },

  { id:"BK-001", section:"TEÓRICA", topic:"Backups", difficulty:1, text:"¿Qué backup copia todo el conjunto seleccionado?", options:["Completo","Incremental","Diferencial"], answer:0, explanation:"El completo copia todo.", reference:"Backups" },
  { id:"BK-002", section:"TEÓRICA", topic:"Backups", difficulty:2, text:"¿Qué backup copia cambios desde el último backup completo?", options:["Diferencial","Incremental","Imagen ISO"], answer:0, explanation:"El diferencial parte del último completo.", reference:"Backups" },

  { id:"SQL-001", section:"TEÓRICA", topic:"Bases de Datos", difficulty:1, text:"¿Qué sentencia SQL consulta datos?", options:["SELECT","INSERT","DELETE"], answer:0, explanation:"SELECT consulta datos.", reference:"SQL" },
  { id:"SQL-002", section:"TEÓRICA", topic:"Bases de Datos", difficulty:1, text:"¿Qué sentencia SQL añade registros?", options:["INSERT","SELECT","DROP"], answer:0, explanation:"INSERT añade filas.", reference:"SQL" },
  { id:"SQL-003", section:"TEÓRICA", topic:"Bases de Datos", difficulty:2, text:"¿Qué cláusula filtra registros?", options:["WHERE","ORDER BY","GROUP BY"], answer:0, explanation:"WHERE filtra resultados.", reference:"SQL" },
  { id:"SQL-004", section:"TEÓRICA", topic:"Bases de Datos", difficulty:2, text:"¿Qué clave identifica de forma única una fila?", options:["Clave primaria","Clave foránea","Índice secundario"], answer:0, explanation:"La clave primaria identifica registros.", reference:"Bases de datos" },

  { id:"PRO-001", section:"TEÓRICA", topic:"Programación", difficulty:1, text:"¿Qué estructura repite instrucciones?", options:["Bucle","Variable","Comentario"], answer:0, explanation:"Los bucles repiten código.", reference:"Programación" },
  { id:"PRO-002", section:"TEÓRICA", topic:"Programación", difficulty:2, text:"¿Qué estructura permite elegir entre caminos alternativos?", options:["Condicional","Array","Registro"], answer:0, explanation:"Los condicionales deciden el flujo.", reference:"Programación" },
  { id:"WEB-001", section:"TEÓRICA", topic:"Web", difficulty:1, text:"¿Qué lenguaje define la estructura de una página web?", options:["HTML","CSS","SQL"], answer:0, explanation:"HTML define estructura.", reference:"Web" },
  { id:"WEB-002", section:"TEÓRICA", topic:"Web", difficulty:1, text:"¿Qué lenguaje define estilos visuales en web?", options:["CSS","HTML","XML"], answer:0, explanation:"CSS define presentación.", reference:"Web" },

  { id:"LEG-001", section:"TEÓRICA", topic:"Legislación", difficulty:2, text:"¿Qué ley española adapta el RGPD y garantiza derechos digitales?", options:["LO 3/2018","LO 1/2004","LO 3/2007"], answer:0, explanation:"La LO 3/2018 regula protección de datos y derechos digitales.", reference:"Anexo B" },
  { id:"LEG-002", section:"TEÓRICA", topic:"Legislación", difficulty:2, text:"¿Qué ley regula la igualdad efectiva de mujeres y hombres?", options:["LO 3/2007","LO 3/2018","LO 1/2004"], answer:0, explanation:"La LO 3/2007 trata la igualdad efectiva.", reference:"Anexo B" },
  { id:"LEG-003", section:"TEÓRICA", topic:"Legislación", difficulty:2, text:"¿Qué ley regula medidas de protección integral contra la violencia de género?", options:["LO 1/2004","LO 3/2007","LO 3/2018"], answer:0, explanation:"La LO 1/2004 regula violencia de género.", reference:"Anexo B" },
  { id:"LEG-004", section:"TEÓRICA", topic:"Legislación", difficulty:3, text:"¿Qué derecho permite solicitar la eliminación de datos personales en ciertos casos?", options:["Derecho de supresión","Derecho de overclocking","Derecho de encapsulación"], answer:0, explanation:"El derecho de supresión permite solicitar eliminación de datos.", reference:"LOPDGDD/RGPD" },
  { id:"LEG-005", section:"TEÓRICA", topic:"Legislación", difficulty:2, text:"¿Qué principio evita discriminación directa o indirecta por razón de sexo?", options:["Igualdad de trato","Neutralidad de red","Confidencialidad"], answer:0, explanation:"La igualdad de trato evita discriminación.", reference:"LO 3/2007" },

  { id:"SUP-001", section:"SUPUESTO", topic:"Redes", difficulty:2, text:"Un PC hace ping a 8.8.8.8 pero no accede a www.aena.es. ¿Qué revisarías primero?", options:["DNS","RAM","Tarjeta gráfica"], answer:0, explanation:"Si hay conectividad por IP pero no por nombre, sospecha DNS.", reference:"Supuesto redes" },
  { id:"SUP-002", section:"SUPUESTO", topic:"Redes", difficulty:2, text:"Un equipo recibe IP 169.254.x.x. ¿Qué indica normalmente?", options:["No obtuvo IP por DHCP","Tiene DNS correcto","Tiene IP pública"], answer:0, explanation:"169.254.x.x suele ser APIPA por fallo DHCP.", reference:"Supuesto redes" },
  { id:"SUP-003", section:"SUPUESTO", topic:"Windows", difficulty:2, text:"Un usuario no puede instalar software por falta de permisos. ¿Qué necesita?", options:["Elevación administrativa","Cambiar monitor","Vaciar papelera"], answer:0, explanation:"Instalar software suele requerir permisos de administrador.", reference:"Supuesto Windows" },
  { id:"SUP-004", section:"SUPUESTO", topic:"AD", difficulty:3, text:"Un equipo unido al dominio no resuelve nombres internos. ¿Qué DNS debe usar preferentemente?", options:["DNS del controlador de dominio","8.8.8.8 como único DNS","Servidor SMTP externo"], answer:0, explanation:"En dominio debe usar DNS interno/AD.", reference:"Supuesto AD" },
  { id:"SUP-005", section:"SUPUESTO", topic:"Seguridad", difficulty:2, text:"Detectas cifrado masivo de archivos compartidos. ¿Primera actuación razonable?", options:["Aislar el equipo afectado de la red","Desactivar backups","Reiniciar todos los servidores"], answer:0, explanation:"Primero se contiene el incidente aislando el equipo.", reference:"Supuesto seguridad" },
  { id:"SUP-006", section:"SUPUESTO", topic:"Impresión", difficulty:2, text:"Una impresora responde a ping pero no imprime desde un equipo. ¿Qué revisarías?", options:["Cola, driver y puerto TCP/IP","Resolución de pantalla","BIOS"], answer:0, explanation:"Si hay red, revisar configuración de impresión.", reference:"Supuesto soporte" },
  { id:"SUP-007", section:"SUPUESTO", topic:"VPN", difficulty:3, text:"Un teletrabajador navega por Internet pero no accede a recursos internos. ¿Qué revisarías primero?", options:["Estado y rutas de la VPN","Fuente de alimentación","Tipo de teclado"], answer:0, explanation:"El fallo apunta a VPN/rutas.", reference:"Supuesto VPN" },
  { id:"SUP-008", section:"SUPUESTO", topic:"HTTP", difficulty:2, text:"Un servidor web devuelve código 500. ¿Qué indica?", options:["Error interno del servidor","Página encontrada","Redirección permanente"], answer:0, explanation:"HTTP 500 indica error interno.", reference:"Supuesto web" },
  { id:"SUP-009", section:"SUPUESTO", topic:"OSI", difficulty:2, text:"Un cable de red está dañado. ¿En qué capa OSI se ubica principalmente el problema?", options:["Física","Aplicación","Sesión"], answer:0, explanation:"El cable pertenece a capa física.", reference:"Modelo OSI" },
  { id:"SUP-010", section:"SUPUESTO", topic:"SQL", difficulty:2, text:"Quieres obtener solo clientes de Madrid en una consulta SQL. ¿Qué cláusula usarías?", options:["WHERE","ORDER BY","CREATE"], answer:0, explanation:"WHERE filtra registros.", reference:"SQL" },

  { id:"ING-001", section:"INGLÉS TÉCNICO", topic:"Traducción", difficulty:1, text:"“The server is unavailable due to scheduled maintenance” significa:", options:["El servidor no está disponible por mantenimiento programado","El servidor está disponible sin mantenimiento","El usuario cambió la contraseña"], answer:0, explanation:"Unavailable = no disponible; scheduled maintenance = mantenimiento programado.", reference:"Inglés técnico" },
  { id:"ING-002", section:"INGLÉS TÉCNICO", topic:"Traducción", difficulty:1, text:"“Backup failed because the destination disk is full” significa:", options:["La copia falló porque el disco destino está lleno","La copia terminó correctamente","El teclado no responde"], answer:0, explanation:"Failed = falló; destination disk = disco destino.", reference:"Inglés técnico" },
  { id:"ING-003", section:"INGLÉS TÉCNICO", topic:"Traducción", difficulty:1, text:"“Authentication required” significa:", options:["Autenticación requerida","Autorización concedida","Aplicación instalada"], answer:0, explanation:"Authentication required = autenticación requerida.", reference:"Inglés técnico" },
  { id:"ING-004", section:"INGLÉS TÉCNICO", topic:"Traducción", difficulty:2, text:"“The device driver must be updated” significa:", options:["El controlador del dispositivo debe actualizarse","El dispositivo debe apagarse","El usuario debe cambiar de oficina"], answer:0, explanation:"Driver = controlador.", reference:"Inglés técnico" },
  { id:"ING-005", section:"INGLÉS TÉCNICO", topic:"Traducción", difficulty:2, text:"“Network latency is high” significa:", options:["La latencia de red es alta","La red está cifrada","La impresora está sin papel"], answer:0, explanation:"Latency = latencia.", reference:"Inglés técnico" },
  { id:"ING-006", section:"INGLÉS TÉCNICO", topic:"Traducción", difficulty:2, text:"“Read-only permission” significa:", options:["Permiso de solo lectura","Permiso de administrador total","Permiso de borrado"], answer:0, explanation:"Read-only = solo lectura.", reference:"Inglés técnico" },
  { id:"ING-007", section:"INGLÉS TÉCNICO", topic:"Traducción", difficulty:2, text:"“The user account has been locked” significa:", options:["La cuenta de usuario ha sido bloqueada","La cuenta fue creada","El usuario imprimió"], answer:0, explanation:"Locked = bloqueada.", reference:"Inglés técnico" },
  { id:"ING-008", section:"INGLÉS TÉCNICO", topic:"Traducción", difficulty:2, text:"“Patch deployment” significa:", options:["Despliegue de parches","Copia de pantalla","Cambio de teclado"], answer:0, explanation:"Patch deployment = despliegue de parches.", reference:"Inglés técnico" },
  { id:"ING-009", section:"INGLÉS TÉCNICO", topic:"Traducción", difficulty:2, text:"“Remote desktop connection” significa:", options:["Conexión de escritorio remoto","Conexión de impresora local","Cable de alimentación"], answer:0, explanation:"Remote desktop = escritorio remoto.", reference:"Inglés técnico" },
  { id:"ING-010", section:"INGLÉS TÉCNICO", topic:"Traducción", difficulty:2, text:"“The certificate has expired” significa:", options:["El certificado ha caducado","El certificado se ha impreso","El certificado es una copia"], answer:0, explanation:"Expired = caducado.", reference:"Inglés técnico" }
];