const questions = [
  {
    id: 1,
    section: "Teórica",
    topic: "Modelo OSI",
    difficulty: "Media",
    text: "¿Cuál es la PDU correspondiente a la capa de red del modelo OSI?",
    options: ["Paquete", "Trama", "Segmento"],
    answer: 0,
    explanation: "En la capa de red la PDU se denomina paquete.",
    reference: "Modelo OSI"
  },
  {
    id: 2,
    section: "Teórica",
    topic: "Modelo OSI",
    difficulty: "Media",
    text: "¿En qué capa del modelo OSI trabaja principalmente un switch tradicional?",
    options: ["Capa 2", "Capa 3", "Capa 4"],
    answer: 0,
    explanation: "Un switch tradicional trabaja en la capa de enlace de datos usando direcciones MAC.",
    reference: "Modelo OSI - Redes locales"
  },
  {
    id: 3,
    section: "Teórica",
    topic: "Redes",
    difficulty: "Media",
    text: "¿Qué dirección identifica físicamente una tarjeta de red Ethernet?",
    options: ["Dirección IP", "Dirección MAC", "Máscara de red"],
    answer: 1,
    explanation: "La dirección MAC identifica físicamente una interfaz de red.",
    reference: "Redes locales"
  },
  {
    id: 4,
    section: "Teórica",
    topic: "TCP/IP",
    difficulty: "Media",
    text: "¿Qué protocolo se utiliza normalmente para resolver nombres de dominio en direcciones IP?",
    options: ["DHCP", "DNS", "ARP"],
    answer: 1,
    explanation: "DNS traduce nombres como ejemplo.com a direcciones IP.",
    reference: "Servicios de red"
  },
  {
    id: 5,
    section: "Teórica",
    topic: "TCP/IP",
    difficulty: "Media",
    text: "¿Qué protocolo asigna automáticamente direcciones IP a los equipos de una red?",
    options: ["DHCP", "DNS", "ICMP"],
    answer: 0,
    explanation: "DHCP permite asignar automáticamente IP, máscara, puerta de enlace y DNS.",
    reference: "Servicios de red"
  },
  {
    id: 6,
    section: "Teórica",
    topic: "TCP/IP",
    difficulty: "Media",
    text: "¿Qué protocolo se utiliza para conocer la dirección MAC asociada a una dirección IP en una red local?",
    options: ["ARP", "SMTP", "FTP"],
    answer: 0,
    explanation: "ARP resuelve direcciones IP en direcciones MAC dentro de una LAN.",
    reference: "Protocolos TCP/IP"
  },
  {
    id: 7,
    section: "Teórica",
    topic: "Puertos",
    difficulty: "Media",
    text: "¿Cuál es el puerto habitual de HTTPS?",
    options: ["80", "443", "25"],
    answer: 1,
    explanation: "HTTPS utiliza normalmente el puerto TCP 443.",
    reference: "Internet - HTTPS"
  },
  {
    id: 8,
    section: "Teórica",
    topic: "Puertos",
    difficulty: "Media",
    text: "¿Cuál es el puerto habitual de HTTP?",
    options: ["80", "110", "143"],
    answer: 0,
    explanation: "HTTP utiliza normalmente el puerto TCP 80.",
    reference: "Internet - HTTP"
  },
  {
    id: 9,
    section: "Teórica",
    topic: "Puertos",
    difficulty: "Media",
    text: "¿Qué protocolo se usa habitualmente para el envío de correo electrónico entre servidores?",
    options: ["POP3", "SMTP", "IMAP"],
    answer: 1,
    explanation: "SMTP se utiliza para enviar correo electrónico.",
    reference: "Correo electrónico"
  },
  {
    id: 10,
    section: "Teórica",
    topic: "Correo electrónico",
    difficulty: "Media",
    text: "¿Qué protocolo permite consultar el correo manteniéndolo normalmente en el servidor?",
    options: ["IMAP", "SMTP", "SNMP"],
    answer: 0,
    explanation: "IMAP permite acceder al correo manteniendo los mensajes en el servidor.",
    reference: "Correo electrónico"
  },
  {
    id: 11,
    section: "Teórica",
    topic: "Redes",
    difficulty: "Media",
    text: "¿Qué dispositivo interconecta redes diferentes y decide rutas usando direcciones IP?",
    options: ["Switch", "Router", "Hub"],
    answer: 1,
    explanation: "El router trabaja con direcciones IP y permite comunicar redes distintas.",
    reference: "Dispositivos de interconexión"
  },
  {
    id: 12,
    section: "Teórica",
    topic: "Redes",
    difficulty: "Media",
    text: "¿Qué dispositivo repite señales a nivel físico sin analizar direcciones MAC?",
    options: ["Hub", "Switch", "Router"],
    answer: 0,
    explanation: "El hub opera a nivel físico y repite la señal a todos los puertos.",
    reference: "Redes locales"
  },
  {
    id: 13,
    section: "Teórica",
    topic: "VLAN",
    difficulty: "Media",
    text: "¿Qué permite principalmente una VLAN?",
    options: ["Segmentar lógicamente una red", "Aumentar la velocidad del procesador", "Cifrar automáticamente todo el tráfico"],
    answer: 0,
    explanation: "Una VLAN permite separar una red física en varias redes lógicas.",
    reference: "Administración de redes locales"
  },
  {
    id: 14,
    section: "Teórica",
    topic: "NAT",
    difficulty: "Media",
    text: "¿Qué permite NAT en una red privada?",
    options: ["Compartir una IP pública entre varios equipos privados", "Crear copias de seguridad", "Asignar nombres DNS"],
    answer: 0,
    explanation: "NAT permite que varios equipos internos salgan a Internet usando una IP pública.",
    reference: "TCP/IP - Internet"
  },
  {
    id: 15,
    section: "Teórica",
    topic: "IPv4",
    difficulty: "Media",
    text: "¿Qué máscara corresponde a una red /24?",
    options: ["255.255.255.0", "255.255.0.0", "255.0.0.0"],
    answer: 0,
    explanation: "Una red /24 equivale a la máscara 255.255.255.0.",
    reference: "Direccionamiento IPv4"
  },
  {
    id: 16,
    section: "Teórica",
    topic: "IPv4",
    difficulty: "Media",
    text: "¿Cuál de las siguientes direcciones pertenece a un rango privado IPv4?",
    options: ["192.168.1.10", "8.8.8.8", "1.1.1.1"],
    answer: 0,
    explanation: "192.168.0.0/16 es un rango privado IPv4.",
    reference: "Direccionamiento IPv4"
  },
  {
    id: 17,
    section: "Teórica",
    topic: "TCP/UDP",
    difficulty: "Media",
    text: "¿Qué protocolo de transporte es orientado a conexión?",
    options: ["TCP", "UDP", "ICMP"],
    answer: 0,
    explanation: "TCP establece conexión y garantiza entrega ordenada.",
    reference: "Protocolos TCP/IP"
  },
  {
    id: 18,
    section: "Teórica",
    topic: "TCP/UDP",
    difficulty: "Media",
    text: "¿Qué protocolo suele usarse cuando prima la velocidad sobre la fiabilidad?",
    options: ["UDP", "TCP", "SSH"],
    answer: 0,
    explanation: "UDP no establece conexión y tiene menor sobrecarga.",
    reference: "Protocolos TCP/IP"
  },
  {
    id: 19,
    section: "Teórica",
    topic: "Modelo OSI",
    difficulty: "Alta",
    text: "¿En qué capa del modelo OSI se sitúa TCP?",
    options: ["Transporte", "Red", "Aplicación"],
    answer: 0,
    explanation: "TCP pertenece a la capa de transporte.",
    reference: "Modelo OSI"
  },
  {
    id: 20,
    section: "Teórica",
    topic: "Modelo OSI",
    difficulty: "Alta",
    text: "¿En qué capa del modelo OSI se sitúa IP?",
    options: ["Red", "Transporte", "Sesión"],
    answer: 0,
    explanation: "IP pertenece a la capa de red.",
    reference: "Modelo OSI"
  },
  {
    id: 21,
    section: "Teórica",
    topic: "Modelo OSI",
    difficulty: "Media",
    text: "¿Cuál es la PDU de la capa de enlace de datos?",
    options: ["Trama", "Paquete", "Bit"],
    answer: 0,
    explanation: "En la capa de enlace de datos la PDU se denomina trama.",
    reference: "Modelo OSI"
  },
  {
    id: 22,
    section: "Teórica",
    topic: "Modelo OSI",
    difficulty: "Media",
    text: "¿Cuál es la PDU de la capa física?",
    options: ["Bits", "Tramas", "Segmentos"],
    answer: 0,
    explanation: "La capa física transmite bits por el medio.",
    reference: "Modelo OSI"
  },
  {
    id: 23,
    section: "Teórica",
    topic: "Seguridad",
    difficulty: "Media",
    text: "¿Qué característica de la seguridad garantiza que la información no sea modificada sin autorización?",
    options: ["Integridad", "Disponibilidad", "Confidencialidad"],
    answer: 0,
    explanation: "La integridad asegura que los datos no se alteren indebidamente.",
    reference: "Seguridad de la información"
  },
  {
    id: 24,
    section: "Teórica",
    topic: "Seguridad",
    difficulty: "Media",
    text: "¿Qué característica protege la información frente a accesos no autorizados?",
    options: ["Confidencialidad", "Tolerancia a fallos", "Redundancia"],
    answer: 0,
    explanation: "La confidencialidad evita accesos no autorizados a la información.",
    reference: "Seguridad de la información"
  },
  {
    id: 25,
    section: "Teórica",
    topic: "Seguridad",
    difficulty: "Media",
    text: "¿Qué técnica permite transformar información para que no sea legible sin una clave?",
    options: ["Cifrado", "Fragmentación", "Compresión"],
    answer: 0,
    explanation: "El cifrado protege la información transformándola mediante algoritmos y claves.",
    reference: "Criptografía"
  },
  {
    id: 26,
    section: "Teórica",
    topic: "Seguridad",
    difficulty: "Media",
    text: "¿Qué elemento se usa habitualmente para filtrar tráfico entre redes según reglas?",
    options: ["Firewall", "Switch no gestionable", "Monitor"],
    answer: 0,
    explanation: "Un firewall controla el tráfico permitido o bloqueado según reglas.",
    reference: "Seguridad perimetral"
  },
  {
    id: 27,
    section: "Teórica",
    topic: "VPN",
    difficulty: "Media",
    text: "¿Para qué se utiliza principalmente una VPN?",
    options: ["Crear una conexión segura a través de una red pública", "Aumentar la memoria RAM", "Formatear discos automáticamente"],
    answer: 0,
    explanation: "Una VPN permite comunicaciones seguras mediante túneles cifrados.",
    reference: "Acceso remoto seguro"
  },
  {
    id: 28,
    section: "Teórica",
    topic: "Active Directory",
    difficulty: "Media",
    text: "¿Qué servicio de Microsoft se usa para gestionar usuarios, equipos y políticas en un dominio?",
    options: ["Active Directory", "IIS", "Hyper-V"],
    answer: 0,
    explanation: "Active Directory centraliza la gestión de identidades, equipos y políticas.",
    reference: "Administración de sistemas"
  },
  {
    id: 29,
    section: "Teórica",
    topic: "Active Directory",
    difficulty: "Media",
    text: "¿Qué son las GPO en un entorno Windows Server?",
    options: ["Directivas de grupo", "Discos virtuales", "Protocolos de correo"],
    answer: 0,
    explanation: "Las GPO permiten aplicar configuraciones y restricciones a usuarios y equipos.",
    reference: "Administración Windows"
  },
  {
    id: 30,
    section: "Teórica",
    topic: "Sistemas Operativos",
    difficulty: "Media",
    text: "¿Qué componente del sistema operativo gestiona los recursos hardware y permite la comunicación con el software?",
    options: ["Kernel", "Navegador", "Antivirus"],
    answer: 0,
    explanation: "El kernel es el núcleo del sistema operativo.",
    reference: "Sistemas operativos"
  },
  {
    id: 31,
    section: "Teórica",
    topic: "Linux",
    difficulty: "Media",
    text: "¿Qué comando de Linux se utiliza habitualmente para listar archivos y directorios?",
    options: ["ls", "cd", "rm"],
    answer: 0,
    explanation: "El comando ls lista el contenido de un directorio.",
    reference: "Sistemas Unix/Linux"
  },
  {
    id: 32,
    section: "Teórica",
    topic: "Linux",
    difficulty: "Media",
    text: "¿Qué permiso representa la letra x en Linux?",
    options: ["Ejecución", "Escritura", "Lectura"],
    answer: 0,
    explanation: "x indica permiso de ejecución.",
    reference: "Permisos Linux"
  },
  {
    id: 33,
    section: "Teórica",
    topic: "Hardware",
    difficulty: "Media",
    text: "¿Qué tecnología permite conectar unidades SSD de alto rendimiento directamente por PCI Express?",
    options: ["NVMe", "SATA", "IDE"],
    answer: 0,
    explanation: "NVMe aprovecha PCI Express para ofrecer alto rendimiento en SSD.",
    reference: "Fundamentos de hardware"
  },
  {
    id: 34,
    section: "Teórica",
    topic: "Hardware",
    difficulty: "Media",
    text: "¿Qué memoria es volátil y se pierde al apagar el equipo?",
    options: ["RAM", "ROM", "SSD"],
    answer: 0,
    explanation: "La RAM es memoria volátil.",
    reference: "Memoria principal"
  },
  {
    id: 35,
    section: "Teórica",
    topic: "Hardware",
    difficulty: "Media",
    text: "¿Qué componente ejecuta las instrucciones principales de un ordenador?",
    options: ["CPU", "Fuente de alimentación", "Tarjeta de red"],
    answer: 0,
    explanation: "La CPU ejecuta instrucciones y coordina operaciones del sistema.",
    reference: "CPU - Microprocesadores"
  },
  {
    id: 36,
    section: "Teórica",
    topic: "Virtualización",
    difficulty: "Media",
    text: "¿Qué es un hipervisor?",
    options: ["Software que permite ejecutar máquinas virtuales", "Un protocolo de correo", "Un tipo de memoria RAM"],
    answer: 0,
    explanation: "El hipervisor permite crear y ejecutar máquinas virtuales sobre hardware físico.",
    reference: "Virtualización"
  },
  {
    id: 37,
    section: "Teórica",
    topic: "Virtualización",
    difficulty: "Media",
    text: "¿Qué es un snapshot en virtualización?",
    options: ["Una captura del estado de una máquina virtual en un momento concreto", "Una copia física de la placa base", "Un protocolo de cifrado"],
    answer: 0,
    explanation: "Un snapshot guarda el estado de una VM para poder volver a ese punto.",
    reference: "Virtualización y backup"
  },
  {
    id: 38,
    section: "Teórica",
    topic: "Backups",
    difficulty: "Media",
    text: "¿Qué copia de seguridad guarda todos los datos seleccionados?",
    options: ["Completa", "Incremental", "Diferencial"],
    answer: 0,
    explanation: "La copia completa incluye todos los datos seleccionados.",
    reference: "Copias de seguridad"
  },
  {
    id: 39,
    section: "Teórica",
    topic: "Backups",
    difficulty: "Alta",
    text: "¿Qué copia guarda únicamente los cambios desde la última copia, sea completa o incremental?",
    options: ["Incremental", "Completa", "Imagen ISO"],
    answer: 0,
    explanation: "La copia incremental guarda cambios desde la última copia realizada.",
    reference: "Copias de seguridad"
  },
  {
    id: 40,
    section: "Teórica",
    topic: "Bases de datos",
    difficulty: "Media",
    text: "¿Qué lenguaje se utiliza habitualmente para consultar bases de datos relacionales?",
    options: ["SQL", "HTML", "CSS"],
    answer: 0,
    explanation: "SQL es el lenguaje estándar de consulta en bases de datos relacionales.",
    reference: "Bases de datos"
  },
  {
    id: 41,
    section: "Teórica",
    topic: "Bases de datos",
    difficulty: "Media",
    text: "¿Qué instrucción SQL se utiliza para obtener datos de una tabla?",
    options: ["SELECT", "INSERT", "DELETE"],
    answer: 0,
    explanation: "SELECT permite consultar registros en una base de datos.",
    reference: "SQL"
  },
  {
    id: 42,
    section: "Teórica",
    topic: "Bases de datos",
    difficulty: "Media",
    text: "¿Qué clave identifica de forma única cada registro de una tabla?",
    options: ["Clave primaria", "Clave externa", "Índice secundario"],
    answer: 0,
    explanation: "La clave primaria identifica de manera única cada fila.",
    reference: "Modelo relacional"
  },
  {
    id: 43,
    section: "Teórica",
    topic: "Bases de datos",
    difficulty: "Media",
    text: "¿Qué tipo de base de datos organiza la información en tablas relacionadas?",
    options: ["Relacional", "Jerárquica únicamente", "Sistema de archivos plano"],
    answer: 0,
    explanation: "Las bases de datos relacionales organizan datos en tablas con relaciones.",
    reference: "Bases de datos relacionales"
  },
  {
    id: 44,
    section: "Teórica",
    topic: "Programación",
    difficulty: "Media",
    text: "¿Qué estructura permite repetir instrucciones mientras se cumple una condición?",
    options: ["Bucle", "Variable", "Comentario"],
    answer: 0,
    explanation: "Un bucle permite ejecutar instrucciones repetidamente.",
    reference: "Lenguajes de programación"
  },
  {
    id: 45,
    section: "Teórica",
    topic: "Programación",
    difficulty: "Media",
    text: "¿Qué estructura permite tomar decisiones en función de una condición?",
    options: ["Condicional", "Array", "Compilador"],
    answer: 0,
    explanation: "Una estructura condicional permite ejecutar caminos distintos según una condición.",
    reference: "Lenguajes de programación"
  },
  {
    id: 46,
    section: "Teórica",
    topic: "Web",
    difficulty: "Media",
    text: "¿Qué lenguaje se utiliza para estructurar el contenido de una página web?",
    options: ["HTML", "CSS", "SQL"],
    answer: 0,
    explanation: "HTML define la estructura y contenido de una página web.",
    reference: "Aplicaciones web"
  },
  {
    id: 47,
    section: "Teórica",
    topic: "Web",
    difficulty: "Media",
    text: "¿Qué lenguaje se utiliza principalmente para definir la presentación visual de una página web?",
    options: ["CSS", "HTML", "SQL"],
    answer: 0,
    explanation: "CSS se utiliza para estilos, diseño y presentación visual.",
    reference: "Desarrollo web"
  },
  {
    id: 48,
    section: "Teórica",
    topic: "Git",
    difficulty: "Media",
    text: "¿Para qué se utiliza Git?",
    options: ["Control de versiones", "Cifrado de discos", "Monitorización de red"],
    answer: 0,
    explanation: "Git permite controlar versiones del código fuente y colaborar en proyectos.",
    reference: "Control de versiones"
  },
  {
    id: 49,
    section: "Teórica",
    topic: "Legislación",
    difficulty: "Media",
    text: "¿Qué norma española regula la protección de datos personales y garantía de derechos digitales?",
    options: ["LOPDGDD 3/2018", "Ley 31/1995", "Ley 39/2015 únicamente"],
    answer: 0,
    explanation: "La Ley Orgánica 3/2018 regula protección de datos personales y derechos digitales.",
    reference: "Anexo B - Protección de datos"
  },
  {
    id: 50,
    section: "Teórica",
    topic: "Legislación",
    difficulty: "Media",
    text: "¿Qué ley regula la igualdad efectiva de mujeres y hombres en España?",
    options: ["Ley Orgánica 3/2007", "Ley Orgánica 1/2004", "Ley Orgánica 3/2018"],
    answer: 0,
    explanation: "La Ley Orgánica 3/2007 regula la igualdad efectiva de mujeres y hombres.",
    reference: "Anexo B - Igualdad"
  }
];