const questions = [
  {
    id: 1,
    section: "Teórica",
    topic: "Modelo OSI",
    difficulty: "Alta",
    text: "¿Cuál es la PDU de la capa de transporte en el modelo OSI?",
    options: ["Trama", "Segmento", "Paquete"],
    answer: 1,
    explanation: "En la capa de transporte la PDU se denomina segmento.",
    reference: "Modelo OSI"
  },
  {
    id: 2,
    section: "Teórica",
    topic: "Modelo OSI",
    difficulty: "Alta",
    text: "¿Qué capa del modelo OSI se encarga del direccionamiento lógico y el encaminamiento?",
    options: ["Enlace de datos", "Transporte", "Red"],
    answer: 2,
    explanation: "La capa de red gestiona el direccionamiento lógico y el encaminamiento.",
    reference: "Modelo OSI"
  },
  {
    id: 3,
    section: "Teórica",
    topic: "Modelo OSI",
    difficulty: "Alta",
    text: "¿En qué capa del modelo OSI trabaja principalmente una dirección MAC?",
    options: ["Enlace de datos", "Red", "Transporte"],
    answer: 0,
    explanation: "La dirección MAC pertenece a la capa de enlace de datos.",
    reference: "Modelo OSI - Redes locales"
  },
  {
    id: 4,
    section: "Teórica",
    topic: "TCP/IP",
    difficulty: "Alta",
    text: "¿Qué protocolo permite comprobar conectividad mediante mensajes echo request y echo reply?",
    options: ["ARP", "ICMP", "DNS"],
    answer: 1,
    explanation: "ICMP se usa, entre otros casos, por ping para comprobar conectividad.",
    reference: "Protocolos TCP/IP"
  },
  {
    id: 5,
    section: "Teórica",
    topic: "TCP/IP",
    difficulty: "Alta",
    text: "¿Qué protocolo permite resolver una dirección IP en una dirección MAC dentro de una red local?",
    options: ["DHCP", "DNS", "ARP"],
    answer: 2,
    explanation: "ARP obtiene la dirección MAC asociada a una IP en la LAN.",
    reference: "Protocolos TCP/IP"
  },
  {
    id: 6,
    section: "Teórica",
    topic: "Puertos",
    difficulty: "Alta",
    text: "¿Qué puerto utiliza normalmente SSH?",
    options: ["22", "23", "25"],
    answer: 0,
    explanation: "SSH utiliza normalmente el puerto TCP 22.",
    reference: "Protocolos seguros"
  },
  {
    id: 7,
    section: "Teórica",
    topic: "Puertos",
    difficulty: "Alta",
    text: "¿Qué puerto utiliza normalmente DNS?",
    options: ["53", "67", "110"],
    answer: 0,
    explanation: "DNS utiliza normalmente el puerto 53, principalmente UDP.",
    reference: "Servicios de red"
  },
  {
    id: 8,
    section: "Teórica",
    topic: "DHCP",
    difficulty: "Alta",
    text: "¿Qué puerto utiliza normalmente el servidor DHCP?",
    options: ["53", "67", "68"],
    answer: 1,
    explanation: "El servidor DHCP escucha normalmente en UDP 67.",
    reference: "Servicios de red"
  },
  {
    id: 9,
    section: "Teórica",
    topic: "Correo electrónico",
    difficulty: "Alta",
    text: "¿Qué puerto utiliza normalmente IMAP sin cifrado?",
    options: ["110", "143", "993"],
    answer: 1,
    explanation: "IMAP sin cifrado utiliza normalmente el puerto 143.",
    reference: "Correo electrónico"
  },
  {
    id: 10,
    section: "Teórica",
    topic: "Correo electrónico",
    difficulty: "Alta",
    text: "¿Qué puerto utiliza normalmente POP3 sin cifrado?",
    options: ["110", "143", "587"],
    answer: 0,
    explanation: "POP3 sin cifrado utiliza normalmente el puerto 110.",
    reference: "Correo electrónico"
  },
  {
    id: 11,
    section: "Teórica",
    topic: "VLAN",
    difficulty: "Alta",
    text: "¿Qué estándar se utiliza habitualmente para etiquetado de VLAN en Ethernet?",
    options: ["802.1Q", "802.11ac", "802.3af"],
    answer: 0,
    explanation: "IEEE 802.1Q define el etiquetado VLAN en tramas Ethernet.",
    reference: "Redes locales - VLAN"
  },
  {
    id: 12,
    section: "Teórica",
    topic: "Redes",
    difficulty: "Alta",
    text: "¿Qué dispositivo reduce dominios de colisión separando el tráfico por puertos?",
    options: ["Hub", "Switch", "Repetidor"],
    answer: 1,
    explanation: "Un switch separa dominios de colisión por puerto.",
    reference: "Redes locales"
  },
  {
    id: 13,
    section: "Teórica",
    topic: "Redes",
    difficulty: "Alta",
    text: "¿Qué dispositivo opera principalmente en capa 3 y conecta redes diferentes?",
    options: ["Router", "Hub", "Bridge"],
    answer: 0,
    explanation: "Un router trabaja en capa 3 y conecta redes distintas.",
    reference: "Dispositivos de interconexión"
  },
  {
    id: 14,
    section: "Teórica",
    topic: "IPv4",
    difficulty: "Alta",
    text: "¿Cuál es la dirección de red de 192.168.10.25/24?",
    options: ["192.168.10.0", "192.168.10.1", "192.168.10.255"],
    answer: 0,
    explanation: "Con máscara /24, la red es 192.168.10.0.",
    reference: "Direccionamiento IPv4"
  },
  {
    id: 15,
    section: "Teórica",
    topic: "IPv4",
    difficulty: "Alta",
    text: "¿Cuál es la dirección de broadcast de 192.168.10.25/24?",
    options: ["192.168.10.0", "192.168.10.255", "192.168.255.255"],
    answer: 1,
    explanation: "En una red /24, el broadcast es el último valor del cuarto octeto.",
    reference: "Direccionamiento IPv4"
  },
  {
    id: 16,
    section: "Teórica",
    topic: "IPv4",
    difficulty: "Alta",
    text: "¿Qué máscara corresponde a /26?",
    options: ["255.255.255.0", "255.255.255.128", "255.255.255.192"],
    answer: 2,
    explanation: "/26 equivale a 255.255.255.192.",
    reference: "Direccionamiento IPv4"
  },
  {
    id: 17,
    section: "Teórica",
    topic: "NAT",
    difficulty: "Alta",
    text: "¿Qué variante de NAT permite que varios equipos internos compartan una única IP pública usando puertos?",
    options: ["PAT", "ARP", "STP"],
    answer: 0,
    explanation: "PAT traduce direcciones y puertos para compartir una IP pública.",
    reference: "NAT"
  },
  {
    id: 18,
    section: "Teórica",
    topic: "TCP/UDP",
    difficulty: "Alta",
    text: "¿Cuál de estas afirmaciones describe mejor UDP?",
    options: ["Orientado a conexión y fiable", "No orientado a conexión y sin garantía de entrega", "Cifra automáticamente la comunicación"],
    answer: 1,
    explanation: "UDP no establece conexión y no garantiza entrega.",
    reference: "Protocolos TCP/IP"
  },
  {
    id: 19,
    section: "Teórica",
    topic: "TCP/UDP",
    difficulty: "Alta",
    text: "¿Qué protocolo garantiza entrega ordenada y control de flujo?",
    options: ["ICMP", "UDP", "TCP"],
    answer: 2,
    explanation: "TCP proporciona entrega fiable, ordenada y control de flujo.",
    reference: "Protocolos TCP/IP"
  },
  {
    id: 20,
    section: "Teórica",
    topic: "Seguridad",
    difficulty: "Alta",
    text: "¿Qué propiedad garantiza que un servicio esté accesible cuando se necesita?",
    options: ["Confidencialidad", "Disponibilidad", "Integridad"],
    answer: 1,
    explanation: "La disponibilidad asegura acceso a servicios y datos cuando son necesarios.",
    reference: "Seguridad de la información"
  },
  {
    id: 21,
    section: "Teórica",
    topic: "Seguridad",
    difficulty: "Alta",
    text: "¿Qué tipo de malware cifra archivos y exige un pago para recuperarlos?",
    options: ["Ransomware", "Spyware", "Adware"],
    answer: 0,
    explanation: "El ransomware cifra datos y pide rescate.",
    reference: "Amenazas de seguridad"
  },
  {
    id: 22,
    section: "Teórica",
    topic: "Seguridad",
    difficulty: "Alta",
    text: "¿Qué mecanismo permite verificar la identidad de un sitio web mediante certificados?",
    options: ["DNS", "PKI", "NAT"],
    answer: 1,
    explanation: "La PKI permite gestionar certificados digitales y verificar identidades.",
    reference: "Criptografía - Certificados"
  },
  {
    id: 23,
    section: "Teórica",
    topic: "Seguridad",
    difficulty: "Alta",
    text: "¿Qué protocolo seguro sustituye funcionalmente a Telnet para administración remota?",
    options: ["SSH", "FTP", "SMTP"],
    answer: 0,
    explanation: "SSH permite administración remota segura frente a Telnet.",
    reference: "Protocolos seguros"
  },
  {
    id: 24,
    section: "Teórica",
    topic: "VPN",
    difficulty: "Alta",
    text: "¿Qué característica es esencial en una VPN?",
    options: ["Túnel cifrado", "Aumento de RAM", "Compilación de código"],
    answer: 0,
    explanation: "Una VPN crea un túnel cifrado sobre una red no confiable.",
    reference: "VPN"
  },
  {
    id: 25,
    section: "Teórica",
    topic: "Active Directory",
    difficulty: "Alta",
    text: "¿Qué protocolo se utiliza habitualmente para consultar servicios de directorio como Active Directory?",
    options: ["LDAP", "SNMP", "ICMP"],
    answer: 0,
    explanation: "LDAP se utiliza para consultar y modificar servicios de directorio.",
    reference: "Active Directory"
  },

    {
    id: 26,
    section: "Teórica",
    topic: "Active Directory",
    difficulty: "Alta",
    text: "¿Qué componente almacena la base de datos principal de Active Directory?",
    options: ["SYSVOL", "NTDS.dit", "Registry"],
    answer: 1,
    explanation: "NTDS.dit contiene la base de datos de Active Directory.",
    reference: "Active Directory"
  },
  {
    id: 27,
    section: "Teórica",
    topic: "Windows",
    difficulty: "Alta",
    text: "¿Qué herramienta permite aplicar configuraciones centralizadas a usuarios y equipos en un dominio?",
    options: ["GPO", "DNS", "DHCP"],
    answer: 0,
    explanation: "Las GPO permiten aplicar configuraciones y restricciones desde Active Directory.",
    reference: "Administración Windows"
  },
  {
    id: 28,
    section: "Teórica",
    topic: "Linux",
    difficulty: "Alta",
    text: "¿Qué comando muestra el directorio actual de trabajo?",
    options: ["ls", "pwd", "cd"],
    answer: 1,
    explanation: "pwd muestra la ruta absoluta del directorio actual.",
    reference: "Linux"
  },
  {
    id: 29,
    section: "Teórica",
    topic: "Linux",
    difficulty: "Alta",
    text: "¿Qué comando cambia permisos sobre archivos y directorios?",
    options: ["chown", "chmod", "passwd"],
    answer: 1,
    explanation: "chmod modifica permisos de lectura, escritura y ejecución.",
    reference: "Linux"
  },
  {
    id: 30,
    section: "Teórica",
    topic: "Linux",
    difficulty: "Alta",
    text: "¿Qué permiso representa el valor numérico 7 en Linux?",
    options: ["Lectura + escritura", "Lectura + ejecución", "Lectura + escritura + ejecución"],
    answer: 2,
    explanation: "7 = 4+2+1 = rwx.",
    reference: "Permisos Linux"
  },
  {
    id: 31,
    section: "Teórica",
    topic: "Virtualización",
    difficulty: "Alta",
    text: "¿Qué tipo de hipervisor se ejecuta directamente sobre el hardware?",
    options: ["Tipo 1", "Tipo 2", "Tipo Hosted"],
    answer: 0,
    explanation: "Los hipervisores tipo 1 se ejecutan directamente sobre el hardware.",
    reference: "Virtualización"
  },
  {
    id: 32,
    section: "Teórica",
    topic: "Virtualización",
    difficulty: "Alta",
    text: "¿Cuál de los siguientes es un hipervisor de tipo 1?",
    options: ["VirtualBox", "VMware ESXi", "VMware Workstation"],
    answer: 1,
    explanation: "ESXi es un hipervisor bare-metal (tipo 1).",
    reference: "Virtualización"
  },
  {
    id: 33,
    section: "Teórica",
    topic: "Contenedores",
    difficulty: "Alta",
    text: "¿Qué tecnología permite empaquetar aplicaciones y dependencias de forma aislada compartiendo kernel?",
    options: ["Docker", "Hyper-V", "RAID"],
    answer: 0,
    explanation: "Docker utiliza contenedores compartiendo el kernel del sistema anfitrión.",
    reference: "Contenedores y microservicios"
  },
  {
    id: 34,
    section: "Teórica",
    topic: "Backups",
    difficulty: "Alta",
    text: "¿Qué tipo de copia guarda los cambios realizados desde la última copia completa?",
    options: ["Incremental", "Diferencial", "Espejo"],
    answer: 1,
    explanation: "La copia diferencial almacena cambios desde la última copia completa.",
    reference: "Backups"
  },
  {
    id: 35,
    section: "Teórica",
    topic: "Backups",
    difficulty: "Alta",
    text: "¿Qué estrategia permite restaurar más rápido normalmente?",
    options: ["Incremental pura", "Diferencial", "Solo incrementales encadenadas"],
    answer: 1,
    explanation: "La restauración diferencial suele requerir menos pasos.",
    reference: "Backups"
  },
  {
    id: 36,
    section: "Teórica",
    topic: "Hardware",
    difficulty: "Alta",
    text: "¿Qué componente conecta todos los dispositivos principales de un ordenador?",
    options: ["Fuente de alimentación", "Placa base", "Disco SSD"],
    answer: 1,
    explanation: "La placa base interconecta CPU, memoria y periféricos.",
    reference: "Fundamentos Hardware"
  },
  {
    id: 37,
    section: "Teórica",
    topic: "Hardware",
    difficulty: "Alta",
    text: "¿Qué memoria conserva la información al apagar el equipo?",
    options: ["RAM", "Caché", "ROM"],
    answer: 2,
    explanation: "La ROM es memoria no volátil.",
    reference: "Memoria principal"
  },
  {
    id: 38,
    section: "Teórica",
    topic: "Hardware",
    difficulty: "Alta",
    text: "¿Qué tecnología ofrece normalmente menor latencia en almacenamiento?",
    options: ["SSD NVMe", "HDD SATA", "DVD"],
    answer: 0,
    explanation: "Los SSD NVMe presentan latencias muy inferiores a HDD.",
    reference: "Almacenamiento"
  },
  {
    id: 39,
    section: "Teórica",
    topic: "Bases de Datos",
    difficulty: "Alta",
    text: "¿Qué propiedad garantiza que una clave primaria no pueda repetirse?",
    options: ["Integridad referencial", "Unicidad", "Normalización"],
    answer: 1,
    explanation: "La clave primaria debe ser única para cada registro.",
    reference: "Modelo Relacional"
  },
  {
    id: 40,
    section: "Teórica",
    topic: "Bases de Datos",
    difficulty: "Alta",
    text: "¿Qué sentencia SQL añade registros a una tabla?",
    options: ["UPDATE", "SELECT", "INSERT"],
    answer: 2,
    explanation: "INSERT añade nuevas filas a una tabla.",
    reference: "SQL"
  },
  {
    id: 41,
    section: "Teórica",
    topic: "Bases de Datos",
    difficulty: "Alta",
    text: "¿Qué sentencia SQL modifica registros existentes?",
    options: ["UPDATE", "DELETE", "ALTER"],
    answer: 0,
    explanation: "UPDATE modifica filas existentes.",
    reference: "SQL"
  },
  {
    id: 42,
    section: "Teórica",
    topic: "Bases de Datos",
    difficulty: "Alta",
    text: "¿Qué proceso busca reducir redundancia y dependencias indebidas?",
    options: ["Indexación", "Normalización", "Fragmentación"],
    answer: 1,
    explanation: "La normalización mejora la estructura lógica de la base de datos.",
    reference: "Diseño de Bases de Datos"
  },
  {
    id: 43,
    section: "Teórica",
    topic: "Programación",
    difficulty: "Alta",
    text: "¿Qué estructura almacena varios elementos del mismo tipo bajo un único identificador?",
    options: ["Array", "Bucle", "Condicional"],
    answer: 0,
    explanation: "Un array permite almacenar múltiples elementos del mismo tipo.",
    reference: "Programación"
  },
  {
    id: 44,
    section: "Teórica",
    topic: "Programación",
    difficulty: "Alta",
    text: "¿Qué mecanismo permite que una función se llame a sí misma?",
    options: ["Iteración", "Recursividad", "Compilación"],
    answer: 1,
    explanation: "La recursividad consiste en llamadas a sí misma.",
    reference: "Programación"
  },
  {
    id: 45,
    section: "Teórica",
    topic: "Web",
    difficulty: "Alta",
    text: "¿Qué protocolo utiliza HTTPS para proteger las comunicaciones?",
    options: ["TLS", "FTP", "ARP"],
    answer: 0,
    explanation: "HTTPS utiliza TLS para cifrar la comunicación.",
    reference: "Internet"
  },
  {
    id: 46,
    section: "Teórica",
    topic: "Web",
    difficulty: "Alta",
    text: "¿Qué lenguaje define principalmente la estructura de una página web?",
    options: ["CSS", "JavaScript", "HTML"],
    answer: 2,
    explanation: "HTML define la estructura y contenido.",
    reference: "Aplicaciones Web"
  },
  {
    id: 47,
    section: "Teórica",
    topic: "Git",
    difficulty: "Alta",
    text: "¿Cuál es la finalidad principal de Git?",
    options: ["Control de versiones", "Monitorización de red", "Virtualización"],
    answer: 0,
    explanation: "Git permite gestionar cambios en código y documentación.",
    reference: "Control de versiones"
  },
  {
    id: 48,
    section: "Teórica",
    topic: "Legislación",
    difficulty: "Alta",
    text: "¿Qué ley regula la protección de datos personales y garantía de derechos digitales en España?",
    options: ["LO 1/2004", "LO 3/2018", "LO 3/2007"],
    answer: 1,
    explanation: "La Ley Orgánica 3/2018 regula la protección de datos personales.",
    reference: "Anexo B"
  },
  {
    id: 49,
    section: "Teórica",
    topic: "Legislación",
    difficulty: "Alta",
    text: "¿Qué ley regula la igualdad efectiva de mujeres y hombres?",
    options: ["LO 1/2004", "LO 3/2018", "LO 3/2007"],
    answer: 2,
    explanation: "La Ley Orgánica 3/2007 regula la igualdad efectiva.",
    reference: "Anexo B"
  },
  {
    id: 50,
    section: "Teórica",
    topic: "Legislación",
    difficulty: "Alta",
    text: "¿Qué ley establece medidas de protección integral contra la violencia de género?",
    options: ["LO 1/2004", "LO 3/2007", "LO 3/2018"],
    answer: 0,
    explanation: "La Ley Orgánica 1/2004 regula las medidas de protección integral contra la violencia de género.",
    reference: "Anexo B"
  }
];