const questions = [
  {
    id: 1,
    section: "Redes",
    topic: "Modelo OSI",
    difficulty: "media",
    text: "¿En qué capa del modelo OSI trabaja principalmente un router?",
    options: ["Capa de enlace", "Capa de red", "Capa de transporte"],
    answer: 1,
    explanation: "El router toma decisiones usando direcciones IP, propias de la capa 3 o capa de red.",
    reference: "Modelo OSI - Capa de red"
  },
  {
    id: 2,
    section: "Redes",
    topic: "Modelo OSI",
    difficulty: "media",
    text: "¿Cuál es la PDU característica de la capa de transporte?",
    options: ["Segmento", "Trama", "Paquete"],
    answer: 0,
    explanation: "En transporte la PDU se denomina segmento, especialmente en TCP.",
    reference: "Modelo OSI - PDU"
  },
  {
    id: 3,
    section: "TCP/IP",
    topic: "DHCP",
    difficulty: "trampa",
    text: "¿Cuál es el primer mensaje que envía un cliente al iniciar el proceso DHCP?",
    options: ["DHCP Offer", "DHCP Discover", "DHCP Request"],
    answer: 1,
    explanation: "El cliente primero emite DHCP Discover para localizar servidores DHCP disponibles.",
    reference: "DHCP DORA"
  },
  {
    id: 4,
    section: "Bases de datos",
    topic: "SQL",
    difficulty: "trampa",
    text: "¿Qué cláusula SQL se usa para filtrar filas antes de agrupar resultados?",
    options: ["HAVING", "WHERE", "GROUP BY"],
    answer: 1,
    explanation: "WHERE filtra registros antes de aplicar GROUP BY.",
    reference: "SQL - WHERE vs HAVING"
  },
  {
    id: 5,
    section: "Bases de datos",
    topic: "SQL",
    difficulty: "trampa",
    text: "¿Qué cláusula SQL se usa para filtrar grupos después de una agrupación?",
    options: ["WHERE", "ORDER BY", "HAVING"],
    answer: 2,
    explanation: "HAVING filtra resultados agregados después de GROUP BY.",
    reference: "SQL - WHERE vs HAVING"
  },
  {
    id: 6,
    section: "Hardware",
    topic: "Memoria",
    difficulty: "media",
    text: "¿Qué tipo de memoria pierde su contenido al apagar el equipo?",
    options: ["ROM", "RAM", "SSD"],
    answer: 1,
    explanation: "La RAM es memoria volátil.",
    reference: "Fundamentos de hardware - Memoria principal"
  },
  {
    id: 7,
    section: "Hardware",
    topic: "CPU",
    difficulty: "media",
    text: "¿Qué componente de la CPU realiza operaciones aritméticas y lógicas?",
    options: ["ALU", "BIOS", "Chipset"],
    answer: 0,
    explanation: "La ALU es la unidad aritmético-lógica.",
    reference: "CPU - Arquitectura básica"
  },
  {
    id: 8,
    section: "Sistemas operativos",
    topic: "Procesos",
    difficulty: "media",
    text: "¿Qué es un proceso en un sistema operativo?",
    options: ["Un programa en ejecución", "Un archivo comprimido", "Una partición del disco"],
    answer: 0,
    explanation: "Un proceso es una instancia de un programa que se está ejecutando.",
    reference: "Sistemas operativos - Procesos"
  },
  {
    id: 9,
    section: "Redes",
    topic: "Switch",
    difficulty: "media",
    text: "¿Qué dirección utiliza principalmente un switch para reenviar tramas?",
    options: ["Dirección IP", "Dirección MAC", "Puerto TCP"],
    answer: 1,
    explanation: "El switch trabaja con direcciones MAC en la capa de enlace.",
    reference: "Redes LAN - Switch"
  },
  {
    id: 10,
    section: "Redes",
    topic: "Hub",
    difficulty: "media",
    text: "¿Qué dispositivo repite señales a todos sus puertos sin analizar direcciones?",
    options: ["Router", "Hub", "Switch gestionable"],
    answer: 1,
    explanation: "El hub opera a nivel físico y no interpreta direcciones MAC ni IP.",
    reference: "Dispositivos de interconexión"
  },
  {
    id: 11,
    section: "TCP/IP",
    topic: "DNS",
    difficulty: "media",
    text: "¿Qué servicio traduce nombres de dominio a direcciones IP?",
    options: ["DHCP", "DNS", "NAT"],
    answer: 1,
    explanation: "DNS resuelve nombres como ejemplo.com hacia direcciones IP.",
    reference: "Servicios de red - DNS"
  },
  {
    id: 12,
    section: "TCP/IP",
    topic: "ARP",
    difficulty: "media",
    text: "¿Para qué se utiliza ARP en IPv4?",
    options: ["Para resolver una IP a una MAC", "Para asignar IP automáticamente", "Para cifrar conexiones web"],
    answer: 0,
    explanation: "ARP permite conocer la MAC asociada a una IP dentro de la red local.",
    reference: "TCP/IP - ARP"
  },
  {
    id: 13,
    section: "TCP/IP",
    topic: "NAT",
    difficulty: "media",
    text: "¿Qué permite NAT en una red privada?",
    options: ["Que varios equipos salgan a Internet usando una IP pública", "Que se cifre todo el tráfico LAN", "Que se eliminen las direcciones MAC"],
    answer: 0,
    explanation: "NAT traduce direcciones privadas a una dirección pública.",
    reference: "TCP/IP - NAT"
  },
  {
    id: 14,
    section: "Seguridad",
    topic: "Firewall",
    difficulty: "media",
    text: "¿Cuál es la función principal de un firewall?",
    options: ["Filtrar tráfico según reglas", "Aumentar la memoria RAM", "Asignar direcciones IP"],
    answer: 0,
    explanation: "Un firewall permite o bloquea tráfico según reglas configuradas.",
    reference: "Seguridad perimetral"
  },
  {
    id: 15,
    section: "Seguridad",
    topic: "VPN",
    difficulty: "media",
    text: "¿Qué proporciona principalmente una VPN?",
    options: ["Acceso remoto seguro a una red", "Más velocidad de CPU", "Sustitución del DNS"],
    answer: 0,
    explanation: "Una VPN crea un túnel seguro para conectarse a una red remota.",
    reference: "VPN - Acceso remoto seguro"
  },
  {
    id: 16,
    section: "Internet",
    topic: "HTTPS",
    difficulty: "media",
    text: "¿Qué protocolo añade cifrado a HTTP?",
    options: ["TLS", "FTP", "ICMP"],
    answer: 0,
    explanation: "HTTPS usa TLS para proteger la comunicación.",
    reference: "HTTP, HTTPS y TLS"
  },
  {
    id: 17,
    section: "Internet",
    topic: "Puertos",
    difficulty: "media",
    text: "¿Cuál es el puerto habitual de HTTPS?",
    options: ["80", "443", "25"],
    answer: 1,
    explanation: "HTTPS usa normalmente el puerto TCP 443.",
    reference: "Puertos TCP/IP"
  },
  {
    id: 18,
    section: "Internet",
    topic: "Puertos",
    difficulty: "media",
    text: "¿Cuál es el puerto habitual de HTTP?",
    options: ["80", "110", "3389"],
    answer: 0,
    explanation: "HTTP utiliza normalmente el puerto TCP 80.",
    reference: "Puertos TCP/IP"
  },
  {
    id: 19,
    section: "Correo",
    topic: "Protocolos",
    difficulty: "media",
    text: "¿Qué protocolo se utiliza normalmente para enviar correo electrónico?",
    options: ["SMTP", "POP3", "IMAP"],
    answer: 0,
    explanation: "SMTP se usa para el envío de correo.",
    reference: "Protocolos de correo"
  },
  {
    id: 20,
    section: "Correo",
    topic: "Protocolos",
    difficulty: "media",
    text: "¿Qué protocolo permite consultar el correo manteniéndolo sincronizado en el servidor?",
    options: ["POP3", "IMAP", "SMTP"],
    answer: 1,
    explanation: "IMAP permite trabajar con el correo conservándolo en el servidor.",
    reference: "IMAP vs POP3"
  },
  {
    id: 21,
    section: "Sistemas operativos",
    topic: "Linux",
    difficulty: "media",
    text: "¿Qué comando Linux muestra el contenido de un directorio?",
    options: ["ls", "cd", "pwd"],
    answer: 0,
    explanation: "ls lista archivos y directorios.",
    reference: "Linux básico"
  },
  {
    id: 22,
    section: "Sistemas operativos",
    topic: "Linux",
    difficulty: "media",
    text: "¿Qué permiso representa la letra x en Linux?",
    options: ["Lectura", "Escritura", "Ejecución"],
    answer: 2,
    explanation: "x indica permiso de ejecución.",
    reference: "Permisos Linux"
  },
  {
    id: 23,
    section: "Sistemas Windows",
    topic: "Active Directory",
    difficulty: "media",
    text: "¿Qué permite principalmente Active Directory?",
    options: ["Gestionar usuarios, equipos y recursos de dominio", "Crear páginas web", "Comprimir bases de datos"],
    answer: 0,
    explanation: "Active Directory centraliza la administración de identidades y recursos.",
    reference: "Active Directory"
  },
  {
    id: 24,
    section: "Sistemas Windows",
    topic: "GPO",
    difficulty: "media",
    text: "¿Para qué se usan las GPO en un dominio Windows?",
    options: ["Aplicar políticas de configuración", "Crear VLAN físicas", "Formatear discos automáticamente"],
    answer: 0,
    explanation: "Las GPO aplican configuraciones y restricciones a usuarios o equipos.",
    reference: "Directivas de grupo"
  },
  {
    id: 25,
    section: "Virtualización",
    topic: "Snapshot",
    difficulty: "media",
    text: "¿Qué es un snapshot en virtualización?",
    options: ["Una copia del estado de una máquina virtual en un momento concreto", "Una copia física del monitor", "Un protocolo de red"],
    answer: 0,
    explanation: "Un snapshot permite volver a un estado anterior de la máquina virtual.",
    reference: "Virtualización - Snapshots"
  },
  {
    id: 26,
    section: "Virtualización",
    topic: "Hipervisor",
    difficulty: "media",
    text: "¿Qué función tiene un hipervisor?",
    options: ["Gestionar máquinas virtuales", "Resolver nombres DNS", "Filtrar spam"],
    answer: 0,
    explanation: "El hipervisor permite crear y ejecutar máquinas virtuales.",
    reference: "Virtualización - Hipervisor"
  },
  {
    id: 27,
    section: "Backups",
    topic: "Tipos de copia",
    difficulty: "media",
    text: "¿Qué copia guarda solo los cambios desde la última copia completa?",
    options: ["Copia completa", "Copia diferencial", "Clonación de pantalla"],
    answer: 1,
    explanation: "La diferencial guarda los cambios desde la última copia completa.",
    reference: "Backups - Tipos"
  },
  {
    id: 28,
    section: "Backups",
    topic: "Tipos de copia",
    difficulty: "media",
    text: "¿Qué copia guarda solo los cambios desde la última copia realizada, sea completa o incremental?",
    options: ["Incremental", "Completa", "Diferencial"],
    answer: 0,
    explanation: "La incremental toma como referencia la última copia realizada.",
    reference: "Backups - Tipos"
  },
  {
    id: 29,
    section: "Bases de datos",
    topic: "Modelo relacional",
    difficulty: "media",
    text: "¿Qué identifica de forma única cada fila de una tabla?",
    options: ["Clave primaria", "Clave externa", "Índice secundario"],
    answer: 0,
    explanation: "La clave primaria identifica de forma única cada registro.",
    reference: "Bases de datos relacionales"
  },
  {
    id: 30,
    section: "Bases de datos",
    topic: "Modelo relacional",
    difficulty: "media",
    text: "¿Qué es una clave externa?",
    options: ["Un campo que relaciona una tabla con la clave primaria de otra", "Una contraseña del servidor", "Un tipo de índice de memoria RAM"],
    answer: 0,
    explanation: "La clave externa permite establecer relaciones entre tablas.",
    reference: "Bases de datos relacionales"
  },
  {
    id: 31,
    section: "Bases de datos",
    topic: "SQL",
    difficulty: "trampa",
    text: "En una consulta con GROUP BY, ¿dónde debe ponerse una condición sobre COUNT(*)?",
    options: ["WHERE", "HAVING", "FROM"],
    answer: 1,
    explanation: "Las condiciones sobre funciones agregadas se filtran con HAVING.",
    reference: "SQL - HAVING"
  },
  {
    id: 32,
    section: "Bases de datos",
    topic: "SQL",
    difficulty: "trampa",
    text: "En SQL, ¿qué cláusula se ejecuta conceptualmente antes de GROUP BY para descartar filas?",
    options: ["WHERE", "HAVING", "ORDER BY"],
    answer: 0,
    explanation: "WHERE filtra filas antes de que se formen los grupos.",
    reference: "SQL - WHERE"
  },
  {
    id: 33,
    section: "Programación",
    topic: "Condicionales",
    difficulty: "baja",
    text: "¿Qué estructura permite ejecutar código solo si se cumple una condición?",
    options: ["if", "for", "array"],
    answer: 0,
    explanation: "if permite evaluar una condición y ejecutar un bloque si es verdadera.",
    reference: "Programación básica"
  },
  {
    id: 34,
    section: "Programación",
    topic: "Bucles",
    difficulty: "baja",
    text: "¿Qué estructura se usa para repetir instrucciones?",
    options: ["Bucle", "Constante", "Comentario"],
    answer: 0,
    explanation: "Los bucles repiten instrucciones mientras se cumpla una condición o durante un número de iteraciones.",
    reference: "Programación básica"
  },
  {
    id: 35,
    section: "Desarrollo web",
    topic: "HTML",
    difficulty: "baja",
    text: "¿Para qué se utiliza principalmente HTML?",
    options: ["Definir la estructura de una página web", "Gestionar direcciones IP", "Cifrar discos"],
    answer: 0,
    explanation: "HTML define la estructura y contenido de una página web.",
    reference: "HTML básico"
  },
  {
    id: 36,
    section: "Desarrollo web",
    topic: "CSS",
    difficulty: "baja",
    text: "¿Para qué se utiliza principalmente CSS?",
    options: ["Aplicar estilos visuales", "Crear tablas SQL", "Asignar IP dinámicas"],
    answer: 0,
    explanation: "CSS controla el diseño visual de una página web.",
    reference: "CSS básico"
  },
  {
    id: 37,
    section: "Git",
    topic: "Control de versiones",
    difficulty: "media",
    text: "¿Qué permite un sistema de control de versiones como Git?",
    options: ["Registrar cambios en el código", "Aumentar la velocidad de red", "Reparar discos SSD"],
    answer: 0,
    explanation: "Git permite controlar cambios, ramas y versiones de un proyecto.",
    reference: "Control de versiones"
  },
  {
    id: 38,
    section: "Seguridad",
    topic: "Malware",
    difficulty: "media",
    text: "¿Qué tipo de malware cifra archivos y pide un rescate?",
    options: ["Ransomware", "Spyware", "Adware"],
    answer: 0,
    explanation: "El ransomware cifra información y exige pago para recuperarla.",
    reference: "Amenazas de seguridad"
  },
  {
    id: 39,
    section: "Seguridad",
    topic: "Criptografía",
    difficulty: "media",
    text: "¿Qué característica tiene la criptografía asimétrica?",
    options: ["Usa una clave pública y una privada", "No utiliza claves", "Solo funciona en redes LAN"],
    answer: 0,
    explanation: "La criptografía asimétrica usa un par de claves: pública y privada.",
    reference: "Criptografía"
  },
  {
    id: 40,
    section: "Seguridad",
    topic: "Firma digital",
    difficulty: "media",
    text: "¿Qué garantiza principalmente una firma digital?",
    options: ["Autenticidad e integridad", "Mayor velocidad de descarga", "Asignación automática de IP"],
    answer: 0,
    explanation: "La firma digital permite verificar autoría e integridad del documento.",
    reference: "Firma digital"
  },
  {
    id: 41,
    section: "TCP/IP",
    topic: "DHCP",
    difficulty: "trampa",
    text: "En el proceso DHCP, después de DHCP Discover, ¿qué mensaje responde normalmente el servidor?",
    options: ["DHCP Offer", "DHCP Request", "DHCP ACK"],
    answer: 0,
    explanation: "Tras Discover, el servidor ofrece una configuración mediante DHCP Offer.",
    reference: "DHCP DORA"
  },
  {
    id: 42,
    section: "TCP/IP",
    topic: "DHCP",
    difficulty: "trampa",
    text: "¿Cuál es el orden correcto del proceso DHCP básico?",
    options: ["Discover, Offer, Request, ACK", "Request, Discover, Offer, ACK", "Offer, Discover, ACK, Request"],
    answer: 0,
    explanation: "El orden clásico es DORA: Discover, Offer, Request, ACK.",
    reference: "DHCP DORA"
  },
  {
    id: 43,
    section: "Redes",
    topic: "VLAN",
    difficulty: "media",
    text: "¿Qué permite una VLAN?",
    options: ["Segmentar lógicamente una red", "Eliminar el uso de switches", "Convertir IPv4 en IPv6"],
    answer: 0,
    explanation: "Una VLAN divide una red física en redes lógicas separadas.",
    reference: "Redes locales - VLAN"
  },
  {
    id: 44,
    section: "Redes",
    topic: "Medios de transmisión",
    difficulty: "media",
    text: "¿Qué medio utiliza pares de cobre trenzados?",
    options: ["UTP", "Fibra óptica", "Wi-Fi"],
    answer: 0,
    explanation: "UTP es cable de par trenzado no apantallado.",
    reference: "Medios de transmisión"
  },
  {
    id: 45,
    section: "TCP/IP",
    topic: "ICMP",
    difficulty: "media",
    text: "¿Qué protocolo utiliza habitualmente la herramienta ping?",
    options: ["ICMP", "SMTP", "FTP"],
    answer: 0,
    explanation: "ping utiliza mensajes ICMP Echo Request y Echo Reply.",
    reference: "TCP/IP - ICMP"
  },
  {
    id: 46,
    section: "TCP/IP",
    topic: "IPv4",
    difficulty: "media",
    text: "¿Qué máscara corresponde habitualmente a una red /24?",
    options: ["255.255.255.0", "255.255.0.0", "255.0.0.0"],
    answer: 0,
    explanation: "/24 equivale a 255.255.255.0.",
    reference: "Direccionamiento IPv4"
  },
  {
    id: 47,
    section: "Sistemas operativos",
    topic: "Arranque",
    difficulty: "media",
    text: "¿Qué firmware moderno sustituye a la BIOS tradicional en muchos equipos actuales?",
    options: ["UEFI", "NTFS", "RAID"],
    answer: 0,
    explanation: "UEFI es el firmware moderno usado en el arranque de muchos equipos.",
    reference: "Arranque de equipos"
  },
  {
    id: 48,
    section: "Hardware",
    topic: "Almacenamiento",
    difficulty: "media",
    text: "¿Qué tecnología permite conectar SSD de alto rendimiento directamente mediante PCI Express?",
    options: ["NVMe", "SATA", "VGA"],
    answer: 0,
    explanation: "NVMe permite aprovechar PCI Express para almacenamiento SSD de alto rendimiento.",
    reference: "Almacenamiento - NVMe"
  },
  {
    id: 49,
    section: "Sistemas",
    topic: "Contenedores",
    difficulty: "media",
    text: "¿Qué caracteriza a un contenedor frente a una máquina virtual tradicional?",
    options: ["Comparte el kernel del sistema anfitrión", "Siempre necesita una BIOS propia", "Emula obligatoriamente hardware completo"],
    answer: 0,
    explanation: "Los contenedores comparten el kernel del host y aíslan procesos.",
    reference: "Contenedores y microservicios"
  },
  {
    id: 50,
    section: "Legislación",
    topic: "Protección de datos",
    difficulty: "media",
    text: "¿Qué norma española regula la protección de datos personales y garantía de derechos digitales?",
    options: ["LOPDGDD 3/2018", "Ley 39/2015", "Ley 31/1995"],
    answer: 0,
    explanation: "La Ley Orgánica 3/2018 regula la protección de datos personales y garantía de derechos digitales.",
    reference: "LOPDGDD 3/2018"
  }
];