const questions = [
  {
    id: 1,
    section: "Bases de Datos",
    topic: "SQL",
    difficulty: "Elite",
    text: "En una consulta SQL, ¿qué cláusula se evalúa lógicamente antes de aplicar una función de agregación?",
    options: ["WHERE", "HAVING", "ORDER BY"],
    answer: 0,
    explanation: "WHERE filtra filas antes de agrupar. HAVING filtra grupos ya agregados.",
    reference: "SQL: WHERE vs HAVING"
  },
  {
    id: 2,
    section: "Bases de Datos",
    topic: "SQL",
    difficulty: "Elite",
    text: "¿Qué sentencia devuelve clientes aunque no tengan pedidos asociados?",
    options: ["INNER JOIN", "LEFT JOIN", "FULL INNER JOIN"],
    answer: 1,
    explanation: "LEFT JOIN devuelve todos los registros de la tabla izquierda y los coincidentes de la derecha.",
    reference: "SQL JOIN"
  },
  {
    id: 3,
    section: "Bases de Datos",
    topic: "Normalización",
    difficulty: "Elite",
    text: "Una tabla contiene datos repetidos de cliente en cada pedido. ¿Qué problema principal existe?",
    options: ["Redundancia y anomalías de actualización", "Falta de clave primaria compuesta", "Uso incorrecto de índices"],
    answer: 0,
    explanation: "La repetición de datos genera redundancia e inconsistencias al actualizar.",
    reference: "Normalización"
  },
  {
    id: 4,
    section: "Bases de Datos",
    topic: "Transacciones",
    difficulty: "Elite",
    text: "¿Qué propiedad ACID garantiza que una transacción se ejecuta completa o no se ejecuta?",
    options: ["Atomicidad", "Aislamiento", "Durabilidad"],
    answer: 0,
    explanation: "Atomicidad significa todo o nada.",
    reference: "ACID"
  },
  {
    id: 5,
    section: "Bases de Datos",
    topic: "Índices",
    difficulty: "Elite",
    text: "¿Cuál es el efecto más probable de crear un índice sobre una columna muy consultada en búsquedas?",
    options: ["Acelera lecturas pero puede penalizar escrituras", "Acelera siempre lecturas y escrituras", "Reduce automáticamente el tamaño de la tabla"],
    answer: 0,
    explanation: "Los índices mejoran búsquedas, pero deben mantenerse en INSERT, UPDATE y DELETE.",
    reference: "Índices SQL"
  },
  {
    id: 6,
    section: "Bases de Datos",
    topic: "SQL",
    difficulty: "Elite",
    text: "¿Qué instrucción se utiliza para eliminar todos los registros de una tabla manteniendo su estructura?",
    options: ["DROP TABLE", "TRUNCATE TABLE", "DELETE DATABASE"],
    answer: 1,
    explanation: "TRUNCATE elimina los registros, pero mantiene la tabla.",
    reference: "SQL DDL/DML"
  },
  {
    id: 7,
    section: "Seguridad",
    topic: "Criptografía",
    difficulty: "Elite",
    text: "¿Qué mecanismo permite garantizar la integridad de un mensaje?",
    options: ["Hash", "Compresión", "Fragmentación"],
    answer: 0,
    explanation: "Un hash permite comprobar si el contenido ha sido alterado.",
    reference: "Funciones hash"
  },
  {
    id: 8,
    section: "Seguridad",
    topic: "Firma digital",
    difficulty: "Elite",
    text: "En una firma digital, ¿qué clave se usa normalmente para verificar la firma?",
    options: ["Clave pública del firmante", "Clave privada del receptor", "Clave simétrica compartida"],
    answer: 0,
    explanation: "La firma se verifica con la clave pública del firmante.",
    reference: "Firma digital"
  },
  {
    id: 9,
    section: "Seguridad",
    topic: "VPN",
    difficulty: "Elite",
    text: "¿Cuál es el objetivo principal de una VPN en acceso remoto?",
    options: ["Crear un canal cifrado sobre una red no confiable", "Sustituir el direccionamiento IP privado", "Eliminar la necesidad de autenticación"],
    answer: 0,
    explanation: "Una VPN protege la comunicación creando un túnel cifrado.",
    reference: "VPN"
  },
  {
    id: 10,
    section: "Seguridad",
    topic: "Firewall",
    difficulty: "Elite",
    text: "Un firewall de capa 4 filtra principalmente según:",
    options: ["IP, protocolo y puerto", "Contenido HTML", "Usuarios de Active Directory"],
    answer: 0,
    explanation: "La capa 4 trabaja con TCP/UDP y puertos.",
    reference: "Firewall"
  },
  {
    id: 11,
    section: "Seguridad",
    topic: "Amenazas",
    difficulty: "Elite",
    text: "¿Qué ataque intenta engañar al usuario para revelar credenciales?",
    options: ["Phishing", "DDoS", "Spoofing ARP"],
    answer: 0,
    explanation: "El phishing busca obtener información sensible mediante engaño.",
    reference: "Amenazas"
  },
  {
    id: 12,
    section: "Seguridad",
    topic: "Disponibilidad",
    difficulty: "Elite",
    text: "¿Qué medida mejora directamente la disponibilidad de un servicio crítico?",
    options: ["Redundancia", "Ofuscación", "Compresión"],
    answer: 0,
    explanation: "La redundancia permite continuidad si falla un componente.",
    reference: "Alta disponibilidad"
  },
  {
    id: 13,
    section: "Virtualización",
    topic: "Hipervisores",
    difficulty: "Elite",
    text: "¿Qué caracteriza a un hipervisor tipo 1?",
    options: ["Se ejecuta directamente sobre el hardware", "Necesita siempre Windows como sistema anfitrión", "Solo permite contenedores"],
    answer: 0,
    explanation: "Un hipervisor tipo 1 es bare-metal.",
    reference: "Virtualización"
  },
  {
    id: 14,
    section: "Virtualización",
    topic: "Snapshots",
    difficulty: "Elite",
    text: "¿Cuál es la afirmación correcta sobre un snapshot?",
    options: ["No sustituye a una copia de seguridad", "Es siempre una copia completa independiente", "Solo sirve para máquinas apagadas"],
    answer: 0,
    explanation: "Un snapshot captura un estado temporal, pero no debe considerarse backup definitivo.",
    reference: "Snapshots"
  },
  {
    id: 15,
    section: "Virtualización",
    topic: "Contenedores",
    difficulty: "Elite",
    text: "¿Qué diferencia principal hay entre una máquina virtual y un contenedor?",
    options: ["El contenedor comparte kernel con el host", "La máquina virtual no necesita sistema operativo", "El contenedor siempre emula hardware completo"],
    answer: 0,
    explanation: "Los contenedores aíslan procesos compartiendo el kernel del host.",
    reference: "Docker / contenedores"
  },
  {
    id: 16,
    section: "Virtualización",
    topic: "Recursos",
    difficulty: "Elite",
    text: "¿Qué problema aparece cuando se asignan más recursos virtuales de los disponibles físicamente?",
    options: ["Sobreasignación", "Clonado diferencial", "Thin provisioning inverso"],
    answer: 0,
    explanation: "La sobreasignación puede provocar degradación si todas las máquinas demandan recursos a la vez.",
    reference: "Overcommit"
  },
  {
    id: 17,
    section: "Virtualización",
    topic: "Backup",
    difficulty: "Elite",
    text: "¿Qué copia de seguridad guarda solo los cambios desde el último backup, sea completo o incremental?",
    options: ["Incremental", "Diferencial", "Completa sintética"],
    answer: 0,
    explanation: "El backup incremental toma como referencia el último backup realizado.",
    reference: "Tipos de backup"
  },
  {
    id: 18,
    section: "Active Directory",
    topic: "LDAP",
    difficulty: "Elite",
    text: "¿Qué protocolo se usa habitualmente para consultar y modificar información en directorios como Active Directory?",
    options: ["LDAP", "SNMP", "NTP"],
    answer: 0,
    explanation: "LDAP es el protocolo de acceso a servicios de directorio.",
    reference: "Active Directory"
  },
  {
    id: 19,
    section: "Active Directory",
    topic: "DNS",
    difficulty: "Elite",
    text: "¿Por qué DNS es crítico en un dominio Active Directory?",
    options: ["Permite localizar controladores de dominio y servicios", "Sustituye las GPO", "Cifra automáticamente las credenciales"],
    answer: 0,
    explanation: "AD depende de DNS para localizar servicios mediante registros como SRV.",
    reference: "AD DNS"
  },
  {
    id: 20,
    section: "Active Directory",
    topic: "GPO",
    difficulty: "Elite",
    text: "¿Para qué sirve principalmente una GPO?",
    options: ["Aplicar configuraciones centralizadas a usuarios o equipos", "Crear automáticamente subredes IP", "Replicar bases de datos SQL"],
    answer: 0,
    explanation: "Las directivas de grupo permiten administrar configuraciones de forma centralizada.",
    reference: "Group Policy"
  },
  {
    id: 21,
    section: "Active Directory",
    topic: "OU",
    difficulty: "Elite",
    text: "¿Qué ventaja aporta una Unidad Organizativa en Active Directory?",
    options: ["Organizar objetos y aplicar delegación o GPO", "Aumentar la velocidad del procesador", "Convertir usuarios locales en administradores globales"],
    answer: 0,
    explanation: "Las OU sirven para organizar objetos y aplicar administración delegada o políticas.",
    reference: "OU"
  },
  {
    id: 22,
    section: "Active Directory",
    topic: "Kerberos",
    difficulty: "Elite",
    text: "¿Qué función cumple Kerberos en Active Directory?",
    options: ["Autenticación mediante tickets", "Resolución de nombres NetBIOS", "Asignación dinámica de IP"],
    answer: 0,
    explanation: "Kerberos autentica usando tickets emitidos por el KDC.",
    reference: "Kerberos"
  },
  {
    id: 23,
    section: "TCP/IP",
    topic: "Subnetting",
    difficulty: "Elite",
    text: "En una red /24, ¿cuántas direcciones IP útiles para hosts hay normalmente?",
    options: ["254", "256", "255"],
    answer: 0,
    explanation: "Una /24 tiene 256 direcciones, pero se reservan red y broadcast.",
    reference: "IPv4"
  },
  {
    id: 24,
    section: "TCP/IP",
    topic: "Gateway",
    difficulty: "Elite",
    text: "¿Qué ocurre si un equipo tiene IP y máscara correctas, pero gateway incorrecto?",
    options: ["Podrá comunicarse localmente, pero fallará al salir a otras redes", "No podrá comunicarse con ningún equipo de su LAN", "No resolverá nombres DNS internos"],
    answer: 0,
    explanation: "El gateway se necesita para comunicar con redes externas.",
    reference: "Gateway"
  },
  {
    id: 25,
    section: "TCP/IP",
    topic: "ARP",
    difficulty: "Elite",
    text: "¿Qué resuelve ARP en una red IPv4 local?",
    options: ["IP a MAC", "Dominio a IP pública", "Puerto TCP a proceso"],
    answer: 0,
    explanation: "ARP permite conocer la dirección MAC asociada a una IP local.",
    reference: "ARP"
  },
  {
    id: 26,
    section: "TCP/IP",
    topic: "DNS",
    difficulty: "Elite",
    text: "¿Qué registro DNS se usa para indicar el servidor de correo de un dominio?",
    options: ["MX", "A", "PTR"],
    answer: 0,
    explanation: "MX indica los servidores de correo responsables del dominio.",
    reference: "DNS"
  },
  {
    id: 27,
    section: "TCP/IP",
    topic: "DHCP",
    difficulty: "Elite",
    text: "¿Cuál es el orden clásico del proceso DHCP?",
    options: ["Discover, Offer, Request, Acknowledge", "Request, Discover, Offer, Acknowledge", "Offer, Discover, Acknowledge, Request"],
    answer: 0,
    explanation: "El proceso DHCP se resume como DORA.",
    reference: "DHCP"
  },
  {
    id: 28,
    section: "TCP/IP",
    topic: "TCP vs UDP",
    difficulty: "Elite",
    text: "¿Qué característica diferencia principalmente TCP de UDP?",
    options: ["TCP es orientado a conexión", "UDP confirma todos los paquetes", "TCP no usa puertos"],
    answer: 0,
    explanation: "TCP establece conexión y controla entrega; UDP es no orientado a conexión.",
    reference: "TCP/UDP"
  },
  {
    id: 29,
    section: "TCP/IP",
    topic: "Puertos",
    difficulty: "Elite",
    text: "¿Qué combinación protocolo/puerto es correcta?",
    options: ["HTTPS TCP 443", "DNS TCP 25", "SMTP UDP 80"],
    answer: 0,
    explanation: "HTTPS usa normalmente TCP 443.",
    reference: "Puertos"
  },
  {
    id: 30,
    section: "TCP/IP",
    topic: "NAT",
    difficulty: "Elite",
    text: "¿Qué permite NAT en una red privada?",
    options: ["Que varios equipos compartan una IP pública", "Que desaparezca la necesidad de DNS", "Que todas las IP privadas sean públicas"],
    answer: 0,
    explanation: "NAT traduce direcciones privadas a una dirección pública.",
    reference: "NAT"
  },
  {
    id: 31,
    section: "Sistemas",
    topic: "Linux",
    difficulty: "Elite",
    text: "En permisos Linux, ¿qué significa permiso 755?",
    options: ["Propietario rwx, grupo r-x, otros r-x", "Propietario r-x, grupo rwx, otros rwx", "Todos rwx excepto propietario"],
    answer: 0,
    explanation: "7=rwx, 5=r-x, 5=r-x.",
    reference: "Permisos Linux"
  },
  {
    id: 32,
    section: "Sistemas",
    topic: "Procesos",
    difficulty: "Elite",
    text: "¿Qué diferencia básica hay entre proceso y servicio?",
    options: ["Un servicio suele ejecutarse en segundo plano ofreciendo una función", "Un proceso solo existe en Linux", "Un servicio no consume memoria"],
    answer: 0,
    explanation: "Un servicio es un proceso o conjunto de procesos orientado a prestar una función persistente.",
    reference: "Sistemas operativos"
  },
  {
    id: 33,
    section: "Sistemas",
    topic: "Windows",
    difficulty: "Elite",
    text: "¿Qué herramienta de Windows permite ver eventos del sistema, seguridad y aplicaciones?",
    options: ["Visor de eventos", "Administrador de discos", "Editor de registro"],
    answer: 0,
    explanation: "El Visor de eventos muestra registros del sistema.",
    reference: "Windows Server / Windows"
  },
  {
    id: 34,
    section: "Sistemas",
    topic: "Arranque",
    difficulty: "Elite",
    text: "¿Qué función cumple UEFI frente a BIOS clásica?",
    options: ["Inicializar hardware y arrancar el sistema con funciones modernas", "Sustituir al sistema operativo", "Gestionar usuarios de dominio"],
    answer: 0,
    explanation: "UEFI es firmware moderno de arranque con más capacidades que BIOS heredada.",
    reference: "Arranque"
  },
  {
    id: 35,
    section: "Sistemas",
    topic: "RAID",
    difficulty: "Elite",
    text: "¿Qué RAID ofrece espejo de datos entre dos discos?",
    options: ["RAID 1", "RAID 0", "RAID 5 sin paridad"],
    answer: 0,
    explanation: "RAID 1 replica la información en espejo.",
    reference: "RAID"
  },
  {
    id: 36,
    section: "Sistemas",
    topic: "Monitorización",
    difficulty: "Elite",
    text: "¿Qué protocolo se usa habitualmente para monitorizar dispositivos de red?",
    options: ["SNMP", "SMTP", "SMB"],
    answer: 0,
    explanation: "SNMP se usa para monitorización y gestión de dispositivos.",
    reference: "Monitorización"
  },
  {
    id: 37,
    section: "Redes",
    topic: "OSI",
    difficulty: "Elite",
    text: "¿En qué capa OSI trabaja principalmente un switch tradicional?",
    options: ["Capa 2", "Capa 3", "Capa 4"],
    answer: 0,
    explanation: "El switch tradicional trabaja con direcciones MAC en capa de enlace.",
    reference: "Modelo OSI"
  },
  {
    id: 38,
    section: "Redes",
    topic: "OSI",
    difficulty: "Elite",
    text: "¿Cuál es la PDU de la capa de red en OSI?",
    options: ["Paquete", "Trama", "Segmento"],
    answer: 0,
    explanation: "Red trabaja con paquetes; enlace con tramas; transporte con segmentos.",
    reference: "Modelo OSI"
  },
  {
    id: 39,
    section: "Redes",
    topic: "VLAN",
    difficulty: "Elite",
    text: "¿Qué consigue principalmente una VLAN?",
    options: ["Separar dominios de broadcast lógicos", "Aumentar automáticamente la velocidad física del cable", "Eliminar la necesidad de switches"],
    answer: 0,
    explanation: "Una VLAN segmenta la red en dominios lógicos.",
    reference: "VLAN"
  },
  {
    id: 40,
    section: "Redes",
    topic: "Wi-Fi",
    difficulty: "Elite",
    text: "¿Qué estándar de seguridad Wi-Fi es más recomendable frente a WEP?",
    options: ["WPA2 o WPA3", "Telnet", "HTTP"],
    answer: 0,
    explanation: "WEP está obsoleto; WPA2/WPA3 son opciones seguras modernas.",
    reference: "Seguridad Wi-Fi"
  },
  {
    id: 41,
    section: "Correo",
    topic: "Protocolos",
    difficulty: "Elite",
    text: "¿Qué protocolo se utiliza principalmente para enviar correo electrónico entre servidores?",
    options: ["SMTP", "IMAP", "POP3"],
    answer: 0,
    explanation: "SMTP se usa para envío de correo. IMAP y POP3 son de recepción/consulta.",
    reference: "Correo electrónico"
  },
  {
    id: 42,
    section: "Correo",
    topic: "IMAP vs POP3",
    difficulty: "Elite",
    text: "¿Qué ventaja típica tiene IMAP frente a POP3?",
    options: ["Mantiene el correo sincronizado en el servidor", "Cifra siempre todos los mensajes", "Solo funciona sin conexión"],
    answer: 0,
    explanation: "IMAP permite sincronización entre dispositivos manteniendo mensajes en servidor.",
    reference: "IMAP / POP3"
  },
  {
    id: 43,
    section: "Web",
    topic: "HTTP/HTTPS",
    difficulty: "Elite",
    text: "¿Qué aporta HTTPS frente a HTTP?",
    options: ["Cifrado mediante TLS", "Mayor tamaño de pantalla", "Conversión automática a IPv6"],
    answer: 0,
    explanation: "HTTPS usa TLS para proteger la comunicación.",
    reference: "HTTPS / TLS"
  },
  {
    id: 44,
    section: "Web",
    topic: "TLS",
    difficulty: "Elite",
    text: "¿Qué función cumple un certificado digital en HTTPS?",
    options: ["Ayuda a autenticar la identidad del servidor", "Comprime las páginas web", "Asigna direcciones IP dinámicas"],
    answer: 0,
    explanation: "El certificado permite validar la identidad del servidor y establecer confianza.",
    reference: "Certificados digitales"
  },
  {
    id: 45,
    section: "Sistemas",
    topic: "Backups",
    difficulty: "Elite",
    text: "¿Qué estrategia es más adecuada para recuperación ante desastre?",
    options: ["Copias periódicas probadas y almacenadas fuera del sistema principal", "Confiar solo en snapshots locales", "Guardar una copia en la misma carpeta"],
    answer: 0,
    explanation: "Un backup debe estar probado y protegido frente al fallo del sistema origen.",
    reference: "Backup y recuperación"
  },
  {
    id: 46,
    section: "Seguridad",
    topic: "Principio de mínimo privilegio",
    difficulty: "Elite",
    text: "¿Qué significa aplicar mínimo privilegio?",
    options: ["Dar solo los permisos necesarios para la tarea", "Hacer administrador local a todos los usuarios", "Bloquear todos los accesos externos"],
    answer: 0,
    explanation: "El usuario o proceso debe tener únicamente los permisos imprescindibles.",
    reference: "Seguridad lógica"
  },
  {
    id: 47,
    section: "Sistemas",
    topic: "Actualizaciones",
    difficulty: "Elite",
    text: "¿Cuál es el objetivo principal de la gestión de parches?",
    options: ["Corregir vulnerabilidades y errores conocidos", "Eliminar todos los logs", "Cambiar la IP del servidor"],
    answer: 0,
    explanation: "Los parches corrigen fallos de seguridad, estabilidad o funcionamiento.",
    reference: "Mantenimiento de sistemas"
  },
  {
    id: 48,
    section: "Redes",
    topic: "ICMP",
    difficulty: "Elite",
    text: "¿Qué protocolo utiliza habitualmente la herramienta ping?",
    options: ["ICMP", "TCP", "SMTP"],
    answer: 0,
    explanation: "Ping usa mensajes ICMP Echo Request y Echo Reply.",
    reference: "ICMP"
  },
  {
    id: 49,
    section: "Redes",
    topic: "MTU",
    difficulty: "Elite",
    text: "¿Qué indica la MTU en una red?",
    options: ["Tamaño máximo de unidad de transmisión", "Tiempo máximo de usuario", "Número máximo de routers"],
    answer: 0,
    explanation: "MTU define el tamaño máximo de paquete/trama que puede transmitirse sin fragmentación.",
    reference: "MTU"
  },
  {
    id: 50,
    section: "Sistemas",
    topic: "CPD",
    difficulty: "Elite",
    text: "¿Qué elemento es esencial para proteger la continuidad eléctrica de servidores en un CPD?",
    options: ["SAI/UPS", "Switch no gestionable", "Cable UTP categoría 5"],
    answer: 0,
    explanation: "Un SAI/UPS proporciona alimentación temporal y protección ante cortes eléctricos.",
    reference: "Infraestructura CPD"
  }
];