const questions = [
  {
    "id": 1,
    "section": "🔴 BLOQUE 13 — DESARROLLO WEB",
    "topic": "Front-end",
    "difficulty": "Fácil",
    "text": "En una aplicación web, ¿qué parte se ejecuta principalmente en el navegador del usuario?",
    "options": ["Front-end", "Back-end", "Base de datos"],
    "answer": 0,
    "explanation": "El front-end es la parte visible e interactiva de la aplicación que se ejecuta en el navegador mediante HTML, CSS y JavaScript.",
    "reference": "Bloque III.08 - Aplicaciones web: desarrollo web front-end"
  },
  {
    "id": 2,
    "section": "🔴 BLOQUE 13 — DESARROLLO WEB",
    "topic": "Back-end",
    "difficulty": "Fácil",
    "text": "¿Qué parte de una aplicación web suele encargarse de la lógica de negocio, acceso a datos y generación de respuestas?",
    "options": ["HTML", "Back-end", "CSS"],
    "answer": 1,
    "explanation": "El back-end se ejecuta en el servidor y gestiona lógica, autenticación, acceso a bases de datos y respuestas al cliente.",
    "reference": "Bloque III.08 - Desarrollo web en servidor"
  },
  {
    "id": 3,
    "section": "🔴 BLOQUE 13 — DESARROLLO WEB",
    "topic": "HTML",
    "difficulty": "Fácil",
    "text": "¿Cuál es la función principal de HTML en una página web?",
    "options": ["Definir la estructura y contenido", "Aplicar reglas de firewall", "Compilar código del servidor"],
    "answer": 0,
    "explanation": "HTML es un lenguaje de marcado usado para estructurar el contenido de una página web.",
    "reference": "Bloque III.08 - Lenguajes: HTML"
  },
  {
    "id": 4,
    "section": "🔴 BLOQUE 13 — DESARROLLO WEB",
    "topic": "CSS",
    "difficulty": "Fácil",
    "text": "En desarrollo web, ¿para qué se utiliza principalmente CSS?",
    "options": ["Para consultar bases de datos", "Para definir la presentación visual de una página", "Para cifrar la comunicación web"],
    "answer": 1,
    "explanation": "CSS define estilos visuales como colores, tamaños, márgenes, tipografías y diseño responsive.",
    "reference": "Bloque III.08 - Desarrollo web front-end"
  },
  {
    "id": 5,
    "section": "🔴 BLOQUE 13 — DESARROLLO WEB",
    "topic": "JavaScript",
    "difficulty": "Fácil",
    "text": "¿Qué lenguaje se usa habitualmente en el navegador para añadir comportamiento dinámico a una página web?",
    "options": ["SQL", "JavaScript", "XML"],
    "answer": 1,
    "explanation": "JavaScript permite manipular el DOM, validar formularios, hacer peticiones asíncronas y crear interacción en el cliente.",
    "reference": "Bloque III.08 - Navegadores y lenguajes de programación web. Lenguajes de script"
  },
  {
    "id": 6,
    "section": "🔴 BLOQUE 13 — DESARROLLO WEB",
    "topic": "DOM",
    "difficulty": "Media",
    "text": "¿Qué representa el DOM en una página web?",
    "options": ["Una copia de seguridad del sitio", "La representación en objetos del documento HTML o XML", "Un protocolo de transferencia de archivos"],
    "answer": 1,
    "explanation": "El DOM representa el documento como una estructura de nodos que puede ser leída y modificada por JavaScript.",
    "reference": "Bloque III.08 - Navegadores y lenguajes de programación web"
  },
  {
    "id": 7,
    "section": "🔴 BLOQUE 13 — DESARROLLO WEB",
    "topic": "HTML5",
    "difficulty": "Fácil",
    "text": "¿Qué indica la declaración <!DOCTYPE html> al inicio de una página?",
    "options": ["Que el documento usa HTML5", "Que el documento está cifrado", "Que el documento es una hoja de estilos"],
    "answer": 0,
    "explanation": "<!DOCTYPE html> informa al navegador de que debe interpretar el documento como HTML5.",
    "reference": "Bloque III.08 - HTML"
  },
  {
    "id": 8,
    "section": "🔴 BLOQUE 13 — DESARROLLO WEB",
    "topic": "HTML",
    "difficulty": "Fácil",
    "text": "¿Qué tipo de información se coloca normalmente dentro de la etiqueta <head>?",
    "options": ["Contenido visible principal", "Metadatos, título, enlaces a CSS y scripts", "Registros de la base de datos"],
    "answer": 1,
    "explanation": "El head contiene información del documento, como título, metadatos, enlaces a hojas de estilo y scripts.",
    "reference": "Bloque III.08 - HTML"
  },
  {
    "id": 9,
    "section": "🔴 BLOQUE 13 — DESARROLLO WEB",
    "topic": "HTML",
    "difficulty": "Fácil",
    "text": "¿Qué contiene normalmente la etiqueta <body> de un documento HTML?",
    "options": ["El contenido visible de la página", "Solo metadatos invisibles", "La configuración del servidor DNS"],
    "answer": 0,
    "explanation": "El body contiene los elementos visibles e interactivos que se muestran al usuario en la página.",
    "reference": "Bloque III.08 - HTML"
  },
  {
    "id": 10,
    "section": "🔴 BLOQUE 13 — DESARROLLO WEB",
    "topic": "HTML semántico",
    "difficulty": "Media",
    "text": "¿Cuál de los siguientes grupos contiene etiquetas semánticas de HTML5?",
    "options": ["<header>, <nav>, <main>, <footer>", "<font>, <center>, <blink>", "<table>, <tr>, <td>, <br>"],
    "answer": 0,
    "explanation": "Las etiquetas semánticas describen el significado de las zonas del documento, como cabecera, navegación, contenido principal y pie.",
    "reference": "Bloque III.08 - HTML"
  },
  {
    "id": 11,
    "section": "🔴 BLOQUE 13 — DESARROLLO WEB",
    "topic": "Formularios",
    "difficulty": "Media",
    "text": "En un formulario web, ¿qué característica describe mejor al método GET?",
    "options": ["Envía los datos en el cuerpo de la petición siempre cifrados", "Incluye los datos en la URL como parámetros", "Solo se puede usar con ficheros adjuntos"],
    "answer": 1,
    "explanation": "GET envía los datos como parámetros en la URL, por lo que es adecuado para consultas simples, no para información sensible.",
    "reference": "Bloque III.08 - Desarrollo web front-end y en servidor"
  },
  {
    "id": 12,
    "section": "🔴 BLOQUE 13 — DESARROLLO WEB",
    "topic": "Formularios",
    "difficulty": "Media",
    "text": "¿Qué método HTTP es más adecuado para enviar datos de un formulario de login?",
    "options": ["GET", "POST", "HEAD"],
    "answer": 1,
    "explanation": "POST envía los datos en el cuerpo de la petición y es más adecuado para formularios que modifican estado o contienen información sensible.",
    "reference": "Bloque III.08 - Desarrollo web en servidor"
  },
  {
    "id": 13,
    "section": "🔴 BLOQUE 13 — DESARROLLO WEB",
    "topic": "Responsive design",
    "difficulty": "Fácil",
    "text": "¿Qué significa que una web tenga diseño responsive?",
    "options": ["Que solo funciona en ordenadores de escritorio", "Que se adapta a distintos tamaños de pantalla y dispositivos", "Que no necesita navegador"],
    "answer": 1,
    "explanation": "Un diseño responsive adapta la presentación a móviles, tablets y pantallas de escritorio.",
    "reference": "Bloque III.08 - Multiplataforma y multidispositivo"
  },
  {
    "id": 14,
    "section": "🔴 BLOQUE 13 — DESARROLLO WEB",
    "topic": "Responsive design",
    "difficulty": "Media",
    "text": "¿Qué mecanismo de CSS permite aplicar estilos según el tamaño de pantalla o características del dispositivo?",
    "options": ["Media queries", "Triggers SQL", "Cookies de sesión"],
    "answer": 0,
    "explanation": "Las media queries permiten definir reglas CSS condicionadas por ancho de pantalla, orientación u otras características del dispositivo.",
    "reference": "Bloque III.08 - Multidispositivo"
  },
  {
    "id": 15,
    "section": "🔴 BLOQUE 13 — DESARROLLO WEB",
    "topic": "XML",
    "difficulty": "Fácil",
    "text": "¿Qué es XML?",
    "options": ["Un lenguaje extensible de marcado", "Un protocolo de correo electrónico", "Un sistema operativo web"],
    "answer": 0,
    "explanation": "XML es un lenguaje de marcado extensible utilizado para estructurar e intercambiar datos.",
    "reference": "Bloque III.08 - Lenguajes: XML y sus derivaciones"
  },
  {
    "id": 16,
    "section": "🔴 BLOQUE 13 — DESARROLLO WEB",
    "topic": "XML",
    "difficulty": "Media",
    "text": "¿Cuál es una regla básica para que un documento XML esté bien formado?",
    "options": ["Puede tener varias raíces principales", "Debe tener etiquetas correctamente anidadas y un único elemento raíz", "No puede contener atributos"],
    "answer": 1,
    "explanation": "Un XML bien formado tiene un único elemento raíz, etiquetas cerradas y correctamente anidadas.",
    "reference": "Bloque III.08 - XML"
  },
  {
    "id": 17,
    "section": "🔴 BLOQUE 13 — DESARROLLO WEB",
    "topic": "XHTML",
    "difficulty": "Media",
    "text": "¿Qué caracteriza principalmente a XHTML frente a HTML tradicional?",
    "options": ["Es una versión de HTML basada en reglas XML más estrictas", "Es un lenguaje exclusivo para bases de datos", "Es un protocolo de cifrado web"],
    "answer": 0,
    "explanation": "XHTML aplica reglas de XML a documentos HTML, por lo que exige una sintaxis más estricta.",
    "reference": "Bloque III.08 - XML y sus derivaciones"
  },
  {
    "id": 18,
    "section": "🔴 BLOQUE 13 — DESARROLLO WEB",
    "topic": "JSON/XML",
    "difficulty": "Media",
    "text": "En intercambio de datos web, ¿qué afirmación es correcta sobre JSON?",
    "options": ["Es un formato ligero basado en pares clave-valor", "Solo sirve para definir estilos visuales", "Sustituye al protocolo HTTPS"],
    "answer": 0,
    "explanation": "JSON es un formato ligero muy usado en APIs para representar datos mediante objetos, arrays y pares clave-valor.",
    "reference": "Bloque III.08 - Aplicaciones web y lenguajes web"
  },
  {
    "id": 19,
    "section": "🔴 BLOQUE 13 — DESARROLLO WEB",
    "topic": "Navegadores",
    "difficulty": "Fácil",
    "text": "¿Qué función realiza principalmente un navegador web?",
    "options": ["Interpretar HTML, CSS y JavaScript para mostrar páginas web", "Administrar exclusivamente bases de datos relacionales", "Sustituir al servidor web"],
    "answer": 0,
    "explanation": "El navegador solicita recursos al servidor, interpreta HTML, CSS y JavaScript y presenta la página al usuario.",
    "reference": "Bloque III.08 - Navegadores"
  },
  {
    "id": 20,
    "section": "🔴 BLOQUE 13 — DESARROLLO WEB",
    "topic": "Cliente-servidor",
    "difficulty": "Fácil",
    "text": "En arquitectura web, ¿qué papel cumple el cliente?",
    "options": ["Solicita recursos o servicios al servidor", "Guarda obligatoriamente toda la base de datos", "Ejecuta siempre el sistema operativo del servidor"],
    "answer": 0,
    "explanation": "El cliente, normalmente el navegador, envía peticiones al servidor y recibe respuestas.",
    "reference": "Bloque III.07/08 - Arquitectura cliente/servidor y aplicaciones web"
  },
  {
    "id": 21,
    "section": "🔴 BLOQUE 13 — DESARROLLO WEB",
    "topic": "Cliente-servidor",
    "difficulty": "Media",
    "text": "¿Qué diferencia general hay entre una página web estática y una dinámica?",
    "options": ["La estática cambia siempre según el usuario y la dinámica nunca cambia", "La dinámica puede generarse en función de datos, sesión o lógica de servidor", "La estática necesita obligatoriamente una base de datos"],
    "answer": 1,
    "explanation": "Una página dinámica puede variar su contenido según datos, usuario, sesión o lógica de aplicación.",
    "reference": "Bloque III.08 - Desarrollo web en servidor"
  },
  {
    "id": 22,
    "section": "🔴 BLOQUE 13 — DESARROLLO WEB",
    "topic": "HTTP",
    "difficulty": "Media",
    "text": "¿Qué significa que HTTP sea un protocolo sin estado?",
    "options": ["Que cada petición se trata de forma independiente", "Que solo funciona sin conexión a Internet", "Que no puede transportar HTML"],
    "answer": 0,
    "explanation": "HTTP no mantiene por sí mismo memoria de peticiones anteriores; las sesiones se gestionan con mecanismos adicionales como cookies o tokens.",
    "reference": "Bloque IV.08 - HTTP/HTTPS y servicios de Internet"
  },
  {
    "id": 23,
    "section": "🔴 BLOQUE 13 — DESARROLLO WEB",
    "topic": "HTTPS",
    "difficulty": "Fácil",
    "text": "¿Qué añade HTTPS respecto a HTTP?",
    "options": ["Cifrado y autenticación mediante TLS", "Conversión automática de XML a HTML", "Eliminación de todas las cookies"],
    "answer": 0,
    "explanation": "HTTPS utiliza TLS para proteger la confidencialidad e integridad de la comunicación y autenticar el servidor.",
    "reference": "Bloque IV.08 - HTTP, HTTPS y SSL/TLS"
  },
  {
    "id": 24,
    "section": "🔴 BLOQUE 13 — DESARROLLO WEB",
    "topic": "Cookies y sesiones",
    "difficulty": "Media",
    "text": "¿Para qué se utilizan habitualmente las cookies en aplicaciones web?",
    "options": ["Para almacenar información en el cliente, como identificadores de sesión o preferencias", "Para reemplazar al servidor DNS", "Para compilar código HTML"],
    "answer": 0,
    "explanation": "Las cookies son datos almacenados en el navegador que pueden enviarse al servidor, por ejemplo para mantener una sesión.",
    "reference": "Bloque III.08 - Aplicaciones web en cliente y servidor"
  },
  {
    "id": 25,
    "section": "🔴 BLOQUE 13 — DESARROLLO WEB",
    "topic": "Sesiones",
    "difficulty": "Media",
    "text": "En una aplicación web clásica, ¿dónde se almacena normalmente la información principal de una sesión de usuario?",
    "options": ["Solo en el fichero CSS", "En el servidor, asociada a un identificador de sesión", "En el registro MX del dominio"],
    "answer": 1,
    "explanation": "La sesión suele mantenerse en el servidor y el cliente conserva un identificador, normalmente mediante cookie.",
    "reference": "Bloque III.08 - Desarrollo web en servidor"
  },
  {
    "id": 26,
    "section": "🔴 BLOQUE 13 — DESARROLLO WEB",
    "topic": "APIs REST",
    "difficulty": "Media",
    "text": "En una API REST, ¿qué representan normalmente las URL o endpoints?",
    "options": ["Recursos sobre los que se realizan operaciones", "Colores definidos por CSS", "Puertos físicos del servidor"],
    "answer": 0,
    "explanation": "REST organiza la interacción alrededor de recursos identificados por URL y operados mediante métodos HTTP.",
    "reference": "Bloque III.07/08 - Servicios web y protocolos asociados"
  },
  {
    "id": 27,
    "section": "🔴 BLOQUE 13 — DESARROLLO WEB",
    "topic": "Métodos HTTP",
    "difficulty": "Media",
    "text": "¿Qué método HTTP se asocia principalmente a obtener información sin modificar el recurso?",
    "options": ["GET", "DELETE", "PATCH"],
    "answer": 0,
    "explanation": "GET se usa para solicitar recursos y, por diseño, no debería modificar el estado del servidor.",
    "reference": "Bloque IV.08 - HTTP"
  },
  {
    "id": 28,
    "section": "🔴 BLOQUE 13 — DESARROLLO WEB",
    "topic": "Métodos HTTP",
    "difficulty": "Media",
    "text": "¿Qué método HTTP se utiliza habitualmente para eliminar un recurso en una API REST?",
    "options": ["OPTIONS", "DELETE", "TRACE"],
    "answer": 1,
    "explanation": "DELETE se utiliza para solicitar la eliminación de un recurso identificado por la URL.",
    "reference": "Bloque III.07/08 - Servicios web y protocolos asociados"
  },
  {
    "id": 29,
    "section": "🔴 BLOQUE 13 — DESARROLLO WEB",
    "topic": "Códigos HTTP",
    "difficulty": "Fácil",
    "text": "¿Qué indica el código de estado HTTP 404?",
    "options": ["Recurso no encontrado", "Petición correcta", "Error interno del servidor"],
    "answer": 0,
    "explanation": "404 Not Found indica que el servidor no ha encontrado el recurso solicitado.",
    "reference": "Bloque IV.08 - HTTP"
  },
  {
    "id": 30,
    "section": "🔴 BLOQUE 13 — DESARROLLO WEB",
    "topic": "Códigos HTTP",
    "difficulty": "Fácil",
    "text": "¿Qué indica generalmente un código HTTP 500?",
    "options": ["Redirección permanente", "Error interno del servidor", "Recurso servido correctamente"],
    "answer": 1,
    "explanation": "Los códigos 5xx indican errores del servidor; 500 corresponde a un error interno genérico.",
    "reference": "Bloque IV.08 - HTTP"
  },
  {
    "id": 31,
    "section": "🔴 BLOQUE 13 — DESARROLLO WEB",
    "topic": "AJAX/fetch",
    "difficulty": "Media",
    "text": "¿Qué permite AJAX o fetch en una aplicación web?",
    "options": ["Hacer peticiones asíncronas al servidor sin recargar toda la página", "Sustituir físicamente la tarjeta de red", "Convertir automáticamente CSS en SQL"],
    "answer": 0,
    "explanation": "AJAX/fetch permite intercambiar datos con el servidor en segundo plano y actualizar partes de la página.",
    "reference": "Bloque III.08 - Lenguajes de script y aplicaciones web"
  },
  {
    "id": 32,
    "section": "🔴 BLOQUE 13 — DESARROLLO WEB",
    "topic": "CORS",
    "difficulty": "Difícil",
    "text": "¿Qué controla CORS en el entorno web?",
    "options": ["El acceso desde un origen web a recursos de otro origen", "La resolución de nombres DNS internos", "La compresión de imágenes JPEG"],
    "answer": 0,
    "explanation": "CORS permite o restringe peticiones entre orígenes distintos según las cabeceras configuradas por el servidor.",
    "reference": "Bloque III.08 - Seguridad básica en aplicaciones web"
  },
  {
    "id": 33,
    "section": "🔴 BLOQUE 13 — DESARROLLO WEB",
    "topic": "SPA",
    "difficulty": "Media",
    "text": "¿Qué caracteriza a una Single Page Application o SPA?",
    "options": ["Carga una página inicial y actualiza vistas principalmente en el cliente", "Solo puede mostrar una línea de texto", "No utiliza JavaScript"],
    "answer": 0,
    "explanation": "Una SPA suele cargar una aplicación en el navegador y cambia vistas mediante JavaScript sin recargas completas constantes.",
    "reference": "Bloque III.08 - Aplicaciones web front-end"
  },
  {
    "id": 34,
    "section": "🔴 BLOQUE 13 — DESARROLLO WEB",
    "topic": "SSR/CSR",
    "difficulty": "Difícil",
    "text": "¿Qué describe mejor el renderizado del lado del servidor o SSR?",
    "options": ["El servidor genera HTML que llega ya renderizado al navegador", "El navegador impide cualquier comunicación con el servidor", "La base de datos dibuja directamente la interfaz"],
    "answer": 0,
    "explanation": "En SSR, el servidor construye el HTML de la vista y lo envía al cliente para su visualización.",
    "reference": "Bloque III.08 - Desarrollo web en servidor"
  },
  {
    "id": 35,
    "section": "🔴 BLOQUE 13 — DESARROLLO WEB",
    "topic": "SSR/CSR",
    "difficulty": "Difícil",
    "text": "¿Qué describe mejor el renderizado del lado del cliente o CSR?",
    "options": ["El navegador genera o actualiza la interfaz mediante JavaScript", "El servidor no envía ningún archivo", "La página solo se muestra en modo texto"],
    "answer": 0,
    "explanation": "En CSR, gran parte de la construcción de la interfaz ocurre en el navegador usando JavaScript.",
    "reference": "Bloque III.08 - Desarrollo web front-end"
  },
  {
    "id": 36,
    "section": "🔴 BLOQUE 13 — DESARROLLO WEB",
    "topic": "Accesibilidad",
    "difficulty": "Fácil",
    "text": "¿Para qué sirve el atributo alt en una imagen HTML?",
    "options": ["Para aportar texto alternativo útil para accesibilidad y cuando la imagen no carga", "Para cifrar la imagen", "Para indicar el puerto HTTP"],
    "answer": 0,
    "explanation": "El atributo alt describe la imagen para lectores de pantalla y mejora la accesibilidad del contenido.",
    "reference": "Bloque III.09 - Accesibilidad, diseño universal y usabilidad"
  },
  {
    "id": 37,
    "section": "🔴 BLOQUE 13 — DESARROLLO WEB",
    "topic": "Usabilidad",
    "difficulty": "Fácil",
    "text": "¿Qué busca principalmente la usabilidad en una aplicación web?",
    "options": ["Que el usuario pueda utilizarla de forma eficaz, eficiente y satisfactoria", "Que el servidor no tenga sistema operativo", "Que todas las páginas pesen más"],
    "answer": 0,
    "explanation": "La usabilidad se centra en facilitar el uso, reducir errores y mejorar la experiencia del usuario.",
    "reference": "Bloque III.09 - Usabilidad"
  },
  {
    "id": 38,
    "section": "🔴 BLOQUE 13 — DESARROLLO WEB",
    "topic": "Seguridad web",
    "difficulty": "Media",
    "text": "¿Qué vulnerabilidad intenta aprovechar una inyección SQL?",
    "options": ["La construcción insegura de consultas a base de datos con entradas del usuario", "El exceso de etiquetas semánticas en HTML", "La falta de imágenes en una página"],
    "answer": 0,
    "explanation": "La inyección SQL ocurre cuando entradas no controladas alteran consultas SQL; se mitiga con consultas parametrizadas y validación.",
    "reference": "Bloque III.09 - Seguridad en el desarrollo de sistemas"
  },
  {
    "id": 39,
    "section": "🔴 BLOQUE 13 — DESARROLLO WEB",
    "topic": "Seguridad web",
    "difficulty": "Media",
    "text": "¿Qué es XSS en el contexto de aplicaciones web?",
    "options": ["La ejecución de scripts maliciosos inyectados en páginas vistas por usuarios", "Un tipo de cable de red", "Una técnica de normalización de bases de datos"],
    "answer": 0,
    "explanation": "XSS permite insertar código de script en páginas para que se ejecute en el navegador de otros usuarios.",
    "reference": "Bloque III.09 - Seguridad en el desarrollo de sistemas"
  },
  {
    "id": 40,
    "section": "🔴 BLOQUE 13 — DESARROLLO WEB",
    "topic": "Seguridad web",
    "difficulty": "Difícil",
    "text": "¿Qué medida ayuda a prevenir ataques CSRF en formularios o acciones autenticadas?",
    "options": ["Usar tokens CSRF únicos y validados por el servidor", "Eliminar todas las etiquetas <div>", "Cambiar HTML por XML siempre"],
    "answer": 0,
    "explanation": "Los tokens CSRF permiten comprobar que la petición procede de un formulario legítimo generado por la aplicación.",
    "reference": "Bloque III.09 - Seguridad en el desarrollo de sistemas"
  },
  {
    "id": 41,
    "section": "🔴 BLOQUE 13 — DESARROLLO WEB",
    "topic": "Validación",
    "difficulty": "Media",
    "text": "¿Dónde debe validarse siempre la entrada del usuario en una aplicación web?",
    "options": ["Solo en el navegador", "En el servidor, aunque también pueda validarse en cliente", "Solo en la hoja CSS"],
    "answer": 1,
    "explanation": "La validación en cliente mejora la experiencia, pero la validación de seguridad debe hacerse en servidor porque el cliente puede manipularse.",
    "reference": "Bloque III.09 - Seguridad en el desarrollo de sistemas"
  },
  {
    "id": 42,
    "section": "🔴 BLOQUE 13 — DESARROLLO WEB",
    "topic": "Almacenamiento web",
    "difficulty": "Media",
    "text": "¿Cuál es una diferencia habitual entre localStorage y sessionStorage?",
    "options": ["localStorage persiste más allá de la sesión del navegador; sessionStorage se limita a la sesión o pestaña", "sessionStorage se guarda siempre en el servidor", "localStorage solo admite imágenes"],
    "answer": 0,
    "explanation": "localStorage conserva datos de forma persistente en el navegador, mientras que sessionStorage se asocia a la sesión de la pestaña.",
    "reference": "Bloque III.08 - Aplicaciones web en cliente"
  },
  {
    "id": 43,
    "section": "🔴 BLOQUE 13 — DESARROLLO WEB",
    "topic": "Caché web",
    "difficulty": "Media",
    "text": "¿Para qué sirve la caché del navegador?",
    "options": ["Para almacenar recursos y acelerar cargas posteriores", "Para borrar automáticamente el servidor", "Para convertir HTTP en FTP"],
    "answer": 0,
    "explanation": "La caché puede guardar recursos como imágenes, CSS o JavaScript para evitar descargas repetidas y mejorar tiempos de carga.",
    "reference": "Bloque III.08 - Navegadores y aplicaciones web"
  },
  {
    "id": 44,
    "section": "🔴 BLOQUE 13 — DESARROLLO WEB",
    "topic": "CDN",
    "difficulty": "Media",
    "text": "¿Qué función cumple una CDN en un sitio web?",
    "options": ["Distribuir contenido estático desde servidores cercanos al usuario", "Sustituir el lenguaje HTML", "Eliminar la necesidad de DNS"],
    "answer": 0,
    "explanation": "Una CDN replica y entrega recursos desde ubicaciones distribuidas para reducir latencia y carga del servidor origen.",
    "reference": "Bloque III.08 - Aplicaciones web multidispositivo y servicios web"
  },
  {
    "id": 45,
    "section": "🔴 BLOQUE 13 — DESARROLLO WEB",
    "topic": "API",
    "difficulty": "Fácil",
    "text": "¿Qué es una API en el contexto de desarrollo web?",
    "options": ["Una interfaz que permite que aplicaciones se comuniquen entre sí", "Un tipo de monitor", "Un cable de fibra óptica"],
    "answer": 0,
    "explanation": "Una API define operaciones, datos y reglas para que un sistema pueda interactuar con otro.",
    "reference": "Bloque III.07/08 - Servicios web"
  },
  {
    "id": 46,
    "section": "🔴 BLOQUE 13 — DESARROLLO WEB",
    "topic": "MVC",
    "difficulty": "Media",
    "text": "¿Qué objetivo tiene el patrón MVC?",
    "options": ["Separar datos, interfaz y control de la aplicación", "Mezclar todo el código en un único archivo obligatoriamente", "Cifrar el tráfico de red"],
    "answer": 0,
    "explanation": "MVC separa Modelo, Vista y Controlador para mejorar organización, mantenimiento y reutilización del código.",
    "reference": "Bloque III.08/10 - Desarrollo web y metodologías"
  },
  {
    "id": 47,
    "section": "🔴 BLOQUE 13 — DESARROLLO WEB",
    "topic": "Servidor web",
    "difficulty": "Media",
    "text": "¿Cuál es la función básica de un servidor web?",
    "options": ["Atender peticiones HTTP/HTTPS y entregar recursos o respuestas web", "Diseñar automáticamente todas las páginas", "Sustituir a la tarjeta gráfica del cliente"],
    "answer": 0,
    "explanation": "Un servidor web recibe peticiones HTTP/HTTPS y devuelve páginas, archivos estáticos o respuestas generadas por la aplicación.",
    "reference": "Bloque III.07/08 - Arquitectura cliente/servidor y aplicaciones web"
  },
  {
    "id": 48,
    "section": "🔴 BLOQUE 13 — DESARROLLO WEB",
    "topic": "Servidor de aplicaciones",
    "difficulty": "Media",
    "text": "¿Qué diferencia general hay entre servidor web y servidor de aplicaciones?",
    "options": ["El servidor web atiende HTTP y contenido; el de aplicaciones ejecuta lógica de negocio", "El servidor de aplicaciones solo sirve imágenes", "No existe ninguna diferencia conceptual"],
    "answer": 0,
    "explanation": "Aunque pueden integrarse, el servidor web se centra en peticiones HTTP y el servidor de aplicaciones en ejecutar lógica de la aplicación.",
    "reference": "Bloque III.07 - Arquitectura cliente/servidor y multicapas"
  },
  {
    "id": 49,
    "section": "🔴 BLOQUE 13 — DESARROLLO WEB",
    "topic": "XML namespaces",
    "difficulty": "Difícil",
    "text": "¿Para qué sirven los espacios de nombres o namespaces en XML?",
    "options": ["Para evitar conflictos entre elementos o atributos con el mismo nombre", "Para aumentar el tamaño de las imágenes", "Para cambiar el puerto HTTPS"],
    "answer": 0,
    "explanation": "Los namespaces permiten distinguir elementos de diferentes vocabularios XML aunque tengan nombres iguales.",
    "reference": "Bloque III.08 - XML y sus derivaciones"
  },
  {
    "id": 50,
    "section": "🔴 BLOQUE 13 — DESARROLLO WEB",
    "topic": "Estándares web",
    "difficulty": "Media",
    "text": "¿Por qué son importantes los estándares web en HTML, CSS y APIs del navegador?",
    "options": ["Favorecen compatibilidad entre navegadores y dispositivos", "Impiden el uso de accesibilidad", "Obligan a usar solo aplicaciones de escritorio"],
    "answer": 0,
    "explanation": "Los estándares web facilitan que las páginas funcionen de forma consistente en distintos navegadores, plataformas y dispositivos.",
    "reference": "Bloque III.08 - Aplicaciones web multiplataforma y multidispositivo"
  }
]