const questions = [
  {
    id: 1,
    section: "Bloque 7 — Seguridad",
    topic: "Conceptos básicos",
    difficulty: "Fácil",
    text: "¿Qué objetivo de seguridad garantiza que la información solo sea accesible por usuarios autorizados?",
    options: ["Confidencialidad", "Integridad", "Disponibilidad"],
    answer: 0,
    explanation: "La confidencialidad evita accesos no autorizados a la información.",
    reference: "Seguridad de la información — Tríada CIA"
  },
  {
    id: 2,
    section: "Bloque 7 — Seguridad",
    topic: "Conceptos básicos",
    difficulty: "Fácil",
    text: "¿Qué objetivo de seguridad busca que los datos no sean alterados de forma no autorizada?",
    options: ["Disponibilidad", "Integridad", "Trazabilidad"],
    answer: 1,
    explanation: "La integridad asegura que la información se mantiene exacta y completa.",
    reference: "Seguridad de la información — Integridad"
  },
  {
    id: 3,
    section: "Bloque 7 — Seguridad",
    topic: "Conceptos básicos",
    difficulty: "Fácil",
    text: "¿Qué objetivo de seguridad se ve afectado principalmente por un ataque de denegación de servicio?",
    options: ["Confidencialidad", "Integridad", "Disponibilidad"],
    answer: 2,
    explanation: "Un ataque DoS o DDoS intenta impedir que un servicio esté disponible para sus usuarios legítimos.",
    reference: "Amenazas — DoS/DDoS"
  },
  {
    id: 4,
    section: "Bloque 7 — Seguridad",
    topic: "Riesgo",
    difficulty: "Media",
    text: "En seguridad informática, ¿qué es una vulnerabilidad?",
    options: ["Una debilidad que puede ser explotada", "Un ataque ya ejecutado con éxito", "La pérdida económica producida por un incidente"],
    answer: 0,
    explanation: "Una vulnerabilidad es una debilidad o fallo que puede ser aprovechado por una amenaza.",
    reference: "Amenazas y vulnerabilidades"
  },
  {
    id: 5,
    section: "Bloque 7 — Seguridad",
    topic: "Riesgo",
    difficulty: "Media",
    text: "¿Cuál es la relación más correcta entre amenaza, vulnerabilidad y riesgo?",
    options: ["El riesgo aparece cuando una amenaza puede explotar una vulnerabilidad", "La vulnerabilidad aparece cuando un riesgo explota una amenaza", "La amenaza es siempre el resultado de una vulnerabilidad"],
    answer: 0,
    explanation: "El riesgo depende de la posibilidad de que una amenaza aproveche una vulnerabilidad y cause impacto.",
    reference: "Gestión de riesgos"
  },
  {
    id: 6,
    section: "Bloque 7 — Seguridad",
    topic: "Malware",
    difficulty: "Fácil",
    text: "¿Qué tipo de malware cifra archivos y exige un pago para recuperarlos?",
    options: ["Spyware", "Ransomware", "Adware"],
    answer: 1,
    explanation: "El ransomware cifra o bloquea información y exige un rescate para restaurar el acceso.",
    reference: "Malware — Ransomware"
  },
  {
    id: 7,
    section: "Bloque 7 — Seguridad",
    topic: "Malware",
    difficulty: "Fácil",
    text: "¿Qué característica diferencia principalmente a un gusano de un virus clásico?",
    options: ["El gusano puede propagarse por sí mismo por la red", "El gusano no es malware", "El gusano solo afecta a documentos de texto"],
    answer: 0,
    explanation: "Un gusano puede autorreplicarse y propagarse sin necesidad de infectar manualmente un archivo huésped.",
    reference: "Malware — Gusanos"
  },
  {
    id: 8,
    section: "Bloque 7 — Seguridad",
    topic: "Malware",
    difficulty: "Fácil",
    text: "¿Qué tipo de malware se oculta simulando ser un programa legítimo?",
    options: ["Troyano", "Firewall", "Parche"],
    answer: 0,
    explanation: "Un troyano se presenta como software aparentemente legítimo para engañar al usuario.",
    reference: "Malware — Troyanos"
  },
  {
    id: 9,
    section: "Bloque 7 — Seguridad",
    topic: "Ingeniería social",
    difficulty: "Fácil",
    text: "¿Qué técnica consiste en engañar al usuario mediante mensajes fraudulentos para obtener credenciales?",
    options: ["Hardening", "Phishing", "Hashing"],
    answer: 1,
    explanation: "El phishing utiliza correos, webs o mensajes falsos para robar información sensible.",
    reference: "Ingeniería social — Phishing"
  },
  {
    id: 10,
    section: "Bloque 7 — Seguridad",
    topic: "Ingeniería social",
    difficulty: "Media",
    text: "¿Qué es el spear phishing?",
    options: ["Phishing dirigido a una persona u organización concreta", "Un ataque físico contra un CPD", "Una técnica de cifrado simétrico"],
    answer: 0,
    explanation: "El spear phishing es un phishing personalizado y dirigido, por lo que suele ser más creíble.",
    reference: "Ingeniería social — Spear phishing"
  },
  {
    id: 11,
    section: "Bloque 7 — Seguridad",
    topic: "Autenticación",
    difficulty: "Fácil",
    text: "¿Qué proceso comprueba la identidad de un usuario?",
    options: ["Autorización", "Autenticación", "Auditoría"],
    answer: 1,
    explanation: "La autenticación verifica quién es el usuario, normalmente mediante contraseña, certificado, token o biometría.",
    reference: "Control de acceso — Autenticación"
  },
  {
    id: 12,
    section: "Bloque 7 — Seguridad",
    topic: "Autorización",
    difficulty: "Fácil",
    text: "Una vez identificado un usuario, ¿qué proceso determina a qué recursos puede acceder?",
    options: ["Autorización", "Cifrado", "Disponibilidad"],
    answer: 0,
    explanation: "La autorización define permisos y privilegios sobre recursos después de la autenticación.",
    reference: "Control de acceso — Autorización"
  },
  {
    id: 13,
    section: "Bloque 7 — Seguridad",
    topic: "Control de acceso",
    difficulty: "Media",
    text: "¿Qué principio recomienda conceder a cada usuario solo los permisos imprescindibles para su trabajo?",
    options: ["Defensa en profundidad", "Mínimo privilegio", "No repudio"],
    answer: 1,
    explanation: "El principio de mínimo privilegio reduce el impacto de errores, abusos o cuentas comprometidas.",
    reference: "Control de acceso — Mínimo privilegio"
  },
  {
    id: 14,
    section: "Bloque 7 — Seguridad",
    topic: "Contraseñas",
    difficulty: "Fácil",
    text: "¿Cuál es una buena práctica para proteger contraseñas almacenadas?",
    options: ["Guardarlas en texto plano", "Guardarlas cifradas o mediante hash seguro con sal", "Enviarlas por correo al usuario"],
    answer: 1,
    explanation: "Las contraseñas no deben almacenarse en texto claro; se usan hashes seguros con sal para dificultar ataques.",
    reference: "Seguridad lógica — Contraseñas"
  },
  {
    id: 15,
    section: "Bloque 7 — Seguridad",
    topic: "MFA",
    difficulty: "Fácil",
    text: "¿Qué aporta la autenticación multifactor?",
    options: ["Usar varios factores de autenticación independientes", "Eliminar la necesidad de copias de seguridad", "Aumentar la velocidad de la red"],
    answer: 0,
    explanation: "MFA combina factores como algo que sabes, algo que tienes o algo que eres.",
    reference: "Control de acceso — MFA"
  },
  {
    id: 16,
    section: "Bloque 7 — Seguridad",
    topic: "Criptografía",
    difficulty: "Media",
    text: "¿Qué tipo de criptografía utiliza la misma clave para cifrar y descifrar?",
    options: ["Criptografía simétrica", "Criptografía asimétrica", "Firma digital"],
    answer: 0,
    explanation: "En la criptografía simétrica, emisor y receptor comparten la misma clave secreta.",
    reference: "Técnicas criptográficas — Cifrado simétrico"
  },
  {
    id: 17,
    section: "Bloque 7 — Seguridad",
    topic: "Criptografía",
    difficulty: "Media",
    text: "¿Qué tipo de criptografía utiliza un par de claves pública y privada?",
    options: ["Criptografía simétrica", "Criptografía asimétrica", "Compresión de datos"],
    answer: 1,
    explanation: "La criptografía asimétrica usa una clave pública y una clave privada relacionadas matemáticamente.",
    reference: "Técnicas criptográficas — Cifrado asimétrico"
  },
  {
    id: 18,
    section: "Bloque 7 — Seguridad",
    topic: "Criptografía",
    difficulty: "Media",
    text: "¿Cuál es una ventaja habitual del cifrado simétrico frente al asimétrico?",
    options: ["Suele ser más rápido", "No necesita claves", "Permite firmar documentos sin clave privada"],
    answer: 0,
    explanation: "El cifrado simétrico suele ser más eficiente y rápido para grandes volúmenes de datos.",
    reference: "Técnicas criptográficas — Cifrado simétrico"
  },
  {
    id: 19,
    section: "Bloque 7 — Seguridad",
    topic: "Hash",
    difficulty: "Media",
    text: "¿Para qué se usa principalmente una función hash criptográfica?",
    options: ["Para obtener una huella de longitud fija de unos datos", "Para comprimir imágenes sin pérdida", "Para asignar direcciones IP automáticamente"],
    answer: 0,
    explanation: "Un hash genera una huella o resumen que ayuda a verificar la integridad de los datos.",
    reference: "Técnicas criptográficas — Hash"
  },
  {
    id: 20,
    section: "Bloque 7 — Seguridad",
    topic: "Hash",
    difficulty: "Media",
    text: "¿Qué propiedad debe tener un buen hash criptográfico?",
    options: ["Debe ser fácilmente reversible", "Debe ser resistente a colisiones", "Debe cambiar la dirección MAC"],
    answer: 1,
    explanation: "La resistencia a colisiones dificulta que dos entradas distintas produzcan el mismo hash.",
    reference: "Técnicas criptográficas — Hash"
  },
  {
    id: 21,
    section: "Bloque 7 — Seguridad",
    topic: "Firma digital",
    difficulty: "Media",
    text: "¿Qué garantiza principalmente una firma digital?",
    options: ["Autenticidad, integridad y no repudio", "Mayor ancho de banda", "Asignación automática de IP"],
    answer: 0,
    explanation: "La firma digital permite verificar el firmante, detectar cambios y aportar no repudio.",
    reference: "Firma digital"
  },
  {
    id: 22,
    section: "Bloque 7 — Seguridad",
    topic: "Firma digital",
    difficulty: "Media",
    text: "Para crear una firma digital, ¿qué clave utiliza el firmante?",
    options: ["La clave pública del receptor", "Su clave privada", "La clave DNS del dominio"],
    answer: 1,
    explanation: "La firma se genera con la clave privada del firmante y se verifica con su clave pública.",
    reference: "Firma digital — Clave privada"
  },
  {
    id: 23,
    section: "Bloque 7 — Seguridad",
    topic: "Certificados digitales",
    difficulty: "Media",
    text: "¿Qué entidad emite y valida certificados digitales dentro de una PKI?",
    options: ["Autoridad de certificación", "Servidor DHCP", "Switch de acceso"],
    answer: 0,
    explanation: "La Autoridad de Certificación emite certificados que vinculan una identidad con una clave pública.",
    reference: "PKI — Autoridad de Certificación"
  },
  {
    id: 24,
    section: "Bloque 7 — Seguridad",
    topic: "Certificados digitales",
    difficulty: "Media",
    text: "¿Qué contiene normalmente un certificado digital?",
    options: ["Una clave pública asociada a una identidad", "La contraseña en texto plano del usuario", "La tabla ARP completa de la red"],
    answer: 0,
    explanation: "Un certificado digital vincula una identidad con una clave pública y está firmado por una CA.",
    reference: "PKI — Certificados digitales"
  },
  {
    id: 25,
    section: "Bloque 7 — Seguridad",
    topic: "TLS/HTTPS",
    difficulty: "Media",
    text: "¿Qué protocolo proporciona seguridad a HTTP para formar HTTPS?",
    options: ["TLS", "ICMP", "ARP"],
    answer: 0,
    explanation: "HTTPS es HTTP protegido mediante TLS, que cifra la comunicación y autentica el servidor.",
    reference: "Protocolos seguros — HTTPS y TLS"
  },
  {
    id: 26,
    section: "Bloque 7 — Seguridad",
    topic: "TLS/HTTPS",
    difficulty: "Media",
    text: "En una conexión HTTPS, ¿para qué sirve el certificado del servidor?",
    options: ["Para autenticar el servidor y facilitar el intercambio seguro de claves", "Para asignar una IP privada al cliente", "Para sustituir al firewall perimetral"],
    answer: 0,
    explanation: "El certificado permite comprobar la identidad del servidor y participar en el establecimiento seguro de la sesión.",
    reference: "Protocolos seguros — Certificados TLS"
  },
  {
    id: 27,
    section: "Bloque 7 — Seguridad",
    topic: "Protocolos seguros",
    difficulty: "Fácil",
    text: "¿Qué protocolo debe preferirse frente a Telnet para administración remota segura por consola?",
    options: ["SSH", "FTP", "SNMPv1"],
    answer: 0,
    explanation: "SSH cifra la sesión remota; Telnet transmite la información sin cifrado.",
    reference: "Acceso remoto seguro — SSH"
  },
  {
    id: 28,
    section: "Bloque 7 — Seguridad",
    topic: "Protocolos seguros",
    difficulty: "Fácil",
    text: "¿Qué protocolo seguro se usa habitualmente para transferir archivos sobre SSH?",
    options: ["SFTP", "TFTP", "POP3"],
    answer: 0,
    explanation: "SFTP proporciona transferencia de archivos segura usando SSH.",
    reference: "Protocolos seguros — SFTP"
  },
  {
    id: 29,
    section: "Bloque 7 — Seguridad",
    topic: "Firewall",
    difficulty: "Fácil",
    text: "¿Cuál es la función principal de un firewall?",
    options: ["Filtrar tráfico según reglas de seguridad", "Aumentar la memoria RAM", "Convertir direcciones MAC en nombres DNS"],
    answer: 0,
    explanation: "Un firewall permite o bloquea tráfico según reglas definidas por dirección, puerto, protocolo, estado u otros criterios.",
    reference: "Seguridad perimetral — Firewall"
  },
  {
    id: 30,
    section: "Bloque 7 — Seguridad",
    topic: "Firewall",
    difficulty: "Media",
    text: "¿Qué diferencia básica hay entre un firewall stateless y uno stateful?",
    options: ["El stateful tiene en cuenta el estado de las conexiones", "El stateless cifra siempre todo el tráfico", "El stateful solo funciona en redes Wi-Fi"],
    answer: 0,
    explanation: "Un firewall stateful analiza el estado de la conexión, no solo paquetes aislados.",
    reference: "Seguridad perimetral — Firewall stateful"
  },
  {
    id: 31,
    section: "Bloque 7 — Seguridad",
    topic: "IDS/IPS",
    difficulty: "Media",
    text: "¿Qué diferencia principal existe entre un IDS y un IPS?",
    options: ["El IDS detecta y alerta; el IPS puede bloquear o prevenir", "El IDS cifra y el IPS descifra", "El IDS asigna IP y el IPS resuelve nombres"],
    answer: 0,
    explanation: "Un IDS monitoriza y alerta; un IPS actúa en línea y puede bloquear tráfico malicioso.",
    reference: "Seguridad perimetral — IDS/IPS"
  },
  {
    id: 32,
    section: "Bloque 7 — Seguridad",
    topic: "DMZ",
    difficulty: "Media",
    text: "¿Para qué se utiliza una DMZ en una red empresarial?",
    options: ["Para aislar servicios expuestos a Internet de la red interna", "Para eliminar la necesidad de copias de seguridad", "Para sustituir al direccionamiento IP"],
    answer: 0,
    explanation: "Una DMZ aloja servicios públicos, como web o correo, separándolos de la LAN interna.",
    reference: "Seguridad perimetral — DMZ"
  },
  {
    id: 33,
    section: "Bloque 7 — Seguridad",
    topic: "VPN",
    difficulty: "Fácil",
    text: "¿Cuál es el objetivo principal de una VPN?",
    options: ["Crear un canal seguro sobre una red no confiable", "Formatear discos duros de forma remota", "Asignar direcciones MAC dinámicas"],
    answer: 0,
    explanation: "Una VPN permite comunicar usuarios o sedes mediante un túnel cifrado sobre Internet u otra red.",
    reference: "Acceso remoto seguro — VPN"
  },
  {
    id: 34,
    section: "Bloque 7 — Seguridad",
    topic: "VPN",
    difficulty: "Media",
    text: "¿Qué protocolo se asocia habitualmente a VPN de nivel de red?",
    options: ["IPsec", "SMTP", "DHCP"],
    answer: 0,
    explanation: "IPsec se usa para proteger comunicaciones IP y es habitual en VPN site-to-site o de acceso remoto.",
    reference: "VPN — IPsec"
  },
  {
    id: 35,
    section: "Bloque 7 — Seguridad",
    topic: "Seguridad Wi-Fi",
    difficulty: "Media",
    text: "¿Qué estándar de seguridad Wi-Fi es más recomendable frente a WEP?",
    options: ["WPA2 o WPA3", "FTP", "Telnet"],
    answer: 0,
    explanation: "WEP está obsoleto y es inseguro; WPA2 y WPA3 ofrecen mecanismos de protección más robustos.",
    reference: "Seguridad en redes inalámbricas"
  },
  {
    id: 36,
    section: "Bloque 7 — Seguridad",
    topic: "Seguridad Wi-Fi",
    difficulty: "Media",
    text: "¿Qué medida mejora la seguridad en una red Wi-Fi corporativa?",
    options: ["Usar WPA2/WPA3-Enterprise con autenticación 802.1X", "Usar siempre red abierta sin contraseña", "Publicar la clave Wi-Fi en la web corporativa"],
    answer: 0,
    explanation: "802.1X permite autenticación individual de usuarios o dispositivos, habitual en entornos corporativos.",
    reference: "Seguridad Wi-Fi — 802.1X"
  },
  {
    id: 37,
    section: "Bloque 7 — Seguridad",
    topic: "Hardening",
    difficulty: "Media",
    text: "¿Qué significa hacer hardening de un sistema?",
    options: ["Reducir su superficie de ataque mediante configuración segura", "Instalar cualquier software disponible", "Desactivar todas las copias de seguridad"],
    answer: 0,
    explanation: "El hardening consiste en reforzar la configuración: cerrar servicios innecesarios, aplicar parches y limitar permisos.",
    reference: "Seguridad lógica — Hardening"
  },
  {
    id: 38,
    section: "Bloque 7 — Seguridad",
    topic: "Parches",
    difficulty: "Fácil",
    text: "¿Por qué es importante aplicar actualizaciones de seguridad?",
    options: ["Porque corrigen vulnerabilidades conocidas", "Porque siempre aumentan el tamaño del disco", "Porque eliminan la necesidad de antivirus"],
    answer: 0,
    explanation: "Los parches de seguridad corrigen fallos que podrían ser explotados por atacantes.",
    reference: "Mantenimiento de seguridad — Parches"
  },
  {
    id: 39,
    section: "Bloque 7 — Seguridad",
    topic: "Antimalware",
    difficulty: "Fácil",
    text: "¿Cuál es la función principal de una solución antimalware?",
    options: ["Detectar, bloquear o eliminar software malicioso", "Asignar direcciones IP", "Crear VLAN automáticamente"],
    answer: 0,
    explanation: "El antimalware ayuda a detectar y contener virus, troyanos, ransomware, spyware y otras amenazas.",
    reference: "Seguridad en puesto de usuario — Antimalware"
  },
  {
    id: 40,
    section: "Bloque 7 — Seguridad",
    topic: "Copias de seguridad",
    difficulty: "Media",
    text: "Ante ransomware, ¿qué medida ayuda más a recuperar la información sin pagar un rescate?",
    options: ["Copias de seguridad probadas y aisladas", "Desactivar el firewall", "Usar contraseñas más cortas"],
    answer: 0,
    explanation: "Las copias de seguridad verificadas y protegidas permiten restaurar datos tras cifrado o destrucción.",
    reference: "Continuidad — Backups frente a ransomware"
  },
  {
    id: 41,
    section: "Bloque 7 — Seguridad",
    topic: "Seguridad física",
    difficulty: "Fácil",
    text: "¿Cuál es un ejemplo de medida de seguridad física?",
    options: ["Control de acceso con tarjeta a una sala de servidores", "Hash de contraseñas", "Filtro por puerto TCP"],
    answer: 0,
    explanation: "La seguridad física protege instalaciones, equipos y soportes frente a accesos o daños físicos.",
    reference: "Seguridad física"
  },
  {
    id: 42,
    section: "Bloque 7 — Seguridad",
    topic: "CPD",
    difficulty: "Media",
    text: "¿Qué elemento es propio del acondicionamiento de un CPD?",
    options: ["Climatización, alimentación eléctrica protegida y control de acceso", "Solo monitores de usuario", "Impresoras personales sin supervisión"],
    answer: 0,
    explanation: "Un CPD requiere control ambiental, suministro eléctrico protegido, seguridad física y sistemas contra incendios.",
    reference: "Infraestructura física de CPD"
  },
  {
    id: 43,
    section: "Bloque 7 — Seguridad",
    topic: "CPD",
    difficulty: "Media",
    text: "¿Qué sistema protege a los servidores ante cortes o microcortes eléctricos?",
    options: ["SAI/UPS", "Hub", "Monitor CRT"],
    answer: 0,
    explanation: "Un SAI o UPS proporciona alimentación temporal y estabilización ante problemas eléctricos.",
    reference: "CPD — Alimentación eléctrica"
  },
  {
    id: 44,
    section: "Bloque 7 — Seguridad",
    topic: "Incidentes",
    difficulty: "Media",
    text: "¿Cuál es el primer paso habitual en la gestión de una incidencia de seguridad?",
    options: ["Identificar y registrar la incidencia", "Borrar todos los logs", "Publicar contraseñas nuevas en abierto"],
    answer: 0,
    explanation: "Una incidencia debe identificarse, registrarse, clasificarse y escalarse según el procedimiento establecido.",
    reference: "Sistemas de gestión de incidencias"
  },
  {
    id: 45,
    section: "Bloque 7 — Seguridad",
    topic: "Logs y auditoría",
    difficulty: "Media",
    text: "¿Para qué sirven principalmente los logs de seguridad?",
    options: ["Para registrar eventos y facilitar auditoría e investigación", "Para sustituir al cifrado", "Para aumentar la resolución del monitor"],
    answer: 0,
    explanation: "Los logs permiten analizar accesos, errores, cambios, alertas y posibles incidentes.",
    reference: "Auditoría — Registros de eventos"
  },
  {
    id: 46,
    section: "Bloque 7 — Seguridad",
    topic: "Control remoto",
    difficulty: "Media",
    text: "¿Qué práctica mejora la seguridad en el control remoto de puestos de usuario?",
    options: ["Usar autenticación fuerte, cifrado y registro de sesiones", "Compartir una cuenta genérica sin contraseña", "Permitir acceso remoto abierto desde Internet"],
    answer: 0,
    explanation: "El control remoto debe estar autenticado, cifrado, limitado y auditado para reducir riesgos.",
    reference: "Control remoto de puestos de usuario"
  },
  {
    id: 47,
    section: "Bloque 7 — Seguridad",
    topic: "Segmentación",
    difficulty: "Media",
    text: "¿Qué ventaja de seguridad aporta segmentar una red en VLAN?",
    options: ["Limitar dominios de broadcast y aislar tráfico entre grupos", "Eliminar la necesidad de switches", "Cifrar automáticamente todos los paquetes"],
    answer: 0,
    explanation: "La segmentación permite separar usuarios, servicios o zonas, reduciendo exposición y movimiento lateral.",
    reference: "Seguridad en redes — Segmentación"
  },
  {
    id: 48,
    section: "Bloque 7 — Seguridad",
    topic: "DLP",
    difficulty: "Difícil",
    text: "¿Qué busca prevenir una solución DLP?",
    options: ["La fuga o pérdida de información sensible", "La fragmentación IP", "La asignación de direcciones DHCP"],
    answer: 0,
    explanation: "DLP significa Data Loss Prevention y ayuda a evitar exfiltración o uso indebido de datos sensibles.",
    reference: "Protección de la información — DLP"
  },
  {
    id: 49,
    section: "Bloque 7 — Seguridad",
    topic: "Ataques web",
    difficulty: "Difícil",
    text: "¿Qué ataque consiste en insertar código SQL malicioso en una entrada de una aplicación?",
    options: ["SQL Injection", "ARP Reply", "DNS Round Robin"],
    answer: 0,
    explanation: "La inyección SQL aprovecha entradas no validadas para alterar consultas a bases de datos.",
    reference: "Seguridad en aplicaciones — SQL Injection"
  },
  {
    id: 50,
    section: "Bloque 7 — Seguridad",
    topic: "Ataques web",
    difficulty: "Difícil",
    text: "¿Qué ataque web ejecuta scripts maliciosos en el navegador de la víctima?",
    options: ["XSS", "RAID 1", "NAT estático"],
    answer: 0,
    explanation: "XSS o Cross-Site Scripting permite inyectar scripts que se ejecutan en el navegador del usuario.",
    reference: "Seguridad en aplicaciones — XSS"
  }
];