questions = [
{
"id": 1,
"section": "Bloque 1 - Hardware",
"topic": "CPU",
"difficulty": "Fácil",
"text": "¿Qué componente se encarga principalmente de ejecutar las instrucciones de un programa?",
"options": ["CPU", "Fuente de alimentación", "Disco duro"],
"answer": 0,
"explanation": "La CPU es la unidad central de procesamiento y ejecuta las instrucciones de los programas.",
"reference": "Fundamentos de hardware - CPU y microprocesadores"
},
{
"id": 2,
"section": "Bloque 1 - Hardware",
"topic": "Memoria RAM",
"difficulty": "Fácil",
"text": "¿Qué característica principal tiene la memoria RAM?",
"options": ["Es volátil y pierde su contenido al apagar el equipo", "Es permanente y no se borra nunca", "Sirve exclusivamente para almacenar copias de seguridad"],
"answer": 0,
"explanation": "La RAM es memoria volátil: almacena datos temporales mientras el equipo está encendido.",
"reference": "Fundamentos de hardware - Memoria principal"
},
{
"id": 3,
"section": "Bloque 1 - Hardware",
"topic": "Almacenamiento",
"difficulty": "Fácil",
"text": "¿Cuál de estos dispositivos se utiliza como almacenamiento secundario?",
"options": ["SSD", "CPU", "Memoria caché L1"],
"answer": 0,
"explanation": "Un SSD es un dispositivo de almacenamiento secundario usado para guardar datos de forma persistente.",
"reference": "Fundamentos de hardware - Memorias secundarias"
},
{
"id": 4,
"section": "Bloque 1 - Hardware",
"topic": "Placa base",
"difficulty": "Fácil",
"text": "¿Cuál es la función principal de la placa base?",
"options": ["Conectar y permitir la comunicación entre los componentes del equipo", "Refrigerar exclusivamente el procesador", "Convertir corriente alterna en corriente continua"],
"answer": 0,
"explanation": "La placa base integra y conecta CPU, RAM, almacenamiento, tarjetas y otros componentes.",
"reference": "Fundamentos de hardware - Placa base"
},
{
"id": 5,
"section": "Bloque 1 - Hardware",
"topic": "Periféricos",
"difficulty": "Fácil",
"text": "¿Cuál de los siguientes es un periférico de entrada?",
"options": ["Teclado", "Monitor", "Altavoces"],
"answer": 0,
"explanation": "El teclado introduce información en el sistema, por eso es un periférico de entrada.",
"reference": "Fundamentos de hardware - Dispositivos periféricos"
},
{
"id": 6,
"section": "Bloque 1 - Hardware",
"topic": "Periféricos",
"difficulty": "Fácil",
"text": "¿Cuál de los siguientes es un periférico de salida?",
"options": ["Monitor", "Ratón", "Escáner"],
"answer": 0,
"explanation": "El monitor muestra información al usuario, por eso es un periférico de salida.",
"reference": "Fundamentos de hardware - Dispositivos periféricos"
},
{
"id": 7,
"section": "Bloque 1 - Hardware",
"topic": "BIOS/UEFI",
"difficulty": "Fácil",
"text": "¿Qué firmware se ejecuta al encender el ordenador para iniciar el hardware y arrancar el sistema?",
"options": ["BIOS/UEFI", "Driver de impresora", "Explorador de archivos"],
"answer": 0,
"explanation": "BIOS o UEFI inicializan el hardware y preparan el arranque del sistema operativo.",
"reference": "Fundamentos de hardware - Arranque y mantenimiento de equipos"
},
{
"id": 8,
"section": "Bloque 1 - Hardware",
"topic": "GPU",
"difficulty": "Fácil",
"text": "¿Qué componente está especializado en el procesamiento gráfico?",
"options": ["GPU", "Chip de sonido", "Fuente de alimentación"],
"answer": 0,
"explanation": "La GPU procesa gráficos, vídeo y tareas visuales, especialmente en 2D/3D.",
"reference": "Fundamentos de hardware - Tarjeta gráfica"
},
{
"id": 9,
"section": "Bloque 1 - Hardware",
"topic": "Fuente de alimentación",
"difficulty": "Fácil",
"text": "¿Qué componente suministra energía eléctrica a los elementos internos del PC?",
"options": ["Fuente de alimentación", "Disco NVMe", "Tarjeta de red"],
"answer": 0,
"explanation": "La fuente de alimentación convierte y distribuye la energía necesaria para el equipo.",
"reference": "Fundamentos de hardware - Montaje y mantenimiento hardware"
},
{
"id": 10,
"section": "Bloque 1 - Hardware",
"topic": "CPU",
"difficulty": "Fácil",
"text": "¿Cómo se llama normalmente el zócalo donde se instala el procesador en la placa base?",
"options": ["Socket", "Slot DIMM", "Puerto RJ45"],
"answer": 0,
"explanation": "El socket es el conector físico de la placa base donde se instala la CPU.",
"reference": "Fundamentos de hardware - CPU y placa base"
},
{
"id": 11,
"section": "Bloque 1 - Hardware",
"topic": "Memoria RAM",
"difficulty": "Fácil",
"text": "¿En qué tipo de ranura se instala habitualmente la memoria RAM de un PC de sobremesa?",
"options": ["DIMM", "PCIe x16", "SATA"],
"answer": 0,
"explanation": "Los módulos de memoria RAM de sobremesa suelen instalarse en ranuras DIMM.",
"reference": "Fundamentos de hardware - Memoria principal"
},
{
"id": 12,
"section": "Bloque 1 - Hardware",
"topic": "Almacenamiento",
"difficulty": "Fácil",
"text": "¿Qué tipo de disco no tiene partes mecánicas móviles?",
"options": ["SSD", "HDD", "Unidad de cinta magnética"],
"answer": 0,
"explanation": "Los SSD usan memoria flash y no tienen platos ni cabezales mecánicos.",
"reference": "Fundamentos de hardware - Memorias secundarias"
},
{
"id": 13,
"section": "Bloque 1 - Hardware",
"topic": "Puertos",
"difficulty": "Fácil",
"text": "¿Qué puerto se usa habitualmente para conectar memorias externas, teclados, ratones y otros periféricos?",
"options": ["USB", "Socket CPU", "DIMM"],
"answer": 0,
"explanation": "USB es un estándar común para conectar periféricos externos.",
"reference": "Fundamentos de hardware - Periféricos y conectividad"
},
{
"id": 14,
"section": "Bloque 1 - Hardware",
"topic": "Arranque",
"difficulty": "Fácil",
"text": "¿Qué componente almacena de forma permanente el sistema operativo y los datos del usuario?",
"options": ["Unidad de almacenamiento", "Memoria RAM", "Registro de la CPU"],
"answer": 0,
"explanation": "El sistema operativo y los datos se guardan en almacenamiento secundario como SSD o HDD.",
"reference": "Fundamentos de hardware - Arranque y memorias secundarias"
},
{
"id": 15,
"section": "Bloque 1 - Hardware",
"topic": "Mantenimiento",
"difficulty": "Fácil",
"text": "¿Qué acción básica ayuda a evitar sobrecalentamientos en un equipo?",
"options": ["Limpiar polvo de ventiladores y disipadores", "Desactivar la memoria RAM", "Formatear el teclado"],
"answer": 0,
"explanation": "El polvo dificulta la ventilación y puede provocar temperaturas elevadas.",
"reference": "Fundamentos de hardware - Prevención y mantenimiento hardware"
},
{
"id": 16,
"section": "Bloque 1 - Hardware",
"topic": "Tarjeta de red",
"difficulty": "Fácil",
"text": "¿Qué componente permite a un equipo conectarse a una red Ethernet?",
"options": ["Tarjeta de red", "Tarjeta gráfica", "Unidad óptica"],
"answer": 0,
"explanation": "La tarjeta de red o NIC permite la conexión del equipo a una red.",
"reference": "Fundamentos de hardware - Periféricos y conectividad"
},
{
"id": 17,
"section": "Bloque 1 - Hardware",
"topic": "Buses",
"difficulty": "Fácil",
"text": "¿Qué bus se utiliza actualmente para conectar tarjetas gráficas y otros dispositivos internos de alto rendimiento?",
"options": ["PCI Express", "PS/2", "RJ11"],
"answer": 0,
"explanation": "PCI Express es el bus interno estándar para tarjetas gráficas y dispositivos de alto rendimiento.",
"reference": "Fundamentos de hardware - Buses"
},
{
"id": 18,
"section": "Bloque 1 - Hardware",
"topic": "Portátiles",
"difficulty": "Fácil",
"text": "¿Qué componente diferencia claramente a un portátil de un equipo de sobremesa tradicional?",
"options": ["Batería integrada", "CPU", "Memoria RAM"],
"answer": 0,
"explanation": "Los portátiles integran batería para funcionar sin conexión permanente a la red eléctrica.",
"reference": "Fundamentos de hardware - Equipos portátiles"
},
{
"id": 19,
"section": "Bloque 1 - Hardware",
"topic": "Impresoras",
"difficulty": "Fácil",
"text": "¿Qué tipo de impresora utiliza tóner?",
"options": ["Láser", "Inyección de tinta", "Matricial"],
"answer": 0,
"explanation": "Las impresoras láser utilizan tóner, no cartuchos de tinta líquida.",
"reference": "Fundamentos de hardware - Elementos de impresión"
},
{
"id": 20,
"section": "Bloque 1 - Hardware",
"topic": "Monitor",
"difficulty": "Fácil",
"text": "¿Qué característica indica el número de píxeles que puede mostrar una pantalla?",
"options": ["Resolución", "Latencia de disco", "Velocidad del ventilador"],
"answer": 0,
"explanation": "La resolución expresa la cantidad de píxeles mostrados, por ejemplo 1920x1080.",
"reference": "Fundamentos de hardware - Elementos de visualización"
},
{
"id": 21,
"section": "Bloque 1 - Hardware",
"topic": "CPU",
"difficulty": "Media",
"text": "¿Qué memoria es más rápida y está integrada dentro o muy cerca del procesador?",
"options": ["Memoria caché", "Disco duro", "Memoria USB"],
"answer": 0,
"explanation": "La caché de CPU es muy rápida y almacena datos e instrucciones usados con frecuencia.",
"reference": "Fundamentos de hardware - CPU y memoria caché"
},
{
"id": 22,
"section": "Bloque 1 - Hardware",
"topic": "CPU",
"difficulty": "Media",
"text": "¿Qué indica la frecuencia de reloj de un procesador?",
"options": ["El número de ciclos que puede realizar por segundo", "La capacidad máxima del disco", "La cantidad de puertos USB disponibles"],
"answer": 0,
"explanation": "La frecuencia de reloj mide ciclos por segundo, habitualmente expresados en GHz.",
"reference": "Fundamentos de hardware - Microprocesadores"
},
{
"id": 23,
"section": "Bloque 1 - Hardware",
"topic": "Memoria RAM",
"difficulty": "Media",
"text": "¿Qué ventaja ofrece la configuración Dual Channel en memoria RAM?",
"options": ["Aumentar el ancho de banda de acceso a memoria", "Duplicar automáticamente la capacidad del disco", "Eliminar la necesidad de CPU"],
"answer": 0,
"explanation": "Dual Channel permite acceder a dos módulos de memoria en paralelo y mejora el ancho de banda.",
"reference": "Fundamentos de hardware - Memoria principal"
},
{
"id": 24,
"section": "Bloque 1 - Hardware",
"topic": "Almacenamiento",
"difficulty": "Media",
"text": "¿Qué interfaz es habitual en discos duros mecánicos y SSD de 2,5 pulgadas?",
"options": ["SATA", "DIMM", "LGA"],
"answer": 0,
"explanation": "SATA se usa comúnmente para conectar HDD y SSD de 2,5 pulgadas.",
"reference": "Fundamentos de hardware - Memorias secundarias"
},
{
"id": 25,
"section": "Bloque 1 - Hardware",
"topic": "Almacenamiento",
"difficulty": "Media",
"text": "¿Qué tecnología permite conectar unidades SSD de alto rendimiento directamente por PCI Express?",
"options": ["NVMe", "VGA", "PS/2"],
"answer": 0,
"explanation": "NVMe es un protocolo diseñado para SSD que aprovechan PCI Express.",
"reference": "Fundamentos de hardware - Dispositivos de almacenamiento"
},
{
"id": 26,
"section": "Bloque 1 - Hardware",
"topic": "BIOS/UEFI",
"difficulty": "Media",
"text": "¿Qué realiza el POST durante el arranque del equipo?",
"options": ["Comprueba el hardware básico antes de cargar el sistema operativo", "Instala automáticamente todas las aplicaciones", "Cifra el disco duro por defecto"],
"answer": 0,
"explanation": "El POST verifica componentes esenciales como CPU, RAM, vídeo y otros elementos básicos.",
"reference": "Fundamentos de hardware - Arranque de equipos"
},
{
"id": 27,
"section": "Bloque 1 - Hardware",
"topic": "Buses",
"difficulty": "Media",
"text": "¿Qué versión moderna sustituyó progresivamente a la BIOS tradicional en muchos equipos?",
"options": ["UEFI", "SATA", "USB 2.0"],
"answer": 0,
"explanation": "UEFI es el firmware moderno que sustituye a la BIOS clásica en muchos sistemas actuales.",
"reference": "Fundamentos de hardware - BIOS/UEFI"
},
{
"id": 28,
"section": "Bloque 1 - Hardware",
"topic": "GPU",
"difficulty": "Media",
"text": "¿Qué ranura de expansión suele utilizar una tarjeta gráfica dedicada moderna?",
"options": ["PCIe x16", "DIMM", "M.2 Key E"],
"answer": 0,
"explanation": "Las tarjetas gráficas dedicadas suelen instalarse en ranuras PCI Express x16.",
"reference": "Fundamentos de hardware - Tarjeta gráfica y buses"
},
{
"id": 29,
"section": "Bloque 1 - Hardware",
"topic": "Fuente de alimentación",
"difficulty": "Media",
"text": "¿Qué significa que una fuente tenga certificación 80 PLUS?",
"options": ["Que cumple un nivel mínimo de eficiencia energética", "Que siempre entrega exactamente 80 vatios", "Que solo funciona con monitores de 80 Hz"],
"answer": 0,
"explanation": "80 PLUS indica eficiencia energética mínima bajo determinadas cargas.",
"reference": "Fundamentos de hardware - Fuente de alimentación"
},
{
"id": 30,
"section": "Bloque 1 - Hardware",
"topic": "RAID",
"difficulty": "Media",
"text": "¿Qué objetivo principal tiene RAID 1?",
"options": ["Duplicar los datos en espejo para mejorar la tolerancia a fallos", "Sumar todos los discos sin redundancia", "Comprimir archivos automáticamente"],
"answer": 0,
"explanation": "RAID 1 crea un espejo de los datos en dos o más discos para mejorar disponibilidad.",
"reference": "Fundamentos de hardware - Almacenamiento y RAID"
},
{
"id": 31,
"section": "Bloque 1 - Hardware",
"topic": "RAID",
"difficulty": "Media",
"text": "¿Qué característica define mejor a RAID 0?",
"options": ["Distribuye datos entre discos para mejorar rendimiento, pero sin tolerancia a fallos", "Duplica datos para máxima redundancia", "Sustituye a las copias de seguridad"],
"answer": 0,
"explanation": "RAID 0 mejora rendimiento mediante striping, pero si falla un disco se pierde el conjunto.",
"reference": "Fundamentos de hardware - Almacenamiento y RAID"
},
{
"id": 32,
"section": "Bloque 1 - Hardware",
"topic": "Memoria",
"difficulty": "Media",
"text": "¿Qué función tiene la memoria virtual en un sistema?",
"options": ["Usar espacio de almacenamiento como extensión de la RAM", "Aumentar físicamente la memoria instalada", "Eliminar el uso del disco duro"],
"answer": 0,
"explanation": "La memoria virtual permite usar parte del almacenamiento como apoyo cuando falta RAM.",
"reference": "Fundamentos de hardware - Memoria principal"
},
{
"id": 33,
"section": "Bloque 1 - Hardware",
"topic": "Puertos",
"difficulty": "Media",
"text": "¿Qué conector se usa habitualmente para red Ethernet cableada?",
"options": ["RJ45", "HDMI", "Jack de 3,5 mm"],
"answer": 0,
"explanation": "RJ45 es el conector físico habitual en redes Ethernet sobre par trenzado.",
"reference": "Fundamentos de hardware - Periféricos y conectividad"
},
{
"id": 34,
"section": "Bloque 1 - Hardware",
"topic": "Vídeo",
"difficulty": "Media",
"text": "¿Cuál de estas interfaces transmite normalmente vídeo digital y audio?",
"options": ["HDMI", "VGA", "PS/2"],
"answer": 0,
"explanation": "HDMI transporta señal digital de vídeo y audio.",
"reference": "Fundamentos de hardware - Tarjeta gráfica y conectores"
},
{
"id": 35,
"section": "Bloque 1 - Hardware",
"topic": "Mantenimiento",
"difficulty": "Media",
"text": "¿Qué herramienta de diagnóstico permite conocer el estado de salud de un disco duro o SSD?",
"options": ["SMART", "POST", "HDMI"],
"answer": 0,
"explanation": "SMART recopila indicadores de salud y posibles fallos en unidades de almacenamiento.",
"reference": "Fundamentos de hardware - Mantenimiento de equipos"
},
{
"id": 36,
"section": "Bloque 1 - Hardware",
"topic": "Portátiles",
"difficulty": "Media",
"text": "¿Qué tipo de módulo RAM es habitual en muchos ordenadores portátiles?",
"options": ["SO-DIMM", "PCIe x16", "ATX"],
"answer": 0,
"explanation": "SO-DIMM es un formato compacto de memoria RAM usado en portátiles.",
"reference": "Fundamentos de hardware - Equipos portátiles"
},
{
"id": 37,
"section": "Bloque 1 - Hardware",
"topic": "Refrigeración",
"difficulty": "Media",
"text": "¿Para qué se utiliza la pasta térmica entre la CPU y el disipador?",
"options": ["Mejorar la transferencia de calor", "Aumentar la capacidad de la RAM", "Evitar que el disco se fragmente"],
"answer": 0,
"explanation": "La pasta térmica rellena imperfecciones y mejora la conducción del calor hacia el disipador.",
"reference": "Fundamentos de hardware - Montaje y mantenimiento hardware"
},
{
"id": 38,
"section": "Bloque 1 - Hardware",
"topic": "Arranque",
"difficulty": "Media",
"text": "¿Qué es el orden de arranque o boot order?",
"options": ["La secuencia de dispositivos desde los que el equipo intenta iniciar", "La velocidad máxima de la memoria RAM", "La cantidad de núcleos de la CPU"],
"answer": 0,
"explanation": "El boot order define si el equipo intenta arrancar desde SSD, USB, red, DVD, etc.",
"reference": "Fundamentos de hardware - Arranque de equipos"
},
{
"id": 39,
"section": "Bloque 1 - Hardware",
"topic": "Escáner",
"difficulty": "Media",
"text": "¿Qué periférico convierte documentos físicos en información digital?",
"options": ["Escáner", "Altavoz", "Proyector"],
"answer": 0,
"explanation": "El escáner digitaliza documentos o imágenes físicas.",
"reference": "Fundamentos de hardware - Elementos de visualización y digitalización"
},
{
"id": 40,
"section": "Bloque 1 - Hardware",
"topic": "Chipset",
"difficulty": "Media",
"text": "¿Qué función cumple el chipset en una placa base?",
"options": ["Coordinar la comunicación entre CPU, memoria, buses y otros componentes", "Imprimir documentos", "Almacenar permanentemente archivos personales"],
"answer": 0,
"explanation": "El chipset gestiona o coordina comunicaciones internas entre componentes de la placa.",
"reference": "Fundamentos de hardware - Placa base y buses"
},
{
"id": 41,
"section": "Bloque 1 - Hardware",
"topic": "CPU",
"difficulty": "Alta",
"text": "¿Qué elemento de la CPU realiza operaciones aritméticas y lógicas básicas?",
"options": ["ALU", "MMU", "BIOS"],
"answer": 0,
"explanation": "La ALU, unidad aritmético-lógica, ejecuta operaciones matemáticas y lógicas.",
"reference": "Fundamentos de hardware - Arquitectura de CPU"
},
{
"id": 42,
"section": "Bloque 1 - Hardware",
"topic": "CPU",
"difficulty": "Alta",
"text": "¿Qué unidad de la CPU se encarga de interpretar instrucciones y coordinar su ejecución?",
"options": ["Unidad de control", "Fuente de alimentación", "Tarjeta de sonido"],
"answer": 0,
"explanation": "La unidad de control interpreta instrucciones y coordina el funcionamiento interno de la CPU.",
"reference": "Fundamentos de hardware - Arquitectura de CPU"
},
{
"id": 43,
"section": "Bloque 1 - Hardware",
"topic": "CPU",
"difficulty": "Alta",
"text": "¿Qué diferencia básica hay entre un núcleo físico y un hilo de ejecución?",
"options": ["El núcleo es una unidad física de procesamiento; el hilo es una secuencia lógica de ejecución", "El hilo es siempre un disco externo; el núcleo es una impresora", "No existe ninguna diferencia en informática"],
"answer": 0,
"explanation": "Un núcleo es hardware real; un hilo representa una línea lógica de ejecución gestionada por el procesador o sistema.",
"reference": "Fundamentos de hardware - Microprocesadores"
},
{
"id": 44,
"section": "Bloque 1 - Hardware",
"topic": "Memoria",
"difficulty": "Alta",
"text": "¿Qué tipo de memoria caché suele ser la más pequeña y rápida dentro de la jerarquía de caché?",
"options": ["L1", "L3", "RAM"],
"answer": 0,
"explanation": "La caché L1 es normalmente la más cercana al núcleo, más pequeña y más rápida.",
"reference": "Fundamentos de hardware - Memoria caché"
},
{
"id": 45,
"section": "Bloque 1 - Hardware",
"topic": "Memoria",
"difficulty": "Alta",
"text": "¿Qué ocurre normalmente si se instala RAM con una frecuencia superior a la soportada por placa base o CPU?",
"options": ["Funcionará a una frecuencia compatible inferior o no será reconocida correctamente", "Siempre quemará la placa base", "Convertirá automáticamente el SSD en RAM"],
"answer": 0,
"explanation": "El sistema ajusta la memoria a parámetros compatibles o puede presentar incompatibilidad si no la soporta.",
"reference": "Fundamentos de hardware - Memoria principal"
},
{
"id": 46,
"section": "Bloque 1 - Hardware",
"topic": "UEFI",
"difficulty": "Alta",
"text": "¿Qué característica está asociada a UEFI frente a BIOS clásica?",
"options": ["Compatibilidad con arranque seguro y tablas de particiones GPT", "Uso exclusivo de discos IDE", "Imposibilidad de arrancar desde USB"],
"answer": 0,
"explanation": "UEFI se asocia a funciones modernas como Secure Boot y soporte de discos con GPT.",
"reference": "Fundamentos de hardware - BIOS/UEFI y arranque"
},
{
"id": 47,
"section": "Bloque 1 - Hardware",
"topic": "Almacenamiento",
"difficulty": "Alta",
"text": "¿Qué diferencia correcta hay entre M.2 y NVMe?",
"options": ["M.2 es un formato físico; NVMe es un protocolo de comunicación para SSD", "M.2 es un sistema operativo; NVMe es una impresora", "Ambos significan exactamente SATA"],
"answer": 0,
"explanation": "M.2 describe el formato/conector; NVMe describe el protocolo usado normalmente sobre PCIe.",
"reference": "Fundamentos de hardware - SSD, M.2 y NVMe"
},
{
"id": 48,
"section": "Bloque 1 - Hardware",
"topic": "Almacenamiento",
"difficulty": "Alta",
"text": "¿Por qué un SSD NVMe suele tener menor latencia y mayor rendimiento que un SSD SATA?",
"options": ["Porque usa PCI Express y un protocolo optimizado para memoria flash", "Porque utiliza platos magnéticos más rápidos", "Porque se conecta al puerto VGA"],
"answer": 0,
"explanation": "NVMe aprovecha PCIe y colas de comandos optimizadas para unidades flash modernas.",
"reference": "Fundamentos de hardware - Unidades SSD"
},
{
"id": 49,
"section": "Bloque 1 - Hardware",
"topic": "RAID",
"difficulty": "Alta",
"text": "¿Qué afirmación sobre RAID y copias de seguridad es correcta?",
"options": ["RAID mejora disponibilidad o rendimiento, pero no sustituye a una copia de seguridad", "RAID siempre protege contra borrados accidentales y ransomware", "RAID elimina la necesidad de restauración"],
"answer": 0,
"explanation": "RAID no protege frente a borrado lógico, corrupción, malware o errores humanos; sigue haciendo falta backup.",
"reference": "Fundamentos de hardware - Almacenamiento y RAID"
},
{
"id": 50,
"section": "Bloque 1 - Hardware",
"topic": "RAID",
"difficulty": "Alta",
"text": "En RAID 5, ¿qué mecanismo permite tolerar el fallo de un disco?",
"options": ["Paridad distribuida", "Duplicación completa de todos los discos", "Compresión de archivos"],
"answer": 0,
"explanation": "RAID 5 distribuye datos y paridad entre discos, permitiendo reconstruir la información si falla uno.",
"reference": "Fundamentos de hardware - RAID"
},
{
"id": 51,
"section": "Bloque 1 - Hardware",
"topic": "Buses",
"difficulty": "Alta",
"text": "¿Qué significa que una ranura PCIe sea x1, x4, x8 o x16?",
"options": ["El número de líneas o lanes PCIe disponibles", "La cantidad de ventiladores conectados", "El número de particiones del disco"],
"answer": 0,
"explanation": "PCIe usa lanes; más lanes permiten mayor ancho de banda potencial.",
"reference": "Fundamentos de hardware - Buses PCI Express"
},
{
"id": 52,
"section": "Bloque 1 - Hardware",
"topic": "USB",
"difficulty": "Alta",
"text": "¿Qué diferencia conceptual hay entre USB-A, USB-C y USB 3.2?",
"options": ["USB-A y USB-C son tipos de conector; USB 3.2 es una especificación de velocidad/protocolo", "Todos son modelos de tarjeta gráfica", "USB 3.2 es un tipo de pantalla"],
"answer": 0,
"explanation": "El conector físico no siempre indica la velocidad; USB 3.2 define características de transmisión.",
"reference": "Fundamentos de hardware - Conectividad de periféricos"
},
{
"id": 53,
"section": "Bloque 1 - Hardware",
"topic": "Mantenimiento",
"difficulty": "Alta",
"text": "Si un equipo emite pitidos al encender y no muestra imagen, ¿qué fase o mecanismo suele estar indicando un error de hardware?",
"options": ["POST", "Desfragmentación", "Actualización de navegador"],
"answer": 0,
"explanation": "Los pitidos durante el POST pueden indicar fallos de RAM, vídeo u otros componentes básicos.",
"reference": "Fundamentos de hardware - Diagnóstico de arranque"
},
{
"id": 54,
"section": "Bloque 1 - Hardware",
"topic": "Mantenimiento",
"difficulty": "Alta",
"text": "¿Qué medida es recomendable antes de manipular componentes internos para evitar daños por electricidad estática?",
"options": ["Descargarse a tierra o usar pulsera antiestática", "Encender y apagar el monitor varias veces", "Aumentar el brillo de la pantalla"],
"answer": 0,
"explanation": "La descarga electrostática puede dañar componentes sensibles; conviene usar medidas ESD.",
"reference": "Fundamentos de hardware - Prevención y montaje hardware"
},
{
"id": 55,
"section": "Bloque 1 - Hardware",
"topic": "Fuente de alimentación",
"difficulty": "Alta",
"text": "¿Qué rail de una fuente ATX alimenta principalmente CPU, GPU y otros componentes de alto consumo actuales?",
"options": ["12 V", "3,3 V", "5 VSB exclusivamente"],
"answer": 0,
"explanation": "En equipos modernos, la línea de 12 V es clave para CPU, GPU y dispositivos de alto consumo.",
"reference": "Fundamentos de hardware - Fuente de alimentación ATX"
},
{
"id": 56,
"section": "Bloque 1 - Hardware",
"topic": "Placa base",
"difficulty": "Alta",
"text": "¿Qué formato de placa base suele ser más grande que microATX y mini-ITX en equipos de sobremesa?",
"options": ["ATX", "SO-DIMM", "M.2"],
"answer": 0,
"explanation": "ATX es un formato de placa base de sobremesa más grande que microATX y mini-ITX.",
"reference": "Fundamentos de hardware - Placa base"
},
{
"id": 57,
"section": "Bloque 1 - Hardware",
"topic": "Impresoras",
"difficulty": "Alta",
"text": "¿Qué elemento de una impresora láser se encarga de fijar el tóner al papel mediante calor y presión?",
"options": ["Fusor", "Cabezal de inyección", "Sensor CMOS"],
"answer": 0,
"explanation": "El fusor calienta y presiona el tóner para adherirlo al papel.",
"reference": "Fundamentos de hardware - Elementos de impresión"
},
{
"id": 58,
"section": "Bloque 1 - Hardware",
"topic": "Pantallas",
"difficulty": "Alta",
"text": "¿Qué diferencia hay entre resolución y tasa de refresco en un monitor?",
"options": ["La resolución indica píxeles; la tasa de refresco indica cuántas veces por segundo se actualiza la imagen", "Ambas indican solo el tamaño físico en pulgadas", "La tasa de refresco mide la capacidad del disco"],
"answer": 0,
"explanation": "La resolución mide detalle en píxeles; la tasa de refresco se mide en Hz.",
"reference": "Fundamentos de hardware - Elementos de visualización"
},
{
"id": 59,
"section": "Bloque 1 - Hardware",
"topic": "Portátiles",
"difficulty": "Alta",
"text": "¿Qué problema puede provocar una batería de portátil hinchada?",
"options": ["Riesgo físico y daño interno; debe dejar de usarse y sustituirse con seguridad", "Aumento permanente del rendimiento del procesador", "Mejora automática de la refrigeración"],
"answer": 0,
"explanation": "Una batería hinchada puede ser peligrosa y dañar el equipo; no debe ignorarse.",
"reference": "Fundamentos de hardware - Equipos portátiles y mantenimiento"
},
{
"id": 60,
"section": "Bloque 1 - Hardware",
"topic": "CPU",
"difficulty": "Alta",
"text": "¿Qué tecnología permite que una CPU ejecute varios hilos lógicos por núcleo físico en determinados procesadores?",
"options": ["Multithreading simultáneo o Hyper-Threading", "RAID 0", "POST"],
"answer": 0,
"explanation": "SMT, conocido comercialmente como Hyper-Threading en Intel, permite varios hilos lógicos por núcleo físico.",
"reference": "Fundamentos de hardware - Microprocesadores"
}
]
