const questions = [
  {
    id: 1,
    section: "Redes / TCP-IP",
    topic: "Modelo OSI",
    difficulty: "media",
    text: "¿Cuál es la PDU propia de la capa de enlace de datos del modelo OSI?",
    options: ["Trama", "Paquete", "Segmento"],
    answer: 0,
    explanation: "En la capa 2, enlace de datos, la unidad de datos es la trama.",
    reference: "Modelo OSI - Capa 2"
  },
  {
    id: 2,
    section: "Redes / TCP-IP",
    topic: "TCP/IP",
    difficulty: "media",
    text: "¿Qué protocolo se utiliza habitualmente para resolver nombres de dominio en direcciones IP?",
    options: ["DHCP", "DNS", "ARP"],
    answer: 1,
    explanation: "DNS traduce nombres como www.ejemplo.com a direcciones IP.",
    reference: "Servicios de red"
  },
  {
    id: 3,
    section: "Redes / TCP-IP",
    topic: "ARP",
    difficulty: "alta",
    text: "¿Qué función realiza ARP en una red IPv4?",
    options: ["Asigna direcciones IP automáticamente", "Resuelve una dirección IP a una dirección MAC", "Cifra el tráfico entre redes"],
    answer: 1,
    explanation: "ARP permite conocer la MAC asociada a una IP dentro de la red local.",
    reference: "Protocolos TCP/IP"
  },
  {
    id: 4,
    section: "Redes / TCP-IP",
    topic: "Puertos",
    difficulty: "media",
    text: "¿Qué puerto utiliza HTTPS por defecto?",
    options: ["80", "443", "25"],
    answer: 1,
    explanation: "HTTPS utiliza TCP 443 por defecto.",
    reference: "HTTP/HTTPS"
  },
  {
    id: 5,
    section: "Redes / TCP-IP",
    topic: "Dispositivos de red",
    difficulty: "media",
    text: "¿Qué dispositivo opera principalmente en la capa 3 del modelo OSI?",
    options: ["Switch", "Hub", "Router"],
    answer: 2,
    explanation: "El router trabaja en capa de red y enruta paquetes entre redes.",
    reference: "Dispositivos de interconexión"
  },
  {
    id: 6,
    section: "Redes / TCP-IP",
    topic: "VLAN",
    difficulty: "alta",
    text: "¿Qué permite principalmente una VLAN?",
    options: ["Segmentar lógicamente una red física", "Aumentar la velocidad de la CPU", "Sustituir el direccionamiento IP"],
    answer: 0,
    explanation: "Una VLAN divide una red física en redes lógicas independientes.",
    reference: "Redes locales"
  },
  {
    id: 7,
    section: "Redes / TCP-IP",
    topic: "NAT",
    difficulty: "media",
    text: "¿Qué permite NAT en una red privada?",
    options: ["Que varios equipos compartan una IP pública", "Que el DNS funcione sin servidor", "Eliminar la necesidad de máscara de red"],
    answer: 0,
    explanation: "NAT traduce direcciones privadas a una o varias direcciones públicas.",
    reference: "Internet y TCP/IP"
  },
  {
    id: 8,
    section: "Redes / TCP-IP",
    topic: "IPv4",
    difficulty: "alta",
    text: "En una red 192.168.1.0/24, ¿cuál es la máscara de subred?",
    options: ["255.255.255.0", "255.255.0.0", "255.0.0.0"],
    answer: 0,
    explanation: "/24 equivale a 255.255.255.0.",
    reference: "Direccionamiento IPv4"
  },
  {
    id: 9,
    section: "Redes / TCP-IP",
    topic: "TCP vs UDP",
    difficulty: "media",
    text: "¿Qué característica corresponde a TCP?",
    options: ["No orientado a conexión", "Entrega fiable y control de errores", "No usa puertos"],
    answer: 1,
    explanation: "TCP es orientado a conexión y proporciona entrega fiable.",
    reference: "TCP/IP"
  },
  {
    id: 10,
    section: "Redes / TCP-IP",
    topic: "Medios de transmisión",
    difficulty: "media",
    text: "¿Qué medio utiliza pares de cobre trenzados?",
    options: ["UTP", "Fibra óptica", "Coaxial"],
    answer: 0,
    explanation: "El cable UTP está formado por pares trenzados de cobre.",
    reference: "Medios de transmisión"
  },
  {
    id: 11,
    section: "Redes / TCP-IP",
    topic: "ICMP",
    difficulty: "media",
    text: "¿Qué protocolo utiliza normalmente el comando ping?",
    options: ["ICMP", "SMTP", "FTP"],
    answer: 0,
    explanation: "Ping utiliza ICMP Echo Request y Echo Reply.",
    reference: "Protocolos TCP/IP"
  },
  {
    id: 12,
    section: "Redes / TCP-IP",
    topic: "DHCP",
    difficulty: "media",
    text: "¿Qué función realiza DHCP?",
    options: ["Asigna configuración IP automáticamente", "Cifra páginas web", "Convierte HTML en XML"],
    answer: 0,
    explanation: "DHCP asigna IP, máscara, puerta de enlace y DNS automáticamente.",
    reference: "Servicios de red"
  },
  {
    id: 13,
    section: "Sistemas Operativos",
    topic: "Procesos",
    difficulty: "media",
    text: "¿Qué es un proceso en un sistema operativo?",
    options: ["Un programa en ejecución", "Un tipo de memoria secundaria", "Una partición del disco"],
    answer: 0,
    explanation: "Un proceso es una instancia de un programa que se está ejecutando.",
    reference: "Sistemas operativos"
  },
  {
    id: 14,
    section: "Sistemas Operativos",
    topic: "Linux",
    difficulty: "media",
    text: "¿Qué comando de Linux muestra el contenido de un directorio?",
    options: ["cd", "ls", "pwd"],
    answer: 1,
    explanation: "ls lista archivos y directorios.",
    reference: "Linux básico"
  },
  {
    id: 15,
    section: "Sistemas Operativos",
    topic: "Permisos Linux",
    difficulty: "alta",
    text: "En permisos Linux, ¿qué significa el valor 7?",
    options: ["Lectura, escritura y ejecución", "Solo lectura y ejecución", "Solo escritura"],
    answer: 0,
    explanation: "7 equivale a 4+2+1: lectura, escritura y ejecución.",
    reference: "Administración Linux"
  },
  {
    id: 16,
    section: "Sistemas Operativos",
    topic: "Windows",
    difficulty: "media",
    text: "¿Qué herramienta de Windows permite ver procesos, rendimiento y aplicaciones en ejecución?",
    options: ["Administrador de tareas", "Editor del Registro", "Visor de eventos"],
    answer: 0,
    explanation: "El Administrador de tareas permite controlar procesos y rendimiento.",
    reference: "Windows"
  },
  {
    id: 17,
    section: "Sistemas Operativos",
    topic: "Arranque",
    difficulty: "alta",
    text: "¿Qué componente carga inicialmente el sistema operativo durante el arranque tradicional BIOS/MBR?",
    options: ["Bootloader", "Firewall", "Servidor DNS"],
    answer: 0,
    explanation: "El bootloader se encarga de iniciar la carga del sistema operativo.",
    reference: "Arranque de sistemas"
  },
  {
    id: 18,
    section: "Sistemas Operativos",
    topic: "Servicios",
    difficulty: "media",
    text: "¿Qué es un servicio del sistema operativo?",
    options: ["Un programa que se ejecuta en segundo plano", "Un tipo de archivo comprimido", "Una conexión física de red"],
    answer: 0,
    explanation: "Los servicios suelen ejecutarse en segundo plano para ofrecer funciones del sistema.",
    reference: "Administración SO"
  },
  {
    id: 19,
    section: "Sistemas Operativos",
    topic: "Sistema de archivos",
    difficulty: "media",
    text: "¿Cuál de los siguientes sistemas de archivos es propio de Windows moderno?",
    options: ["NTFS", "ext4", "HFS+"],
    answer: 0,
    explanation: "NTFS es el sistema de archivos habitual en Windows.",
    reference: "Sistemas de archivos"
  },
  {
    id: 20,
    section: "Hardware",
    topic: "CPU",
    difficulty: "media",
    text: "¿Qué componente ejecuta las instrucciones principales de un ordenador?",
    options: ["CPU", "Fuente de alimentación", "Disco duro"],
    answer: 0,
    explanation: "La CPU procesa instrucciones y coordina operaciones del sistema.",
    reference: "Fundamentos de hardware"
  },
  {
    id: 21,
    section: "Hardware",
    topic: "Memoria",
    difficulty: "media",
    text: "¿Qué característica define a la memoria RAM?",
    options: ["Es volátil", "Es siempre óptica", "No permite escritura"],
    answer: 0,
    explanation: "La RAM pierde su contenido al apagar el equipo.",
    reference: "Memoria principal"
  },
  {
    id: 22,
    section: "Hardware",
    topic: "Almacenamiento",
    difficulty: "media",
    text: "¿Qué tecnología permite conectar SSD de alto rendimiento directamente por PCI Express?",
    options: ["NVMe", "VGA", "SATA I exclusivamente"],
    answer: 0,
    explanation: "NVMe aprovecha PCI Express para SSD de alto rendimiento.",
    reference: "Dispositivos de almacenamiento"
  },
  {
    id: 23,
    section: "Hardware",
    topic: "Buses",
    difficulty: "media",
    text: "¿Qué bus se utiliza habitualmente para tarjetas gráficas modernas?",
    options: ["PCI Express", "IDE", "PS/2"],
    answer: 0,
    explanation: "PCI Express es el bus habitual para tarjetas gráficas actuales.",
    reference: "Placa base y buses"
  },
  {
    id: 24,
    section: "Hardware",
    topic: "BIOS/UEFI",
    difficulty: "alta",
    text: "¿Qué función cumple UEFI en un equipo?",
    options: ["Inicializa hardware y facilita el arranque del sistema", "Gestiona consultas SQL", "Cifra todo el tráfico HTTPS"],
    answer: 0,
    explanation: "UEFI sustituye o complementa BIOS y participa en el arranque del sistema.",
    reference: "Arranque y mantenimiento"
  },
  {
    id: 25,
    section: "Seguridad",
    topic: "Criptografía",
    difficulty: "media",
    text: "¿Qué tipo de criptografía utiliza una clave pública y una clave privada?",
    options: ["Simétrica", "Asimétrica", "Hash simple"],
    answer: 1,
    explanation: "La criptografía asimétrica usa un par de claves: pública y privada.",
    reference: "Seguridad lógica"
  },
  {
    id: 26,
    section: "Seguridad",
    topic: "Malware",
    difficulty: "media",
    text: "¿Qué es el ransomware?",
    options: ["Malware que cifra datos y exige rescate", "Un sistema de backup incremental", "Un protocolo de correo"],
    answer: 0,
    explanation: "El ransomware bloquea o cifra información para pedir un rescate.",
    reference: "Amenazas"
  },
  {
    id: 27,
    section: "Seguridad",
    topic: "Firma digital",
    difficulty: "alta",
    text: "¿Qué garantiza principalmente una firma digital?",
    options: ["Autenticidad e integridad", "Mayor velocidad de red", "Compresión de archivos"],
    answer: 0,
    explanation: "La firma digital permite verificar autoría e integridad del documento.",
    reference: "Firma digital"
  },
  {
    id: 28,
    section: "Seguridad",
    topic: "VPN",
    difficulty: "media",
    text: "¿Para qué se utiliza una VPN?",
    options: ["Para crear un túnel seguro sobre una red pública", "Para aumentar la RAM", "Para sustituir el sistema operativo"],
    answer: 0,
    explanation: "Una VPN permite comunicaciones seguras a través de redes no confiables.",
    reference: "Seguridad en redes"
  },
  {
    id: 29,
    section: "Seguridad",
    topic: "Firewall",
    difficulty: "media",
    text: "¿Cuál es la función principal de un firewall?",
    options: ["Filtrar tráfico de red según reglas", "Convertir imágenes a PDF", "Asignar direcciones MAC"],
    answer: 0,
    explanation: "El firewall controla el tráfico permitido o bloqueado.",
    reference: "Seguridad perimetral"
  },
  {
    id: 30,
    section: "Seguridad",
    topic: "Hash",
    difficulty: "alta",
    text: "¿Qué propiedad debe tener una función hash criptográfica?",
    options: ["Ser difícil de invertir", "Permitir recuperar siempre el texto original", "Usar siempre la misma clave privada"],
    answer: 0,
    explanation: "Un hash criptográfico debe ser unidireccional y resistente a colisiones.",
    reference: "Criptografía"
  },
  {
    id: 31,
    section: "Seguridad",
    topic: "Disponibilidad",
    difficulty: "media",
    text: "En seguridad de la información, ¿qué busca la disponibilidad?",
    options: ["Que la información esté accesible cuando se necesite", "Que todos los usuarios tengan permisos de administrador", "Que los datos estén siempre comprimidos"],
    answer: 0,
    explanation: "La disponibilidad garantiza acceso a los sistemas y datos cuando son necesarios.",
    reference: "CIA"
  },
  {
    id: 32,
    section: "Active Directory / Virtualización",
    topic: "Active Directory",
    difficulty: "media",
    text: "¿Qué permite Active Directory en una red Windows?",
    options: ["Gestionar usuarios, equipos y políticas de forma centralizada", "Crear únicamente páginas HTML", "Eliminar la necesidad de DNS"],
    answer: 0,
    explanation: "Active Directory centraliza identidades, equipos, permisos y políticas.",
    reference: "Administración de sistemas"
  },
  {
    id: 33,
    section: "Active Directory / Virtualización",
    topic: "GPO",
    difficulty: "alta",
    text: "¿Qué es una GPO en Active Directory?",
    options: ["Una directiva de grupo", "Un tipo de disco SSD", "Un protocolo de correo"],
    answer: 0,
    explanation: "Las GPO aplican configuraciones y restricciones a usuarios o equipos.",
    reference: "Active Directory"
  },
  {
    id: 34,
    section: "Active Directory / Virtualización",
    topic: "Virtualización",
    difficulty: "media",
    text: "¿Qué es un hipervisor?",
    options: ["Software que permite ejecutar máquinas virtuales", "Un gestor de bases de datos", "Un tipo de malware"],
    answer: 0,
    explanation: "El hipervisor gestiona la ejecución de máquinas virtuales sobre hardware físico.",
    reference: "Virtualización"
  },
  {
    id: 35,
    section: "Active Directory / Virtualización",
    topic: "Snapshots",
    difficulty: "alta",
    text: "¿Qué es un snapshot de una máquina virtual?",
    options: ["Una copia del estado de la VM en un momento concreto", "Un backup externo completo garantizado", "Un protocolo de acceso remoto"],
    answer: 0,
    explanation: "Un snapshot captura el estado de la VM, pero no sustituye a una política de backup.",
    reference: "Virtualización y backup"
  },
  {
    id: 36,
    section: "Active Directory / Virtualización",
    topic: "Contenedores",
    difficulty: "media",
    text: "¿Qué caracteriza a un contenedor frente a una máquina virtual tradicional?",
    options: ["Comparte el kernel del sistema anfitrión", "Siempre necesita BIOS propia", "Emula hardware completo obligatoriamente"],
    answer: 0,
    explanation: "Los contenedores aíslan aplicaciones compartiendo el kernel del host.",
    reference: "Contenedores"
  },
  {
    id: 37,
    section: "Bases de Datos",
    topic: "SQL",
    difficulty: "media",
    text: "¿Qué sentencia SQL se utiliza para consultar datos?",
    options: ["SELECT", "DELETE", "DROP"],
    answer: 0,
    explanation: "SELECT permite recuperar datos de una o varias tablas.",
    reference: "SQL básico"
  },
  {
    id: 38,
    section: "Bases de Datos",
    topic: "Modelo relacional",
    difficulty: "media",
    text: "¿Qué identifica de forma única un registro en una tabla relacional?",
    options: ["Clave primaria", "Clave foránea", "Índice secundario siempre obligatorio"],
    answer: 0,
    explanation: "La clave primaria identifica de forma única cada fila.",
    reference: "Modelo relacional"
  },
  {
    id: 39,
    section: "Bases de Datos",
    topic: "Normalización",
    difficulty: "alta",
    text: "¿Cuál es uno de los objetivos principales de la normalización?",
    options: ["Reducir redundancias y anomalías", "Duplicar todos los datos", "Eliminar claves primarias"],
    answer: 0,
    explanation: "La normalización organiza los datos para reducir redundancias e inconsistencias.",
    reference: "Diseño de bases de datos"
  },
  {
    id: 40,
    section: "Bases de Datos",
    topic: "NoSQL",
    difficulty: "media",
    text: "¿Cuál de las siguientes opciones corresponde a una base de datos NoSQL documental?",
    options: ["MongoDB", "MySQL", "PostgreSQL"],
    answer: 0,
    explanation: "MongoDB es una base de datos documental NoSQL.",
    reference: "Bases de datos NoSQL"
  },
  {
    id: 41,
    section: "Bases de Datos",
    topic: "Transacciones",
    difficulty: "alta",
    text: "¿Qué propiedad ACID garantiza que una transacción se realiza por completo o no se realiza?",
    options: ["Atomicidad", "Disponibilidad", "Herencia"],
    answer: 0,
    explanation: "La atomicidad asegura que una transacción sea todo o nada.",
    reference: "SGBD"
  },
  {
    id: 42,
    section: "Programación / Web",
    topic: "Programación",
    difficulty: "media",
    text: "¿Qué estructura permite repetir instrucciones mientras se cumple una condición?",
    options: ["Bucle", "Variable", "Comentario"],
    answer: 0,
    explanation: "Los bucles permiten repetir bloques de código.",
    reference: "Lenguajes de programación"
  },
  {
    id: 43,
    section: "Programación / Web",
    topic: "Funciones",
    difficulty: "media",
    text: "¿Qué es una función en programación?",
    options: ["Un bloque reutilizable de código", "Un tipo de cable de red", "Una tabla de base de datos obligatoria"],
    answer: 0,
    explanation: "Una función agrupa instrucciones reutilizables y puede recibir parámetros.",
    reference: "Programación básica"
  },
  {
    id: 44,
    section: "Programación / Web",
    topic: "HTML",
    difficulty: "media",
    text: "¿Para qué se utiliza HTML?",
    options: ["Para estructurar contenido web", "Para enrutar paquetes IP", "Para cifrar discos duros"],
    answer: 0,
    explanation: "HTML define la estructura de una página web.",
    reference: "Desarrollo web"
  },
  {
    id: 45,
    section: "Programación / Web",
    topic: "CSS",
    difficulty: "media",
    text: "¿Qué función cumple CSS en una página web?",
    options: ["Definir presentación y estilos", "Administrar usuarios de dominio", "Asignar direcciones IP"],
    answer: 0,
    explanation: "CSS controla estilos visuales como colores, tamaños y disposición.",
    reference: "Front-end"
  },
  {
    id: 46,
    section: "Programación / Web",
    topic: "HTTP",
    difficulty: "alta",
    text: "¿Qué código HTTP indica que un recurso no se ha encontrado?",
    options: ["404", "200", "301"],
    answer: 0,
    explanation: "404 Not Found indica que el recurso solicitado no existe o no está disponible.",
    reference: "HTTP"
  },
  {
    id: 47,
    section: "Programación / Web",
    topic: "Git",
    difficulty: "media",
    text: "¿Para qué se utiliza Git?",
    options: ["Control de versiones", "Monitorización eléctrica", "Resolución DNS"],
    answer: 0,
    explanation: "Git permite gestionar versiones del código fuente.",
    reference: "Control de versiones"
  },
  {
    id: 48,
    section: "Legislación",
    topic: "Protección de datos",
    difficulty: "media",
    text: "¿Qué norma española regula la protección de datos personales y garantía de derechos digitales?",
    options: ["Ley Orgánica 3/2018", "Ley Orgánica 1/2004", "Ley 31/1995"],
    answer: 0,
    explanation: "La LOPDGDD es la Ley Orgánica 3/2018.",
    reference: "LO 3/2018"
  },
  {
    id: 49,
    section: "Legislación",
    topic: "Igualdad",
    difficulty: "media",
    text: "¿Qué ley regula la igualdad efectiva de mujeres y hombres?",
    options: ["Ley Orgánica 3/2007", "Ley Orgánica 3/2018", "Ley Orgánica 10/1995"],
    answer: 0,
    explanation: "La Ley Orgánica 3/2007 regula la igualdad efectiva de mujeres y hombres.",
    reference: "LO 3/2007"
  },
  {
    id: 50,
    section: "Redes / TCP-IP",
    topic: "Correo electrónico",
    difficulty: "alta",
    text: "¿Qué protocolo se utiliza normalmente para enviar correo electrónico entre servidores?",
    options: ["SMTP", "POP3", "IMAP"],
    answer: 0,
    explanation: "SMTP se utiliza para el envío de correo electrónico.",
    reference: "Protocolos de correo"
  }
];